# Python Test 100
## Group Pandas 1 Questions 1..21

In [1]:
import os,sys
import pandas as pd
import numpy as np
from IPython.display import display, Image

In [2]:
aa = np.array([range(10),range(10)])
print(aa)
print(aa.shape)

[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]
(2, 10)

In [3]:
print(pd.__file__)
print(pd.__version__)
print(np.__file__)
print(np.__version__)

/Users/levselector/anaconda3/lib/python3.7/site-packages/pandas/__init__.py
0.24.2
/Users/levselector/anaconda3/lib/python3.7/site-packages/numpy/__init__.py
1.16.4

### -------------------- Question 1 --------------------

Explain how to install/upgrade pandas module

#### Answer

``` python
pandas stands for "Panel Data"
http://pandas.pydata.org/
It is a python module which is great for  analytical calculations.
Original author - Wes McKinney
Installation - it comes with Anaconda Python.
It is recommended to add these two channels:
  conda config --add channels anaconda
  conda config --add channels conda-forge
Updates happen when you update anaconda:
  conda update conda
  conda update anaconda

To play with pandas I recommend to use the following 
simple function ddd()
```

In [4]:
mydict = {} # empty dict
mydict["c1"] = [1,2,3]
mydict['c2'] = [4,5,6]
print(mydict)
print('-'*40)
aa = pd.DataFrame(  mydict , 
                    index = ['mama','papa','me'],
                    columns = ['c2','c1'])
display(aa)
print('-'*40)
print(aa.columns)

{'c1': [1, 2, 3], 'c2': [4, 5, 6]}
----------------------------------------

      c2  c1
mama   4   1
papa   5   2
me     6   3

----------------------------------------
Index(['c2', 'c1'], dtype='object')

In [5]:
aa.index[1]

'papa'

In [6]:
def ddd(nrows=10):
    """
    # returns a simple pandas DataFrame - useful for quick tests
    # nrows is number of rows (divisible by 10), for example:
    #     df = ddd()
    #     df = ddd(100)
    #     df = ddd(10**6)   # million rows
    """
    n_aa = 10
    nn = int(nrows/n_aa)
    if nn < 1:
        nn = 1
    aa = pd.DataFrame({
          'ii':nn*[0,1,2,3,4,5,np.nan,7,8,9],
          'i1':nn*[6,5,4,3,2,1,0,-1,-2,-3],
          'i2':nn*[6,5,4,4,1,1,0,-1,-2,-3],
          'ff':nn*[0.0,1.0,2.0,np.NaN,4.0,5.0,6.0,7.0,8.0,9.0],
          'f1':nn*[0.0,1.01,2.002,3.0003,4.00004,5.000005,6.0000006,7.0,8.0,9.0],
          'f2':nn*[1.11,2.22,3.33,4.44,5.55,7.77,9.99,0.01,-0.01,-1.11],
          'ss':nn*['s0','s1','狗','汽车',np.nan,'s5','s6','s7','s8','s9'],
          's1':nn*list(np.array(['s0','s1','s2','s2',np.nan,'s5','s6','s7','s8','s9'],dtype=np.str)),
          's2':nn*['1.11','2.22','3.33','4.44','5.55','7.77','9.99','0.01','-0.01','-1.11'],
          'bb':nn*[True, False, True, False, np.nan, False, True,np.nan, False, True],
          'b1':nn*[True, False, True, False, True, False, True, True, False, True],
          'xx':nn*list(range(n_aa)),
          'yy':nn*[x*50 + 60 + np.random.randn() for x in range(n_aa)]
    })
    aa = aa[['ii','i1','i2','ff','f1','f2','ss','s1','s2','bb','b1','xx','yy']].copy()
    aa.index = range(len(aa))

    if 1 <= nrows < 10:
        aa = aa[:nrows+1]
        
    return aa

In [7]:
aa = ddd()
display(aa.head(5).tail(2))
print("-"*40)
display(aa.tail(6).T.copy())

    ii  i1  i2   ff       f1    f2   ss   s1    s2     bb     b1  xx          yy
3  3.0   3   4  NaN  3.00030  4.44   汽车   s2  4.44  False  False   3  208.098583
4  4.0   2   1  4.0  4.00004  5.55  NaN  nan  5.55    NaN   True   4  258.950493

----------------------------------------

          4        5        6        7        8        9
ii        4        5      NaN        7        8        9
i1        2        1        0       -1       -2       -3
i2        1        1        0       -1       -2       -3
ff        4        5        6        7        8        9
f1  4.00004        5        6        7        8        9
f2     5.55     7.77     9.99     0.01    -0.01    -1.11
ss      NaN       s5       s6       s7       s8       s9
s1      nan       s5       s6       s7       s8       s9
s2     5.55     7.77     9.99     0.01    -0.01    -1.11
bb      NaN    False     True      NaN    False     True
b1     True    False     True     True    False     True
xx        4        5        6        7        8        9
yy   258.95  311.125  358.744  409.066  459.791  508.822

### -------------------- Question 2 --------------------

- Show how to test the type of the variable (is it an int? float? str?, list? dict? etc.) 
- Show how to test type of a column in a DataFrame 
- Show how to list types of all columns in a DataFrame

#### Answer

In [8]:
type({1:2,3:4})
aa = ddd()
aa['i1'].dtype

dtype('int64')

In [9]:
print("type of a python variable")

def print_type(obj):
    if type(obj) == int:
        print("  int")
    elif type(obj) == float:
        print("  float")
    elif type(obj) == str:
        print("  str")
    else:
        print("  unknown type")

print_type(1)
print_type(1.1)
print_type('mama')
print_type([1,2,3])

print("type of pd.DataFrame column")
aa = ddd()
print("aa.f1.dtype    = ",aa.f1.dtype)
print("aa['f1'].dtype = ",aa['f1'].dtype)

print('-'*40)
print("types of all pd.DataFrame columns")
print(aa.dtypes)

type of a python variable
  int
  float
  str
  unknown type
type of pd.DataFrame column
aa.f1.dtype    =  float64
aa['f1'].dtype =  float64
----------------------------------------
types of all pd.DataFrame columns
ii    float64
i1      int64
i2      int64
ff    float64
f1    float64
f2    float64
ss     object
s1     object
s2     object
bb     object
b1       bool
xx      int64
yy    float64
dtype: object

### -------------------- Question 3 --------------------

Show how to take a value from a particular cell of a dataframe
 - using df[col][row]                  # label based
 - using df.loc [row_label, col_label] # label based
 - using df.iloc[row_index, col_index] # indexes start with 0

#### Answer

In [10]:
aa = ddd()
aa.index = range(len(aa))
# aa.index = range(len(aa)-1,  -1,  -1)
print("aa['i2'][1]     =", aa['i2'][1]   )     # order: column(s), row(s)
print("aa.loc [1,'i2'] =", aa.loc [1,'i2'] )   # order: row(s), column(s)
print("aa.iloc[1,1]    =", aa.iloc[1, 1  ] )   # order: row(s), column(s)

aa['i2'][1]     = 5
aa.loc [1,'i2'] = 5
aa.iloc[1,1]    = 5

In [11]:
aa = ddd()
mask = (aa.f1 >= 1.5) & (aa.f1 < 5)
print(mask)
aa[mask]
# aa[2:4]
# aa

0    False
1    False
2     True
3     True
4     True
5    False
6    False
7    False
8    False
9    False
Name: f1, dtype: bool

    ii  i1  i2   ff       f1    f2   ss   s1    s2     bb     b1  xx          yy
2  2.0   4   4  2.0  2.00200  3.33    狗   s2  3.33   True   True   2  159.088997
3  3.0   3   4  NaN  3.00030  4.44   汽车   s2  4.44  False  False   3  207.486457
4  4.0   2   1  4.0  4.00004  5.55  NaN  nan  5.55    NaN   True   4  259.391116

In [12]:
aa=ddd()
N = len(aa)
aa.index = range(N-1,-1,-1)
aa.loc[2,'ii']

7.0

In [13]:
aa = [5,6,7,8,9,10,11,12]
bb = aa[:]
cc = aa
cc = aa
for ii in range(len(cc)):
    cc[ii] = pow(cc[ii],2)
print(id(aa))
print(id(cc))
print(id(bb))
print(aa)
print(cc)

140613156424584
140613156424584
140613156423496
[25, 36, 49, 64, 81, 100, 121, 144]
[25, 36, 49, 64, 81, 100, 121, 144]

In [14]:
x = 100000000
e = (1+1/x)**x
print(e)

2.7182817983473577

In [15]:
# Note:
#   loc  - by labels
#   iloc - by integer numbers of rows/columns - count starts with 0
#   ix   - deprecated, can do both

aa = ddd()
aa = aa.loc[:,['ii','i1','i2']] # [rows,cols]
aa.index = range(len(aa))  # 0,1,...,5,6
aa.index = aa.index.map(lambda x: 'm' + str(x))
display(aa)
#     id  i1  i2
# m0   0   6   6
# m1   1   5   5
# m2   2   4   4
# m3   3   3   4
# m4   4   2   1
# m5   5   1  1
# m6 NaN   0   0
print('-'*40)
print(aa.loc['m2','i2'])  # 4
# aa.iloc['m2','i2'] # ERROR
print(aa.iloc[2,2])       # 4

     ii  i1  i2
m0  0.0   6   6
m1  1.0   5   5
m2  2.0   4   4
m3  3.0   3   4
m4  4.0   2   1
m5  5.0   1   1
m6  NaN   0   0
m7  7.0  -1  -1
m8  8.0  -2  -2
m9  9.0  -3  -3

----------------------------------------
4
4

### -------------------- Question 4 --------------------

Extract a row from a DataFrame into a regular python list

#### Answer

In [16]:
aa=ddd()
print(aa.loc[1,:].values.tolist())
print(aa.loc[1,:].tolist())
print(aa.iloc[len(aa)-1].tolist())

[1.0, 5, 5, 1.0, 1.01, 2.22, 's1', 's1', '2.22', False, False, 1, 110.87468073642249]
[1.0, 5, 5, 1.0, 1.01, 2.22, 's1', 's1', '2.22', False, False, 1, 110.87468073642249]
[9.0, -3, -3, 9.0, 9.0, -1.11, 's9', 's9', '-1.11', True, True, 9, 509.0480239470938]

In [17]:
aa=ddd()
type(aa.i1.values)

numpy.ndarray

### -------------------- Question 5 --------------------

- Show to find rows which has the same value in a particular column
- Show how to use value_counts()
- Show how to count number of times each unique value appears in group, and for multiple columns 
- What is np.unique - and how is it used?
- Write a procedure to extract duplicate rows (by one or more columns)

#### Answer

In [18]:
# duplicated() - create true/false mask
aa=ddd()
aa.duplicated(['i2'])

0    False
1    False
2    False
3     True
4    False
5     True
6    False
7    False
8    False
9    False
dtype: bool

In [19]:
# value_counts()
# Returns pd.Series containing counts of unique values (excluding NaN)
# in descending order (the first element is the most frequently occuring).

aa['i2'].value_counts()

 4    2
 1    2
-2    1
 6    1
 5    1
-3    1
-1    1
 0    1
Name: i2, dtype: int64

In [20]:
# Show how to count number of times each unique value appears in group, and for multiple columns

data = [
  ['amazon.com',  'correct',   'correct'  ], 
  ['amazon.com',  'incorrect', 'correct'  ], 
  ['walmart.com', 'incorrect', 'correct'  ], 
  ['walmart.com', 'incorrect', 'incorrect']
]

source = pd.DataFrame(data, columns=['domain', 'price', 'product'])

source.groupby('domain').apply(lambda x: x[['price','product']].apply(lambda y: y.value_counts())).fillna(0)

                       price  product
domain
amazon.com  correct      1.0      2.0
            incorrect    1.0      0.0
walmart.com correct      0.0      1.0
            incorrect    2.0      1.0

In [21]:
# np.unique is a Numpy function which shows unique values in a column,
# and where they were found first time.

aa=ddd()
np.unique(aa.i2)

array([-3, -2, -1,  0,  1,  4,  5,  6])

In [22]:
# a procedure to extract duplicate rows (by one or more columns)

def show_duplicates(df, cols=[], include_nulls=True):
    """
    # accepts a dataframe df and a column (or list of columns)
    # if list of columns is not provided - uses all df columns
    # returns a dataframe consisting of rows of df
    # which have duplicate values in "cols"
    # sorted by "cols" so that duplciates are next to each other
    # Note - doesn't change index values of rows
    """
    # ---------------------------------
    aa = df.copy()
    mycols = cols
    # ---------------------------------
    if len(mycols) <= 0:
        mycols = aa.columns.tolist()
    elif type(mycols) != list:
        mycols = list(mycols)
    # ---------------------------------
    if not include_nulls:
        mask = False
        for mycol in mycols:
            mask = mask | (aa[mycol] != aa[mycol])  # test for null values
        aa = aa[~mask]                              # remove rows with nulls in mycols
    if len(aa) <= 0:
        return aa[:0]
    # ---------------------------------
    # duplicated() method returns Boolean Series denoting duplicate rows
    mask = aa.duplicated(subset=mycols, keep='first').values \
         | aa.duplicated(subset=mycols, keep='first').values
    aa = aa[mask]
    if len(aa) <= 0:
        return aa[:0]
    # ---------------------------------
    # sorting to keep duplicates together
    # Attention - can not sort by nulls
    # bb contains mycols except for cols which are completely nulls
    bb = aa[mycols]
    bb = bb.dropna(how='all',axis=1)
    # sort aa by columns in bb (thus avoiding nulls)
    aa = aa.sort_values(by=bb.columns.tolist())
    # ---------------------------------
    # sorting skips nulls thus messing up the order. 
    # Let's put nulls at the end
    mask = False
    for mycol in mycols:
        mask = mask | (aa[mycol] != aa[mycol])  # test for null values
    aa1 = aa[~mask]
    aa2 = aa[mask]
    aa = aa1.append(aa2)

    return aa

In [23]:
aa = ddd()
show_duplicates(df=aa, cols=['i2'], include_nulls=True)

    ii  i1  i2   ff        f1    f2  ss  s1    s2     bb     b1  xx         yy
5  5.0   1   1  5.0  5.000005  7.77  s5  s5  7.77  False  False   5  310.81362
3  3.0   3   4  NaN  3.000300  4.44  汽车  s2  4.44  False  False   3  208.96248

### -------------------- Question 6 --------------------

- Show how to append dataframes
- Show how to append a list (or series) of data to a dataframe

#### Answer

In [24]:
# append two dataframes one on top of the other
aa1 = ddd(5)
aa2 = ddd(5)
aa = aa1.append(aa2)
aa.index = range(len(aa))
display(aa)

     ii  i1  i2   ff        f1    f2   ss   s1    s2     bb     b1  xx          yy
0   0.0   6   6  0.0  0.000000  1.11   s0   s0  1.11   True   True   0   59.192022
1   1.0   5   5  1.0  1.010000  2.22   s1   s1  2.22  False  False   1  110.613789
2   2.0   4   4  2.0  2.002000  3.33    狗   s2  3.33   True   True   2  160.582327
3   3.0   3   4  NaN  3.000300  4.44   汽车   s2  4.44  False  False   3  210.626670
4   4.0   2   1  4.0  4.000040  5.55  NaN  nan  5.55    NaN   True   4  261.093836
5   5.0   1   1  5.0  5.000005  7.77   s5   s5  7.77  False  False   5  309.274546
6   0.0   6   6  0.0  0.000000  1.11   s0   s0  1.11   True   True   0   59.988549
7   1.0   5   5  1.0  1.010000  2.22   s1   s1  2.22  False  False   1  109.691834
8   2.0   4   4  2.0  2.002000  3.33    狗   s2  3.33   True   True   2  158.930466
9   3.0   3   4  NaN  3.000300  4.44   汽车   s2  4.44  False  False   3  209.912366
10  4.0   2   1  4.0  4.000040  5.55  NaN  nan  5.55    NaN   True   4  261.371339
11  5.0   1   1  5.0  5.000005  7.77   s5   s5  7.77  False  False   5  309.690183

In [25]:
# append a series or list by converting it to a DataFrame
aa = ddd()
bb = aa.loc[1].tolist()   # take 2nd row as a list
dd = pd.DataFrame([bb], columns=aa.columns)

# now append list
aa = aa.append(dd)
display(aa)

# Note: alternatively you can make 1-column dataframe - and transpose it
# bb=DataFrame(ss)
# bb.index = aa.columns
# aa.append(bb.T)

    ii  i1  i2   ff        f1    f2   ss   s1     s2     bb     b1  xx          yy
0  0.0   6   6  0.0  0.000000  1.11   s0   s0   1.11   True   True   0   62.321643
1  1.0   5   5  1.0  1.010000  2.22   s1   s1   2.22  False  False   1  109.809978
2  2.0   4   4  2.0  2.002000  3.33    狗   s2   3.33   True   True   2  161.093738
3  3.0   3   4  NaN  3.000300  4.44   汽车   s2   4.44  False  False   3  210.280515
4  4.0   2   1  4.0  4.000040  5.55  NaN  nan   5.55    NaN   True   4  258.570479
5  5.0   1   1  5.0  5.000005  7.77   s5   s5   7.77  False  False   5  308.762960
6  NaN   0   0  6.0  6.000001  9.99   s6   s6   9.99   True   True   6  360.936722
7  7.0  -1  -1  7.0  7.000000  0.01   s7   s7   0.01    NaN   True   7  411.747227
8  8.0  -2  -2  8.0  8.000000 -0.01   s8   s8  -0.01  False  False   8  459.184533
9  9.0  -3  -3  9.0  9.000000 -1.11   s9   s9  -1.11   True   True   9  509.640527
0  1.0   5   5  1.0  1.010000  2.22   s1   s1   2.22  False  False   1  109.809978

### -------------------- Question 7 --------------------

Show how to remove duplicate rows (duplicate is defined as having same value in a list of columns)

#### Answer

In [26]:
aa = aa.drop_duplicates(['i2']) 
# or
aa = aa.drop_duplicates(['i2'], keep='last') 
display(aa)

    ii  i1  i2   ff        f1    f2   ss   s1     s2     bb     b1  xx          yy
0  0.0   6   6  0.0  0.000000  1.11   s0   s0   1.11   True   True   0   62.321643
1  1.0   5   5  1.0  1.010000  2.22   s1   s1   2.22  False  False   1  109.809978
2  2.0   4   4  2.0  2.002000  3.33    狗   s2   3.33   True   True   2  161.093738
4  4.0   2   1  4.0  4.000040  5.55  NaN  nan   5.55    NaN   True   4  258.570479
6  NaN   0   0  6.0  6.000001  9.99   s6   s6   9.99   True   True   6  360.936722
7  7.0  -1  -1  7.0  7.000000  0.01   s7   s7   0.01    NaN   True   7  411.747227
8  8.0  -2  -2  8.0  8.000000 -0.01   s8   s8  -0.01  False  False   8  459.184533
9  9.0  -3  -3  9.0  9.000000 -1.11   s9   s9  -1.11   True   True   9  509.640527

### -------------------- Question 8 --------------------

Show how to use a mask using   &, |, ~, .isin(), .isnull()

#### Answer

In [27]:
aa=ddd()
mask = aa.f2.isnull()
display(aa[mask])
print('-'*40)
mask = aa.i1.isin([1,3,5])
display(aa[mask])
print('-'*40)
display(aa[~mask]) # shows the records where mask is False
print('-'*40)

# examples of masks based on more than one column
# mask = (aa.ii==1) & (aa.i2 == 4)
# mask = (aa.ii==1) | (aa.i2 == 4)

Empty DataFrame
Columns: [ii, i1, i2, ff, f1, f2, ss, s1, s2, bb, b1, xx, yy]
Index: []

----------------------------------------

    ii  i1  i2   ff        f1    f2  ss  s1    s2     bb     b1  xx          yy
1  1.0   5   5  1.0  1.010000  2.22  s1  s1  2.22  False  False   1  110.209856
3  3.0   3   4  NaN  3.000300  4.44  汽车  s2  4.44  False  False   3  210.029944
5  5.0   1   1  5.0  5.000005  7.77  s5  s5  7.77  False  False   5  310.778747

----------------------------------------

    ii  i1  i2   ff        f1    f2   ss   s1     s2     bb     b1  xx          yy
0  0.0   6   6  0.0  0.000000  1.11   s0   s0   1.11   True   True   0   60.616897
2  2.0   4   4  2.0  2.002000  3.33    狗   s2   3.33   True   True   2  159.241234
4  4.0   2   1  4.0  4.000040  5.55  NaN  nan   5.55    NaN   True   4  260.216686
6  NaN   0   0  6.0  6.000001  9.99   s6   s6   9.99   True   True   6  360.385281
7  7.0  -1  -1  7.0  7.000000  0.01   s7   s7   0.01    NaN   True   7  410.952472
8  8.0  -2  -2  8.0  8.000000 -0.01   s8   s8  -0.01  False  False   8  460.936823
9  9.0  -3  -3  9.0  9.000000 -1.11   s9   s9  -1.11   True   True   9  509.399675

----------------------------------------

### -------------------- Question 9 --------------------

Give an example of using a map() function on a pandas DataFrame column

#### Answer

In [28]:
aa=ddd()
str(aa.yy)

'0     59.717213\n1    109.702831\n2    160.205200\n3    211.616658\n4    261.396268\n5    309.832708\n6    360.713549\n7    409.840312\n8    459.359938\n9    511.177338\nName: yy, dtype: float64'

In [29]:
aa=ddd()
display(aa.yy.dtype)
aa['yy'] = aa.yy.map(lambda crocodile : str(round(crocodile,2)) + "abc")
display(aa)

dtype('float64')

    ii  i1  i2   ff        f1    f2   ss   s1     s2     bb     b1  xx         yy
0  0.0   6   6  0.0  0.000000  1.11   s0   s0   1.11   True   True   0   61.19abc
1  1.0   5   5  1.0  1.010000  2.22   s1   s1   2.22  False  False   1  107.93abc
2  2.0   4   4  2.0  2.002000  3.33    狗   s2   3.33   True   True   2  159.39abc
3  3.0   3   4  NaN  3.000300  4.44   汽车   s2   4.44  False  False   3  210.63abc
4  4.0   2   1  4.0  4.000040  5.55  NaN  nan   5.55    NaN   True   4  258.88abc
5  5.0   1   1  5.0  5.000005  7.77   s5   s5   7.77  False  False   5   309.0abc
6  NaN   0   0  6.0  6.000001  9.99   s6   s6   9.99   True   True   6  359.22abc
7  7.0  -1  -1  7.0  7.000000  0.01   s7   s7   0.01    NaN   True   7  410.24abc
8  8.0  -2  -2  8.0  8.000000 -0.01   s8   s8  -0.01  False  False   8  459.45abc
9  9.0  -3  -3  9.0  9.000000 -1.11   s9   s9  -1.11   True   True   9  512.31abc

### -------------------- Question 10 --------------------

Give example using map with lambda for dataframe operations

#### Answer

In [30]:
aa = ddd()
aa['s2'] = aa.ss + '__' + aa.i1.map(lambda x: str(x))

# make a list of values in column 'yy' 
# rounded to 2 digits after dot
aa['zz'] = aa['yy'].map(lambda x: round(x,2))
display(aa)

    ii  i1  i2   ff        f1    f2   ss   s1      s2     bb     b1  xx          yy      zz
0  0.0   6   6  0.0  0.000000  1.11   s0   s0   s0__6   True   True   0   60.389491   60.39
1  1.0   5   5  1.0  1.010000  2.22   s1   s1   s1__5  False  False   1  108.304917  108.30
2  2.0   4   4  2.0  2.002000  3.33    狗   s2    狗__4   True   True   2  159.614857  159.61
3  3.0   3   4  NaN  3.000300  4.44   汽车   s2   汽车__3  False  False   3  209.250567  209.25
4  4.0   2   1  4.0  4.000040  5.55  NaN  nan     NaN    NaN   True   4  260.872386  260.87
5  5.0   1   1  5.0  5.000005  7.77   s5   s5   s5__1  False  False   5  310.602994  310.60
6  NaN   0   0  6.0  6.000001  9.99   s6   s6   s6__0   True   True   6  360.384269  360.38
7  7.0  -1  -1  7.0  7.000000  0.01   s7   s7  s7__-1    NaN   True   7  408.789226  408.79
8  8.0  -2  -2  8.0  8.000000 -0.01   s8   s8  s8__-2  False  False   8  459.231522  459.23
9  9.0  -3  -3  9.0  9.000000 -1.11   s9   s9  s9__-3   True   True   9  509.300270  509.30

### -------------------- Question 11 --------------------

Give example using groupby().sum()

#### Answer

In [31]:
aa = ddd()
cc = aa.groupby(['i2'], as_index=False).sum()
display(cc)
print("-"*40)

# note - groupby().sum() will usually remove all 
# string columns from the result. To avoid it, you can use agg()
# But be carefull to avoid mixing NaN with strings - causes error 

aa = ddd()
aa['ss'] = aa.ss.fillna('_') # this removes NaN
cc = aa.groupby('i2', as_index=False).agg({'i1':np.sum,'ss':np.max})
display(cc)

   i2   ii  i1   ff        f1     f2     b1  xx          yy
0  -3  9.0  -3  9.0  9.000000  -1.11   True   9  509.294604
1  -2  8.0  -2  8.0  8.000000  -0.01  False   8  457.791001
2  -1  7.0  -1  7.0  7.000000   0.01   True   7  409.562483
3   0  0.0   0  6.0  6.000001   9.99   True   6  359.037280
4   1  9.0   3  9.0  9.000045  13.32   True   9  571.342364
5   4  5.0   7  2.0  5.002300   7.77   True   5  371.671314
6   5  1.0   5  1.0  1.010000   2.22  False   1  109.449105
7   6  0.0   6  0.0  0.000000   1.11   True   0   59.740769

----------------------------------------

   i2  i1  ss
0  -3  -3  s9
1  -2  -2  s8
2  -1  -1  s7
3   0   0  s6
4   1   3  s5
5   4   7   狗
6   5   5  s1
7   6   6  s0

### -------------------- Question 12 --------------------

Give example using groupby().aggregate()

#### Answer

In [32]:
aa = ddd()
bb = aa.groupby('i2', as_index=True).aggregate({'yy':np.sum, 'xx':np.max}) 
display(bb)

            yy  xx
i2
-3  510.973009   9
-2  461.574263   8
-1  410.852080   7
 0  359.752592   6
 1  569.117457   5
 4  369.679901   3
 5  110.268509   1
 6   60.397002   0

### -------------------- Question 13 --------------------

Show how to sort a dataframe by a list of columns

#### Answer

In [33]:
cc = aa.sort_values(by=['i2','yy'])
display(cc)

    ii  i1  i2   ff        f1    f2   ss   s1     s2     bb     b1  xx          yy
9  9.0  -3  -3  9.0  9.000000 -1.11   s9   s9  -1.11   True   True   9  510.973009
8  8.0  -2  -2  8.0  8.000000 -0.01   s8   s8  -0.01  False  False   8  461.574263
7  7.0  -1  -1  7.0  7.000000  0.01   s7   s7   0.01    NaN   True   7  410.852080
6  NaN   0   0  6.0  6.000001  9.99   s6   s6   9.99   True   True   6  359.752592
4  4.0   2   1  4.0  4.000040  5.55  NaN  nan   5.55    NaN   True   4  260.591489
5  5.0   1   1  5.0  5.000005  7.77   s5   s5   7.77  False  False   5  308.525968
2  2.0   4   4  2.0  2.002000  3.33    狗   s2   3.33   True   True   2  159.209372
3  3.0   3   4  NaN  3.000300  4.44   汽车   s2   4.44  False  False   3  210.470529
1  1.0   5   5  1.0  1.010000  2.22   s1   s1   2.22  False  False   1  110.268509
0  0.0   6   6  0.0  0.000000  1.11   s0   s0   1.11   True   True   0   60.397002

### -------------------- Question 14 --------------------

Show how to delete some rows from dataframe - and reindex

#### Answer

In [34]:
aa = ddd()
aa = aa.drop([1,3,5]) # remove several rows 
display(aa)

    ii  i1  i2   ff        f1    f2   ss   s1     s2     bb     b1  xx          yy
0  0.0   6   6  0.0  0.000000  1.11   s0   s0   1.11   True   True   0   60.881133
2  2.0   4   4  2.0  2.002000  3.33    狗   s2   3.33   True   True   2  161.348142
4  4.0   2   1  4.0  4.000040  5.55  NaN  nan   5.55    NaN   True   4  260.485762
6  NaN   0   0  6.0  6.000001  9.99   s6   s6   9.99   True   True   6  360.229121
7  7.0  -1  -1  7.0  7.000000  0.01   s7   s7   0.01    NaN   True   7  408.436042
8  8.0  -2  -2  8.0  8.000000 -0.01   s8   s8  -0.01  False  False   8  460.985868
9  9.0  -3  -3  9.0  9.000000 -1.11   s9   s9  -1.11   True   True   9  508.669022

In [35]:
# remove rows based on a mask
aa = ddd()
mask = aa['ii'].map(lambda x: x > 3) # True when aa.ii > 3
aa = aa[~mask]                       # take only where a.ii <= 3 or NaN
display(aa)
print('-'*40)
mask = aa['ii'].map(lambda x: x in (0,1,4))
aa = aa[~mask]
display(aa)

    ii  i1  i2   ff        f1    f2  ss  s1    s2     bb     b1  xx          yy
0  0.0   6   6  0.0  0.000000  1.11  s0  s0  1.11   True   True   0   59.832859
1  1.0   5   5  1.0  1.010000  2.22  s1  s1  2.22  False  False   1  109.352895
2  2.0   4   4  2.0  2.002000  3.33   狗  s2  3.33   True   True   2  160.062045
3  3.0   3   4  NaN  3.000300  4.44  汽车  s2  4.44  False  False   3  210.888036
6  NaN   0   0  6.0  6.000001  9.99  s6  s6  9.99   True   True   6  359.248295

----------------------------------------

    ii  i1  i2   ff        f1    f2  ss  s1    s2     bb     b1  xx          yy
2  2.0   4   4  2.0  2.002000  3.33   狗  s2  3.33   True   True   2  160.062045
3  3.0   3   4  NaN  3.000300  4.44  汽车  s2  4.44  False  False   3  210.888036
6  NaN   0   0  6.0  6.000001  9.99  s6  s6  9.99   True   True   6  359.248295

In [36]:
# after removing rows you may want to index rows sequentially
aa = ddd()
aa.reindex() # doesn't change index unless you provide it 
print('-0'*30)
aa.index = range(len(aa))
display(aa)
print('-1'*30)
# note - you can shift index
aa.index = range(100,100+len(aa))
display(aa)
print('-2'*30)
# you can even make all index values the same - although it is pointless
aa.index = [2]*len(aa)
display(aa)

-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0

    ii  i1  i2   ff        f1    f2   ss   s1     s2     bb     b1  xx          yy
0  0.0   6   6  0.0  0.000000  1.11   s0   s0   1.11   True   True   0   59.975985
1  1.0   5   5  1.0  1.010000  2.22   s1   s1   2.22  False  False   1  111.301231
2  2.0   4   4  2.0  2.002000  3.33    狗   s2   3.33   True   True   2  159.084003
3  3.0   3   4  NaN  3.000300  4.44   汽车   s2   4.44  False  False   3  210.673908
4  4.0   2   1  4.0  4.000040  5.55  NaN  nan   5.55    NaN   True   4  260.876996
5  5.0   1   1  5.0  5.000005  7.77   s5   s5   7.77  False  False   5  311.499644
6  NaN   0   0  6.0  6.000001  9.99   s6   s6   9.99   True   True   6  358.604588
7  7.0  -1  -1  7.0  7.000000  0.01   s7   s7   0.01    NaN   True   7  410.007842
8  8.0  -2  -2  8.0  8.000000 -0.01   s8   s8  -0.01  False  False   8  459.591339
9  9.0  -3  -3  9.0  9.000000 -1.11   s9   s9  -1.11   True   True   9  509.108235

-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1

      ii  i1  i2   ff        f1    f2   ss   s1     s2     bb     b1  xx          yy
100  0.0   6   6  0.0  0.000000  1.11   s0   s0   1.11   True   True   0   59.975985
101  1.0   5   5  1.0  1.010000  2.22   s1   s1   2.22  False  False   1  111.301231
102  2.0   4   4  2.0  2.002000  3.33    狗   s2   3.33   True   True   2  159.084003
103  3.0   3   4  NaN  3.000300  4.44   汽车   s2   4.44  False  False   3  210.673908
104  4.0   2   1  4.0  4.000040  5.55  NaN  nan   5.55    NaN   True   4  260.876996
105  5.0   1   1  5.0  5.000005  7.77   s5   s5   7.77  False  False   5  311.499644
106  NaN   0   0  6.0  6.000001  9.99   s6   s6   9.99   True   True   6  358.604588
107  7.0  -1  -1  7.0  7.000000  0.01   s7   s7   0.01    NaN   True   7  410.007842
108  8.0  -2  -2  8.0  8.000000 -0.01   s8   s8  -0.01  False  False   8  459.591339
109  9.0  -3  -3  9.0  9.000000 -1.11   s9   s9  -1.11   True   True   9  509.108235

-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2

    ii  i1  i2   ff        f1    f2   ss   s1     s2     bb     b1  xx          yy
2  0.0   6   6  0.0  0.000000  1.11   s0   s0   1.11   True   True   0   59.975985
2  1.0   5   5  1.0  1.010000  2.22   s1   s1   2.22  False  False   1  111.301231
2  2.0   4   4  2.0  2.002000  3.33    狗   s2   3.33   True   True   2  159.084003
2  3.0   3   4  NaN  3.000300  4.44   汽车   s2   4.44  False  False   3  210.673908
2  4.0   2   1  4.0  4.000040  5.55  NaN  nan   5.55    NaN   True   4  260.876996
2  5.0   1   1  5.0  5.000005  7.77   s5   s5   7.77  False  False   5  311.499644
2  NaN   0   0  6.0  6.000001  9.99   s6   s6   9.99   True   True   6  358.604588
2  7.0  -1  -1  7.0  7.000000  0.01   s7   s7   0.01    NaN   True   7  410.007842
2  8.0  -2  -2  8.0  8.000000 -0.01   s8   s8  -0.01  False  False   8  459.591339
2  9.0  -3  -3  9.0  9.000000 -1.11   s9   s9  -1.11   True   True   9  509.108235

### -------------------- Question 15 --------------------

Show how to add rows to a dataframe 
<br>(add 2 dataframes together vertically - and reindex)

#### Answer

In [37]:
aa=ddd()
aa = aa.append(aa[2:4],ignore_index=True)
display(aa)

     ii  i1  i2   ff        f1    f2   ss   s1     s2     bb     b1  xx          yy
0   0.0   6   6  0.0  0.000000  1.11   s0   s0   1.11   True   True   0   60.520120
1   1.0   5   5  1.0  1.010000  2.22   s1   s1   2.22  False  False   1  109.727508
2   2.0   4   4  2.0  2.002000  3.33    狗   s2   3.33   True   True   2  160.675240
3   3.0   3   4  NaN  3.000300  4.44   汽车   s2   4.44  False  False   3  208.319512
4   4.0   2   1  4.0  4.000040  5.55  NaN  nan   5.55    NaN   True   4  260.461321
5   5.0   1   1  5.0  5.000005  7.77   s5   s5   7.77  False  False   5  310.650472
6   NaN   0   0  6.0  6.000001  9.99   s6   s6   9.99   True   True   6  360.409197
7   7.0  -1  -1  7.0  7.000000  0.01   s7   s7   0.01    NaN   True   7  409.012103
8   8.0  -2  -2  8.0  8.000000 -0.01   s8   s8  -0.01  False  False   8  459.639505
9   9.0  -3  -3  9.0  9.000000 -1.11   s9   s9  -1.11   True   True   9  509.408420
10  2.0   4   4  2.0  2.002000  3.33    狗   s2   3.33   True   True   2  160.675240
11  3.0   3   4  NaN  3.000300  4.44   汽车   s2   4.44  False  False   3  208.319512

### -------------------- Question 16 --------------------

- Show how to write dataframe to csv file
- Show how to read it back

#### Answer

In [38]:
aa = ddd()
aa.to_csv('junk.csv', sep='|', header=True, index=False)
bb = pd.read_csv('junk.csv', sep='|')
display(bb)

    ii  i1  i2   ff        f1    f2   ss   s1    s2     bb     b1  xx          yy
0  0.0   6   6  0.0  0.000000  1.11   s0   s0  1.11   True   True   0   61.869672
1  1.0   5   5  1.0  1.010000  2.22   s1   s1  2.22  False  False   1  111.346819
2  2.0   4   4  2.0  2.002000  3.33    狗   s2  3.33   True   True   2  160.085493
3  3.0   3   4  NaN  3.000300  4.44   汽车   s2  4.44  False  False   3  209.052525
4  4.0   2   1  4.0  4.000040  5.55  NaN  NaN  5.55    NaN   True   4  260.559886
5  5.0   1   1  5.0  5.000005  7.77   s5   s5  7.77  False  False   5  311.823515
6  NaN   0   0  6.0  6.000001  9.99   s6   s6  9.99   True   True   6  360.432074
7  7.0  -1  -1  7.0  7.000000  0.01   s7   s7  0.01    NaN   True   7  411.053783
8  8.0  -2  -2  8.0  8.000000 -0.01   s8   s8 -0.01  False  False   8  461.386606
9  9.0  -3  -3  9.0  9.000000 -1.11   s9   s9 -1.11   True   True   9  509.640621

### -------------------- Question 17 --------------------

- Show how to add columns to pandas DataFrame
- Show how to calculate column values from numeric/string values in other columns.
- Show how to delete one or more columns

#### Answer

In [39]:
aa = ddd()
aa['c4'] = None         # populate with same value
display(aa)
print('-0'*30)
col2=[1,2,3,4,5,6,7,8,9,0]
aa['c4'] = col2         # list becomes a column
display(aa)
print('-1'*30)
aa['c4'] = "-"
display(aa)
print('-2'*30)

# adding a column - and populating it using vectorized operation on columns
aa['c5']= 2*aa['i1'] + 3*aa['i2'] + 5
display(aa)
print('-3'*30)

# calculating column values from other columns:
aa['c4']= 2*aa['i1'] + 3*aa['i2'] + 5
aa['s2'] = aa.ss + '__' + aa.i1.map(lambda x: str(x))
display(aa)
print('-4'*30)

# Deleting one column
del aa['s1']
display(aa)
print('-5'*30)

# Deleting many columns
aa = aa.drop(['i1','i2','c4'], axis=1)
display(aa)

    ii  i1  i2   ff        f1    f2   ss   s1     s2     bb     b1  xx          yy    c4
0  0.0   6   6  0.0  0.000000  1.11   s0   s0   1.11   True   True   0   59.412107  None
1  1.0   5   5  1.0  1.010000  2.22   s1   s1   2.22  False  False   1  110.741464  None
2  2.0   4   4  2.0  2.002000  3.33    狗   s2   3.33   True   True   2  159.163642  None
3  3.0   3   4  NaN  3.000300  4.44   汽车   s2   4.44  False  False   3  209.784417  None
4  4.0   2   1  4.0  4.000040  5.55  NaN  nan   5.55    NaN   True   4  260.938055  None
5  5.0   1   1  5.0  5.000005  7.77   s5   s5   7.77  False  False   5  312.594908  None
6  NaN   0   0  6.0  6.000001  9.99   s6   s6   9.99   True   True   6  359.709787  None
7  7.0  -1  -1  7.0  7.000000  0.01   s7   s7   0.01    NaN   True   7  408.680221  None
8  8.0  -2  -2  8.0  8.000000 -0.01   s8   s8  -0.01  False  False   8  458.617713  None
9  9.0  -3  -3  9.0  9.000000 -1.11   s9   s9  -1.11   True   True   9  510.398464  None

-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0

    ii  i1  i2   ff        f1    f2   ss   s1     s2     bb     b1  xx          yy  c4
0  0.0   6   6  0.0  0.000000  1.11   s0   s0   1.11   True   True   0   59.412107   1
1  1.0   5   5  1.0  1.010000  2.22   s1   s1   2.22  False  False   1  110.741464   2
2  2.0   4   4  2.0  2.002000  3.33    狗   s2   3.33   True   True   2  159.163642   3
3  3.0   3   4  NaN  3.000300  4.44   汽车   s2   4.44  False  False   3  209.784417   4
4  4.0   2   1  4.0  4.000040  5.55  NaN  nan   5.55    NaN   True   4  260.938055   5
5  5.0   1   1  5.0  5.000005  7.77   s5   s5   7.77  False  False   5  312.594908   6
6  NaN   0   0  6.0  6.000001  9.99   s6   s6   9.99   True   True   6  359.709787   7
7  7.0  -1  -1  7.0  7.000000  0.01   s7   s7   0.01    NaN   True   7  408.680221   8
8  8.0  -2  -2  8.0  8.000000 -0.01   s8   s8  -0.01  False  False   8  458.617713   9
9  9.0  -3  -3  9.0  9.000000 -1.11   s9   s9  -1.11   True   True   9  510.398464   0

-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1

    ii  i1  i2   ff        f1    f2   ss   s1     s2     bb     b1  xx          yy c4
0  0.0   6   6  0.0  0.000000  1.11   s0   s0   1.11   True   True   0   59.412107  -
1  1.0   5   5  1.0  1.010000  2.22   s1   s1   2.22  False  False   1  110.741464  -
2  2.0   4   4  2.0  2.002000  3.33    狗   s2   3.33   True   True   2  159.163642  -
3  3.0   3   4  NaN  3.000300  4.44   汽车   s2   4.44  False  False   3  209.784417  -
4  4.0   2   1  4.0  4.000040  5.55  NaN  nan   5.55    NaN   True   4  260.938055  -
5  5.0   1   1  5.0  5.000005  7.77   s5   s5   7.77  False  False   5  312.594908  -
6  NaN   0   0  6.0  6.000001  9.99   s6   s6   9.99   True   True   6  359.709787  -
7  7.0  -1  -1  7.0  7.000000  0.01   s7   s7   0.01    NaN   True   7  408.680221  -
8  8.0  -2  -2  8.0  8.000000 -0.01   s8   s8  -0.01  False  False   8  458.617713  -
9  9.0  -3  -3  9.0  9.000000 -1.11   s9   s9  -1.11   True   True   9  510.398464  -

-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2

    ii  i1  i2   ff        f1    f2   ss   s1     s2     bb     b1  xx          yy c4  c5
0  0.0   6   6  0.0  0.000000  1.11   s0   s0   1.11   True   True   0   59.412107  -  35
1  1.0   5   5  1.0  1.010000  2.22   s1   s1   2.22  False  False   1  110.741464  -  30
2  2.0   4   4  2.0  2.002000  3.33    狗   s2   3.33   True   True   2  159.163642  -  25
3  3.0   3   4  NaN  3.000300  4.44   汽车   s2   4.44  False  False   3  209.784417  -  23
4  4.0   2   1  4.0  4.000040  5.55  NaN  nan   5.55    NaN   True   4  260.938055  -  12
5  5.0   1   1  5.0  5.000005  7.77   s5   s5   7.77  False  False   5  312.594908  -  10
6  NaN   0   0  6.0  6.000001  9.99   s6   s6   9.99   True   True   6  359.709787  -   5
7  7.0  -1  -1  7.0  7.000000  0.01   s7   s7   0.01    NaN   True   7  408.680221  -   0
8  8.0  -2  -2  8.0  8.000000 -0.01   s8   s8  -0.01  False  False   8  458.617713  -  -5
9  9.0  -3  -3  9.0  9.000000 -1.11   s9   s9  -1.11   True   True   9  510.398464  - -10

-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3

    ii  i1  i2   ff        f1    f2   ss   s1      s2     bb     b1  xx          yy  c4  c5
0  0.0   6   6  0.0  0.000000  1.11   s0   s0   s0__6   True   True   0   59.412107  35  35
1  1.0   5   5  1.0  1.010000  2.22   s1   s1   s1__5  False  False   1  110.741464  30  30
2  2.0   4   4  2.0  2.002000  3.33    狗   s2    狗__4   True   True   2  159.163642  25  25
3  3.0   3   4  NaN  3.000300  4.44   汽车   s2   汽车__3  False  False   3  209.784417  23  23
4  4.0   2   1  4.0  4.000040  5.55  NaN  nan     NaN    NaN   True   4  260.938055  12  12
5  5.0   1   1  5.0  5.000005  7.77   s5   s5   s5__1  False  False   5  312.594908  10  10
6  NaN   0   0  6.0  6.000001  9.99   s6   s6   s6__0   True   True   6  359.709787   5   5
7  7.0  -1  -1  7.0  7.000000  0.01   s7   s7  s7__-1    NaN   True   7  408.680221   0   0
8  8.0  -2  -2  8.0  8.000000 -0.01   s8   s8  s8__-2  False  False   8  458.617713  -5  -5
9  9.0  -3  -3  9.0  9.000000 -1.11   s9   s9  s9__-3   True   True   9  510.398464 -10 -10

-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4

    ii  i1  i2   ff        f1    f2   ss      s2     bb     b1  xx          yy  c4  c5
0  0.0   6   6  0.0  0.000000  1.11   s0   s0__6   True   True   0   59.412107  35  35
1  1.0   5   5  1.0  1.010000  2.22   s1   s1__5  False  False   1  110.741464  30  30
2  2.0   4   4  2.0  2.002000  3.33    狗    狗__4   True   True   2  159.163642  25  25
3  3.0   3   4  NaN  3.000300  4.44   汽车   汽车__3  False  False   3  209.784417  23  23
4  4.0   2   1  4.0  4.000040  5.55  NaN     NaN    NaN   True   4  260.938055  12  12
5  5.0   1   1  5.0  5.000005  7.77   s5   s5__1  False  False   5  312.594908  10  10
6  NaN   0   0  6.0  6.000001  9.99   s6   s6__0   True   True   6  359.709787   5   5
7  7.0  -1  -1  7.0  7.000000  0.01   s7  s7__-1    NaN   True   7  408.680221   0   0
8  8.0  -2  -2  8.0  8.000000 -0.01   s8  s8__-2  False  False   8  458.617713  -5  -5
9  9.0  -3  -3  9.0  9.000000 -1.11   s9  s9__-3   True   True   9  510.398464 -10 -10

-5-5-5-5-5-5-5-5-5-5-5-5-5-5-5-5-5-5-5-5-5-5-5-5-5-5-5-5-5-5

    ii   ff        f1    f2   ss      s2     bb     b1  xx          yy  c5
0  0.0  0.0  0.000000  1.11   s0   s0__6   True   True   0   59.412107  35
1  1.0  1.0  1.010000  2.22   s1   s1__5  False  False   1  110.741464  30
2  2.0  2.0  2.002000  3.33    狗    狗__4   True   True   2  159.163642  25
3  3.0  NaN  3.000300  4.44   汽车   汽车__3  False  False   3  209.784417  23
4  4.0  4.0  4.000040  5.55  NaN     NaN    NaN   True   4  260.938055  12
5  5.0  5.0  5.000005  7.77   s5   s5__1  False  False   5  312.594908  10
6  NaN  6.0  6.000001  9.99   s6   s6__0   True   True   6  359.709787   5
7  7.0  7.0  7.000000  0.01   s7  s7__-1    NaN   True   7  408.680221   0
8  8.0  8.0  8.000000 -0.01   s8  s8__-2  False  False   8  458.617713  -5
9  9.0  9.0  9.000000 -1.11   s9  s9__-3   True   True   9  510.398464 -10

### -------------------- Question 18 --------------------

Show how to calculate a pandas DataFrame column 
as a linear combination of some other columns

#### Answer

In [40]:
aa = ddd()
aa['c4']= 2*aa['i1'] + 3*aa['i2'] + 5 
display(aa)

    ii  i1  i2   ff        f1    f2   ss   s1     s2     bb     b1  xx          yy  c4
0  0.0   6   6  0.0  0.000000  1.11   s0   s0   1.11   True   True   0   58.397920  35
1  1.0   5   5  1.0  1.010000  2.22   s1   s1   2.22  False  False   1  110.849525  30
2  2.0   4   4  2.0  2.002000  3.33    狗   s2   3.33   True   True   2  159.711857  25
3  3.0   3   4  NaN  3.000300  4.44   汽车   s2   4.44  False  False   3  211.861524  23
4  4.0   2   1  4.0  4.000040  5.55  NaN  nan   5.55    NaN   True   4  259.808958  12
5  5.0   1   1  5.0  5.000005  7.77   s5   s5   7.77  False  False   5  311.137453  10
6  NaN   0   0  6.0  6.000001  9.99   s6   s6   9.99   True   True   6  360.777097   5
7  7.0  -1  -1  7.0  7.000000  0.01   s7   s7   0.01    NaN   True   7  410.144619   0
8  8.0  -2  -2  8.0  8.000000 -0.01   s8   s8  -0.01  False  False   8  459.761297  -5
9  9.0  -3  -3  9.0  9.000000 -1.11   s9   s9  -1.11   True   True   9  510.282339 -10

### -------------------- Question 19 --------------------

Show how to calculate a DataFrame column 
from several other columns while using str() and int().<br>
Hint - use map(lambda ..)

#### Answer

In [41]:
aa = ddd()
aa['s3'] = aa['yy'].map(lambda x: int(x)) 
aa['s4']= '>>>' + aa.s3.map(lambda x: str(x)) + '<<<'
display(aa)

    ii  i1  i2   ff        f1    f2   ss   s1     s2     bb     b1  xx          yy   s3         s4
0  0.0   6   6  0.0  0.000000  1.11   s0   s0   1.11   True   True   0   60.080559   60   >>>60<<<
1  1.0   5   5  1.0  1.010000  2.22   s1   s1   2.22  False  False   1  109.914353  109  >>>109<<<
2  2.0   4   4  2.0  2.002000  3.33    狗   s2   3.33   True   True   2  160.321482  160  >>>160<<<
3  3.0   3   4  NaN  3.000300  4.44   汽车   s2   4.44  False  False   3  210.582375  210  >>>210<<<
4  4.0   2   1  4.0  4.000040  5.55  NaN  nan   5.55    NaN   True   4  259.623300  259  >>>259<<<
5  5.0   1   1  5.0  5.000005  7.77   s5   s5   7.77  False  False   5  311.902589  311  >>>311<<<
6  NaN   0   0  6.0  6.000001  9.99   s6   s6   9.99   True   True   6  358.693055  358  >>>358<<<
7  7.0  -1  -1  7.0  7.000000  0.01   s7   s7   0.01    NaN   True   7  408.008863  408  >>>408<<<
8  8.0  -2  -2  8.0  8.000000 -0.01   s8   s8  -0.01  False  False   8  459.645359  459  >>>459<<<
9  9.0  -3  -3  9.0  9.000000 -1.11   s9   s9  -1.11   True   True   9  509.003351  509  >>>509<<<

### -------------------- Question 20 --------------------

Show how to define a mask using regex on one column, and numeric comparison on the other column

#### Answer

In [42]:
import re
aa = ddd()
mask = (aa.i2.map(lambda x: True if re.search(r'4',str(x)) else False)) & (aa.xx > 2)
display(mask)
display(aa[mask])

# more examples
# mask = ( df.a == 1) & (df.b == 2)
# mask = ( df.a == 1) | (df.b == 2)
# mask = ( df.a == 1) | df.b.isin([1,2,3])
# mask = ( df.a == 1) | df.b.map(lambda x: ......)
# mask = ( df.a == 1) | df.b.map(lambda x: ......)  |  df.c.map(lambda x: ......)

0    False
1    False
2    False
3     True
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

    ii  i1  i2  ff      f1    f2  ss  s1    s2     bb     b1  xx        yy
3  3.0   3   4 NaN  3.0003  4.44  汽车  s2  4.44  False  False   3  209.7324

### -------------------- Question 21 --------------------

String operations on columns
<br>How to define a mask using a regular expression

In [43]:
aa = ddd()
mask = aa.ss.map(lambda x: True if re.search(r's[1,3]',str(x)) else False)
display(aa[mask])

    ii  i1  i2   ff    f1    f2  ss  s1    s2     bb     b1  xx          yy
1  1.0   5   5  1.0  1.01  2.22  s1  s1  2.22  False  False   1  109.236769