# Python Test 100
## Group Pandas 1 Questions 1..21

In [8]:
import os,sys
import pandas as pd
import numpy as np
from IPython.display import display, Image

In [9]:
aa = np.array([range(10),range(10)])
print(aa)
print(aa.shape)

[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]
(2, 10)

In [10]:
print(pd.__file__)
print(pd.__version__)
print(np.__file__)
print(np.__version__)

/Users/levselector/anaconda3/lib/python3.8/site-packages/pandas/__init__.py
1.0.5
/Users/levselector/anaconda3/lib/python3.8/site-packages/numpy/__init__.py
1.18.5

### -------------------- Question 1 --------------------

Explain how to install/upgrade pandas module

#### Answer

``` python
pandas stands for "Panel Data"
http://pandas.pydata.org/
It is a python module which is great for  analytical calculations.
Original author - Wes McKinney
Installation - it comes with Anaconda Python.
It is recommended to add these two channels:
  conda config --add channels anaconda
  conda config --add channels conda-forge
Updates happen when you update anaconda:
  conda update conda
  conda update anaconda

To play with pandas I recommend to use the following 
simple function ddd()
```

In [11]:
mydict = {} # empty dict
mydict["c1"] = [1,2,3]
mydict['c2'] = [4,5,6]
print(mydict)
print('-'*40)
aa = pd.DataFrame(  mydict , 
                    index = ['mama','papa','me'],
                    columns = ['c2','c1'])
display(aa)
print('-'*40)
print(aa.columns)

{'c1': [1, 2, 3], 'c2': [4, 5, 6]}
----------------------------------------

      c2  c1
mama   4   1
papa   5   2
me     6   3

----------------------------------------
Index(['c2', 'c1'], dtype='object')

In [12]:
aa.index[1]

'papa'

In [13]:
def ddd(nrows=10):
    """
    # returns a simple pandas DataFrame - useful for quick tests
    # nrows is number of rows (divisible by 10), for example:
    #     df = ddd()
    #     df = ddd(100)
    #     df = ddd(10**6)   # million rows
    """
    n_aa = 10
    nn = int(nrows/n_aa)
    if nn < 1:
        nn = 1
    aa = pd.DataFrame({
          'ii':nn*[0,1,2,3,4,5,np.nan,7,8,9],
          'i1':nn*[6,5,4,3,2,1,0,-1,-2,-3],
          'i2':nn*[6,5,4,4,1,1,0,-1,-2,-3],
          'ff':nn*[0.0,1.0,2.0,np.NaN,4.0,5.0,6.0,7.0,8.0,9.0],
          'f1':nn*[0.0,1.01,2.002,3.0003,4.00004,5.000005,6.0000006,7.0,8.0,9.0],
          'f2':nn*[1.11,2.22,3.33,4.44,5.55,7.77,9.99,0.01,-0.01,-1.11],
          'ss':nn*['s0','s1','狗','汽车',np.nan,'s5','s6','s7','s8','s9'],
          's1':nn*list(np.array(['s0','s1','s2','s2',np.nan,'s5','s6','s7','s8','s9'],dtype=np.str)),
          's2':nn*['1.11','2.22','3.33','4.44','5.55','7.77','9.99','0.01','-0.01','-1.11'],
          'bb':nn*[True, False, True, False, np.nan, False, True,np.nan, False, True],
          'b1':nn*[True, False, True, False, True, False, True, True, False, True],
          'xx':nn*list(range(n_aa)),
          'yy':nn*[x*50 + 60 + np.random.randn() for x in range(n_aa)]
    })
    aa = aa[['ii','i1','i2','ff','f1','f2','ss','s1','s2','bb','b1','xx','yy']].copy()
    aa.index = range(len(aa))

    if 1 <= nrows < 10:
        aa = aa[:nrows+1]
        
    return aa

In [14]:
aa = ddd()
display(aa.head(5).tail(2))
print("-"*40)
display(aa.tail(6).T.copy())

    ii  i1  i2   ff       f1    f2   ss   s1    s2     bb     b1  xx          yy
3  3.0   3   4  NaN  3.00030  4.44   汽车   s2  4.44  False  False   3  209.053810
4  4.0   2   1  4.0  4.00004  5.55  NaN  nan  5.55    NaN   True   4  259.494625

----------------------------------------

          4        5        6        7        8        9
ii        4        5      NaN        7        8        9
i1        2        1        0       -1       -2       -3
i2        1        1        0       -1       -2       -3
ff        4        5        6        7        8        9
f1  4.00004        5        6        7        8        9
f2     5.55     7.77     9.99     0.01    -0.01    -1.11
ss      NaN       s5       s6       s7       s8       s9
s1      nan       s5       s6       s7       s8       s9
s2     5.55     7.77     9.99     0.01    -0.01    -1.11
bb      NaN    False     True      NaN    False     True
b1     True    False     True     True    False     True
xx        4        5        6        7        8        9
yy  259.495  310.994  358.908  408.901  459.816  508.551

### -------------------- Question 2 --------------------

- Show how to test the type of the variable (is it an int? float? str?, list? dict? etc.) 
- Show how to test type of a column in a DataFrame 
- Show how to list types of all columns in a DataFrame

#### Answer

In [15]:
type({1:2,3:4})
aa = ddd()
aa['i1'].dtype

dtype('int64')

In [16]:
print("type of a python variable")

def print_type(obj):
    if type(obj) == int:
        print("  int")
    elif type(obj) == float:
        print("  float")
    elif type(obj) == str:
        print("  str")
    else:
        print("  unknown type")

print_type(1)
print_type(1.1)
print_type('mama')
print_type([1,2,3])

print("type of pd.DataFrame column")
aa = ddd()
print("aa.f1.dtype    = ",aa.f1.dtype)
print("aa['f1'].dtype = ",aa['f1'].dtype)

print('-'*40)
print("types of all pd.DataFrame columns")
print(aa.dtypes)

type of a python variable
  int
  float
  str
  unknown type
type of pd.DataFrame column
aa.f1.dtype    =  float64
aa['f1'].dtype =  float64
----------------------------------------
types of all pd.DataFrame columns
ii    float64
i1      int64
i2      int64
ff    float64
f1    float64
f2    float64
ss     object
s1     object
s2     object
bb     object
b1       bool
xx      int64
yy    float64
dtype: object

### -------------------- Question 3 --------------------

Show how to take a value from a particular cell of a dataframe
 - using df[col][row]                  # label based
 - using df.loc [row_label, col_label] # label based
 - using df.iloc[row_index, col_index] # indexes start with 0

#### Answer

In [17]:
aa = ddd()
aa.index = range(len(aa))
# aa.index = range(len(aa)-1,  -1,  -1)
print("aa['i2'][1]     =", aa['i2'][1]   )     # order: column(s), row(s)
print("aa.loc [1,'i2'] =", aa.loc [1,'i2'] )   # order: row(s), column(s)
print("aa.iloc[1,1]    =", aa.iloc[1, 1  ] )   # order: row(s), column(s)

aa['i2'][1]     = 5
aa.loc [1,'i2'] = 5
aa.iloc[1,1]    = 5

In [18]:
aa = ddd()
mask = (aa.f1 >= 1.5) & (aa.f1 < 5)
print(mask)
aa[mask]
# aa[2:4]
# aa

0    False
1    False
2     True
3     True
4     True
5    False
6    False
7    False
8    False
9    False
Name: f1, dtype: bool

    ii  i1  i2   ff       f1    f2   ss   s1    s2     bb     b1  xx          yy
2  2.0   4   4  2.0  2.00200  3.33    狗   s2  3.33   True   True   2  159.812838
3  3.0   3   4  NaN  3.00030  4.44   汽车   s2  4.44  False  False   3  209.093033
4  4.0   2   1  4.0  4.00004  5.55  NaN  nan  5.55    NaN   True   4  259.504914

In [19]:
aa=ddd()
N = len(aa)
aa.index = range(N-1,-1,-1)
aa.loc[2,'ii']

7.0

In [52]:
aa = [5,6,7,8,9,10,11,12]
bb = aa[:]
cc = aa
cc = aa
for ii in range(len(cc)):
    cc[ii] = pow(cc[ii],2)
print("aa",id(aa))
print("cc",id(cc))
print("bb",id(bb))
print("aa",aa)
print("cc",cc)

aa 140685563914368
cc 140685563914368
bb 140685551913152
aa [25, 36, 49, 64, 81, 100, 121, 144]
cc [25, 36, 49, 64, 81, 100, 121, 144]

In [59]:
x = 10**8
e = (1+1/x)**x
print(e)
import math
print(math.exp(1))

2.7182817983473577
2.718281828459045

In [22]:
# Note:
#   loc  - by labels
#   iloc - by integer numbers of rows/columns - count starts with 0
#   ix   - deprecated, can do both

aa = ddd()
aa = aa.loc[:,['ii','i1','i2']] # [rows,cols]
aa.index = range(len(aa))  # 0,1,...,5,6
aa.index = aa.index.map(lambda x: 'm' + str(x))
display(aa)
#     id  i1  i2
# m0   0   6   6
# m1   1   5   5
# m2   2   4   4
# m3   3   3   4
# m4   4   2   1
# m5   5   1  1
# m6 NaN   0   0
print('-'*40)
print(aa.loc['m2','i2'])  # 4
# aa.iloc['m2','i2'] # ERROR
print(aa.iloc[2,2])       # 4

     ii  i1  i2
m0  0.0   6   6
m1  1.0   5   5
m2  2.0   4   4
m3  3.0   3   4
m4  4.0   2   1
m5  5.0   1   1
m6  NaN   0   0
m7  7.0  -1  -1
m8  8.0  -2  -2
m9  9.0  -3  -3

----------------------------------------
4
4

### -------------------- Question 4 --------------------

Extract a row from a DataFrame into a regular python list

#### Answer

In [61]:
aa=ddd()
print(aa.loc[1,:].values.tolist())
print(aa.loc[1,:].tolist())
print(type(aa.loc[1,:].tolist()))
print()
print(aa.iloc[len(aa)-1].tolist())

[1.0, 5, 5, 1.0, 1.01, 2.22, 's1', 's1', '2.22', False, False, 1, 108.1629151753549]
[1.0, 5, 5, 1.0, 1.01, 2.22, 's1', 's1', '2.22', False, False, 1, 108.1629151753549]
<class 'list'>

[9.0, -3, -3, 9.0, 9.0, -1.11, 's9', 's9', '-1.11', True, True, 9, 511.0444906726481]

In [24]:
aa=ddd()
type(aa.i1.values)

numpy.ndarray

### -------------------- Question 5 --------------------

- Show to find rows which has the same value in a particular column
- Show how to use value_counts()
- Show how to count number of times each unique value appears in group, and for multiple columns 
- What is np.unique - and how is it used?
- Write a procedure to extract duplicate rows (by one or more columns)

#### Answer

In [62]:
# duplicated() - create true/false mask
aa=ddd()
print(aa.i2)
aa.duplicated(['i2'])

0    6
1    5
2    4
3    4
4    1
5    1
6    0
7   -1
8   -2
9   -3
Name: i2, dtype: int64

0    False
1    False
2    False
3     True
4    False
5     True
6    False
7    False
8    False
9    False
dtype: bool

In [26]:
# value_counts()
# Returns pd.Series containing counts of unique values (excluding NaN)
# in descending order (the first element is the most frequently occuring).
aa['i2'].value_counts()

 4    2
 1    2
-2    1
 6    1
 5    1
-3    1
-1    1
 0    1
Name: i2, dtype: int64

In [80]:
aa=ddd()[["i1","i2"]].head()
display(aa)
display(aa.groupby(["i1","i2"],as_index=False).apply(lambda x: len(x)))

   i1  i2
0   6   6
1   5   5
2   4   4
3   3   4
4   2   1

i1  i2
2   1     1
3   4     1
4   4     1
5   5     1
6   6     1
dtype: int64

In [81]:
# Show how to count number of times each unique value appears in group, and for multiple columns

data = [
  ['amazon.com',  'correct',   'correct'  ], 
  ['amazon.com',  'incorrect', 'correct'  ], 
  ['walmart.com', 'incorrect', 'correct'  ], 
  ['walmart.com', 'incorrect', 'incorrect']
]

source = pd.DataFrame(data, columns=['domain', 'price', 'product'])

source.groupby('domain').apply(lambda x: x[['price','product']].apply(lambda y: y.value_counts())).fillna(0)

                       price  product
domain
amazon.com  correct      1.0      2.0
            incorrect    1.0      0.0
walmart.com correct      0.0      1.0
            incorrect    2.0      1.0

In [28]:
# np.unique is a Numpy function which shows unique values in a column,
# and where they were found first time.

aa=ddd()
np.unique(aa.i2)

array([-3, -2, -1,  0,  1,  4,  5,  6])

In [83]:
# a procedure to extract duplicate rows (by one or more columns)

def show_duplicates(df, cols=[], include_nulls=True):
    """
    # accepts a dataframe df and a column (or list of columns)
    # if list of columns is not provided - uses all df columns
    # returns a dataframe consisting of rows of df
    # which have duplicate values in "cols"
    # sorted by "cols" so that duplciates are next to each other
    # Note - doesn't change index values of rows
    """
    # ---------------------------------
    aa = df.copy()
    mycols = cols
    # ---------------------------------
    if len(mycols) <= 0:
        mycols = aa.columns.tolist()
    elif type(mycols) != list:
        mycols = list(mycols)
    # ---------------------------------
    if not include_nulls:
        mask = False
        for mycol in mycols:
            mask = mask | (aa[mycol] != aa[mycol])  # test for null values
        aa = aa[~mask]                              # remove rows with nulls in mycols
    if len(aa) <= 0:
        return aa[:0]
    # ---------------------------------
    # duplicated() method returns Boolean Series denoting duplicate rows
    mask = aa.duplicated(subset=mycols, keep='first').values \
         | aa.duplicated(subset=mycols, keep='last').values
    aa = aa[mask]
    if len(aa) <= 0:
        return aa[:0]
    # ---------------------------------
    # sorting to keep duplicates together
    # Attention - can not sort by nulls
    # bb contains mycols except for cols which are completely nulls
    bb = aa[mycols]
    bb = bb.dropna(how='all',axis=1)
    # sort aa by columns in bb (thus avoiding nulls)
    aa = aa.sort_values(by=bb.columns.tolist())
    # ---------------------------------
    # sorting skips nulls thus messing up the order. 
    # Let's put nulls at the end
    mask = False
    for mycol in mycols:
        mask = mask | (aa[mycol] != aa[mycol])  # test for null values
    aa1 = aa[~mask]
    aa2 = aa[mask]
    aa = aa1.append(aa2)

    return aa

In [84]:
aa = ddd()
show_duplicates(df=aa, cols=['i2'], include_nulls=True)

    ii  i1  i2   ff        f1    f2   ss   s1    s2     bb     b1  xx          yy
4  4.0   2   1  4.0  4.000040  5.55  NaN  nan  5.55    NaN   True   4  259.939539
5  5.0   1   1  5.0  5.000005  7.77   s5   s5  7.77  False  False   5  309.945677
2  2.0   4   4  2.0  2.002000  3.33    狗   s2  3.33   True   True   2  161.131597
3  3.0   3   4  NaN  3.000300  4.44   汽车   s2  4.44  False  False   3  210.617426

### -------------------- Question 6 --------------------

- Show how to append dataframes
- Show how to append a list (or series) of data to a dataframe

#### Answer

In [85]:
# append two dataframes one on top of the other
aa1 = ddd(5)
aa2 = ddd(5)
aa = aa1.append(aa2)
aa.index = range(len(aa))
display(aa)

     ii  i1  i2   ff        f1    f2   ss   s1    s2     bb     b1  xx          yy
0   0.0   6   6  0.0  0.000000  1.11   s0   s0  1.11   True   True   0   59.058597
1   1.0   5   5  1.0  1.010000  2.22   s1   s1  2.22  False  False   1  109.644614
2   2.0   4   4  2.0  2.002000  3.33    狗   s2  3.33   True   True   2  159.256151
3   3.0   3   4  NaN  3.000300  4.44   汽车   s2  4.44  False  False   3  211.016268
4   4.0   2   1  4.0  4.000040  5.55  NaN  nan  5.55    NaN   True   4  260.495031
5   5.0   1   1  5.0  5.000005  7.77   s5   s5  7.77  False  False   5  310.278820
6   0.0   6   6  0.0  0.000000  1.11   s0   s0  1.11   True   True   0   59.392032
7   1.0   5   5  1.0  1.010000  2.22   s1   s1  2.22  False  False   1  109.287640
8   2.0   4   4  2.0  2.002000  3.33    狗   s2  3.33   True   True   2  158.033873
9   3.0   3   4  NaN  3.000300  4.44   汽车   s2  4.44  False  False   3  208.935046
10  4.0   2   1  4.0  4.000040  5.55  NaN  nan  5.55    NaN   True   4  259.447705
11  5.0   1   1  5.0  5.000005  7.77   s5   s5  7.77  False  False   5  311.248410

In [86]:
# append a series or list by converting it to a DataFrame
aa = ddd()
bb = aa.loc[1].tolist()   # take 2nd row as a list
dd = pd.DataFrame([bb], columns=aa.columns)

# now append list
aa = aa.append(dd)
display(aa)

# Note: alternatively you can make 1-column dataframe - and transpose it
# bb=DataFrame(ss)
# bb.index = aa.columns
# aa.append(bb.T)

    ii  i1  i2   ff        f1    f2   ss   s1     s2     bb     b1  xx          yy
0  0.0   6   6  0.0  0.000000  1.11   s0   s0   1.11   True   True   0   59.495070
1  1.0   5   5  1.0  1.010000  2.22   s1   s1   2.22  False  False   1  110.333551
2  2.0   4   4  2.0  2.002000  3.33    狗   s2   3.33   True   True   2  159.231611
3  3.0   3   4  NaN  3.000300  4.44   汽车   s2   4.44  False  False   3  209.132728
4  4.0   2   1  4.0  4.000040  5.55  NaN  nan   5.55    NaN   True   4  260.622910
5  5.0   1   1  5.0  5.000005  7.77   s5   s5   7.77  False  False   5  308.472554
6  NaN   0   0  6.0  6.000001  9.99   s6   s6   9.99   True   True   6  360.959548
7  7.0  -1  -1  7.0  7.000000  0.01   s7   s7   0.01    NaN   True   7  409.865775
8  8.0  -2  -2  8.0  8.000000 -0.01   s8   s8  -0.01  False  False   8  460.177588
9  9.0  -3  -3  9.0  9.000000 -1.11   s9   s9  -1.11   True   True   9  508.595745
0  1.0   5   5  1.0  1.010000  2.22   s1   s1   2.22  False  False   1  110.333551

### -------------------- Question 7 --------------------

Show how to remove duplicate rows (duplicate is defined as having same value in a list of columns)

#### Answer

In [87]:
aa = aa.drop_duplicates(['i2']) 
# or
aa = aa.drop_duplicates(['i2'], keep='last') 
display(aa)

    ii  i1  i2   ff        f1    f2   ss   s1     s2     bb     b1  xx          yy
0  0.0   6   6  0.0  0.000000  1.11   s0   s0   1.11   True   True   0   59.495070
1  1.0   5   5  1.0  1.010000  2.22   s1   s1   2.22  False  False   1  110.333551
2  2.0   4   4  2.0  2.002000  3.33    狗   s2   3.33   True   True   2  159.231611
4  4.0   2   1  4.0  4.000040  5.55  NaN  nan   5.55    NaN   True   4  260.622910
6  NaN   0   0  6.0  6.000001  9.99   s6   s6   9.99   True   True   6  360.959548
7  7.0  -1  -1  7.0  7.000000  0.01   s7   s7   0.01    NaN   True   7  409.865775
8  8.0  -2  -2  8.0  8.000000 -0.01   s8   s8  -0.01  False  False   8  460.177588
9  9.0  -3  -3  9.0  9.000000 -1.11   s9   s9  -1.11   True   True   9  508.595745

### -------------------- Question 8 --------------------

Show how to use a mask using   &, |, ~, .isin(), .isnull()

#### Answer

In [34]:
aa=ddd()
mask = aa.f2.isnull()
display(aa[mask])
print('-'*40)
mask = aa.i1.isin([1,3,5])
display(aa[mask])
print('-'*40)
display(aa[~mask]) # shows the records where mask is False
print('-'*40)

# examples of masks based on more than one column
# mask = (aa.ii==1) & (aa.i2 == 4)
# mask = (aa.ii==1) | (aa.i2 == 4)

Empty DataFrame
Columns: [ii, i1, i2, ff, f1, f2, ss, s1, s2, bb, b1, xx, yy]
Index: []

----------------------------------------

    ii  i1  i2   ff        f1    f2  ss  s1    s2     bb     b1  xx          yy
1  1.0   5   5  1.0  1.010000  2.22  s1  s1  2.22  False  False   1  110.531422
3  3.0   3   4  NaN  3.000300  4.44  汽车  s2  4.44  False  False   3  211.176632
5  5.0   1   1  5.0  5.000005  7.77  s5  s5  7.77  False  False   5  310.347672

----------------------------------------

    ii  i1  i2   ff        f1    f2   ss   s1     s2     bb     b1  xx          yy
0  0.0   6   6  0.0  0.000000  1.11   s0   s0   1.11   True   True   0   60.277387
2  2.0   4   4  2.0  2.002000  3.33    狗   s2   3.33   True   True   2  159.441731
4  4.0   2   1  4.0  4.000040  5.55  NaN  nan   5.55    NaN   True   4  258.296581
6  NaN   0   0  6.0  6.000001  9.99   s6   s6   9.99   True   True   6  360.499548
7  7.0  -1  -1  7.0  7.000000  0.01   s7   s7   0.01    NaN   True   7  409.534483
8  8.0  -2  -2  8.0  8.000000 -0.01   s8   s8  -0.01  False  False   8  459.398654
9  9.0  -3  -3  9.0  9.000000 -1.11   s9   s9  -1.11   True   True   9  509.522663

----------------------------------------

### -------------------- Question 9 --------------------

Give an example of using a map() function on a pandas DataFrame column

#### Answer

In [35]:
aa=ddd()
str(aa.yy)

'0     60.667504\n1    110.801432\n2    159.624757\n3    209.172698\n4    260.551715\n5    310.555957\n6    358.782116\n7    409.846208\n8    460.033431\n9    511.137229\nName: yy, dtype: float64'

In [36]:
aa=ddd()
display(aa.yy.dtype)
aa['yy'] = aa.yy.map(lambda crocodile : str(round(crocodile,2)) + "abc")
display(aa)

dtype('float64')

    ii  i1  i2   ff        f1    f2   ss   s1     s2     bb     b1  xx         yy
0  0.0   6   6  0.0  0.000000  1.11   s0   s0   1.11   True   True   0   57.98abc
1  1.0   5   5  1.0  1.010000  2.22   s1   s1   2.22  False  False   1  113.48abc
2  2.0   4   4  2.0  2.002000  3.33    狗   s2   3.33   True   True   2   161.8abc
3  3.0   3   4  NaN  3.000300  4.44   汽车   s2   4.44  False  False   3  212.24abc
4  4.0   2   1  4.0  4.000040  5.55  NaN  nan   5.55    NaN   True   4  259.43abc
5  5.0   1   1  5.0  5.000005  7.77   s5   s5   7.77  False  False   5  310.57abc
6  NaN   0   0  6.0  6.000001  9.99   s6   s6   9.99   True   True   6  360.67abc
7  7.0  -1  -1  7.0  7.000000  0.01   s7   s7   0.01    NaN   True   7  410.84abc
8  8.0  -2  -2  8.0  8.000000 -0.01   s8   s8  -0.01  False  False   8  459.39abc
9  9.0  -3  -3  9.0  9.000000 -1.11   s9   s9  -1.11   True   True   9  509.88abc

### -------------------- Question 10 --------------------

Give example using map with lambda for dataframe operations

#### Answer

In [37]:
aa = ddd()
aa['s2'] = aa.ss + '__' + aa.i1.map(lambda x: str(x))

# make a list of values in column 'yy' 
# rounded to 2 digits after dot
aa['zz'] = aa['yy'].map(lambda x: round(x,2))
display(aa)

    ii  i1  i2   ff        f1    f2   ss   s1      s2     bb     b1  xx          yy      zz
0  0.0   6   6  0.0  0.000000  1.11   s0   s0   s0__6   True   True   0   61.342241   61.34
1  1.0   5   5  1.0  1.010000  2.22   s1   s1   s1__5  False  False   1  109.579153  109.58
2  2.0   4   4  2.0  2.002000  3.33    狗   s2    狗__4   True   True   2  159.226287  159.23
3  3.0   3   4  NaN  3.000300  4.44   汽车   s2   汽车__3  False  False   3  209.803300  209.80
4  4.0   2   1  4.0  4.000040  5.55  NaN  nan     NaN    NaN   True   4  259.784873  259.78
5  5.0   1   1  5.0  5.000005  7.77   s5   s5   s5__1  False  False   5  309.172021  309.17
6  NaN   0   0  6.0  6.000001  9.99   s6   s6   s6__0   True   True   6  360.994266  360.99
7  7.0  -1  -1  7.0  7.000000  0.01   s7   s7  s7__-1    NaN   True   7  409.994083  409.99
8  8.0  -2  -2  8.0  8.000000 -0.01   s8   s8  s8__-2  False  False   8  460.007190  460.01
9  9.0  -3  -3  9.0  9.000000 -1.11   s9   s9  s9__-3   True   True   9  509.384283  509.38

### -------------------- Question 11 --------------------

Give example using groupby().sum()

#### Answer

In [38]:
aa = ddd()
cc = aa.groupby(['i2'], as_index=False).sum()
display(cc)
print("-"*40)

# note - groupby().sum() will usually remove all 
# string columns from the result. To avoid it, you can use agg()
# But be carefull to avoid mixing NaN with strings - causes error 

aa = ddd()
aa['ss'] = aa.ss.fillna('_') # this removes NaN
cc = aa.groupby('i2', as_index=False).agg({'i1':np.sum,'ss':np.max})
display(cc)

   i2   ii  i1   ff        f1     f2     b1  xx          yy
0  -3  9.0  -3  9.0  9.000000  -1.11   True   9  508.816224
1  -2  8.0  -2  8.0  8.000000  -0.01  False   8  460.901107
2  -1  7.0  -1  7.0  7.000000   0.01   True   7  408.730745
3   0  0.0   0  6.0  6.000001   9.99   True   6  360.045782
4   1  9.0   3  9.0  9.000045  13.32   True   9  568.572107
5   4  5.0   7  2.0  5.002300   7.77   True   5  372.254615
6   5  1.0   5  1.0  1.010000   2.22  False   1  109.843367
7   6  0.0   6  0.0  0.000000   1.11   True   0   59.358943

----------------------------------------

   i2  i1  ss
0  -3  -3  s9
1  -2  -2  s8
2  -1  -1  s7
3   0   0  s6
4   1   3  s5
5   4   7   狗
6   5   5  s1
7   6   6  s0

### -------------------- Question 12 --------------------

Give example using groupby().aggregate()

#### Answer

In [88]:
aa = ddd()
bb = aa.groupby('i2', as_index=True).aggregate({'yy':np.sum, 'xx':np.max}) 
display(bb)

            yy  xx
i2
-3  510.134390   9
-2  461.759086   8
-1  408.289587   7
 0  360.324363   6
 1  572.269069   5
 4  372.014098   3
 5  109.144330   1
 6   60.755068   0

### -------------------- Question 13 --------------------

Show how to sort a dataframe by a list of columns

#### Answer

In [89]:
cc = aa.sort_values(by=['i2','yy'])
display(cc)

    ii  i1  i2   ff        f1    f2   ss   s1     s2     bb     b1  xx          yy
9  9.0  -3  -3  9.0  9.000000 -1.11   s9   s9  -1.11   True   True   9  510.134390
8  8.0  -2  -2  8.0  8.000000 -0.01   s8   s8  -0.01  False  False   8  461.759086
7  7.0  -1  -1  7.0  7.000000  0.01   s7   s7   0.01    NaN   True   7  408.289587
6  NaN   0   0  6.0  6.000001  9.99   s6   s6   9.99   True   True   6  360.324363
4  4.0   2   1  4.0  4.000040  5.55  NaN  nan   5.55    NaN   True   4  260.101521
5  5.0   1   1  5.0  5.000005  7.77   s5   s5   7.77  False  False   5  312.167549
2  2.0   4   4  2.0  2.002000  3.33    狗   s2   3.33   True   True   2  161.497766
3  3.0   3   4  NaN  3.000300  4.44   汽车   s2   4.44  False  False   3  210.516331
1  1.0   5   5  1.0  1.010000  2.22   s1   s1   2.22  False  False   1  109.144330
0  0.0   6   6  0.0  0.000000  1.11   s0   s0   1.11   True   True   0   60.755068

### -------------------- Question 14 --------------------

Show how to delete some rows from dataframe - and reindex

#### Answer

In [90]:
aa = ddd()
aa = aa.drop([1,3,5]) # remove several rows 
display(aa)

    ii  i1  i2   ff        f1    f2   ss   s1     s2     bb     b1  xx          yy
0  0.0   6   6  0.0  0.000000  1.11   s0   s0   1.11   True   True   0   59.839684
2  2.0   4   4  2.0  2.002000  3.33    狗   s2   3.33   True   True   2  160.378035
4  4.0   2   1  4.0  4.000040  5.55  NaN  nan   5.55    NaN   True   4  259.622326
6  NaN   0   0  6.0  6.000001  9.99   s6   s6   9.99   True   True   6  360.751824
7  7.0  -1  -1  7.0  7.000000  0.01   s7   s7   0.01    NaN   True   7  410.236826
8  8.0  -2  -2  8.0  8.000000 -0.01   s8   s8  -0.01  False  False   8  459.613512
9  9.0  -3  -3  9.0  9.000000 -1.11   s9   s9  -1.11   True   True   9  508.467734

In [91]:
# remove rows based on a mask
aa = ddd()
mask = aa['ii'].map(lambda x: x > 3) # True when aa.ii > 3
aa = aa[~mask]                       # take only where a.ii <= 3 or NaN
display(aa)
print('-'*40)
mask = aa['ii'].map(lambda x: x in (0,1,4))
aa = aa[~mask]
display(aa)

    ii  i1  i2   ff        f1    f2  ss  s1    s2     bb     b1  xx          yy
0  0.0   6   6  0.0  0.000000  1.11  s0  s0  1.11   True   True   0   58.657309
1  1.0   5   5  1.0  1.010000  2.22  s1  s1  2.22  False  False   1  109.855857
2  2.0   4   4  2.0  2.002000  3.33   狗  s2  3.33   True   True   2  161.652562
3  3.0   3   4  NaN  3.000300  4.44  汽车  s2  4.44  False  False   3  211.651054
6  NaN   0   0  6.0  6.000001  9.99  s6  s6  9.99   True   True   6  360.419546

----------------------------------------

    ii  i1  i2   ff        f1    f2  ss  s1    s2     bb     b1  xx          yy
2  2.0   4   4  2.0  2.002000  3.33   狗  s2  3.33   True   True   2  161.652562
3  3.0   3   4  NaN  3.000300  4.44  汽车  s2  4.44  False  False   3  211.651054
6  NaN   0   0  6.0  6.000001  9.99  s6  s6  9.99   True   True   6  360.419546

In [92]:
# after removing rows you may want to index rows sequentially
aa = ddd()
aa.reindex() # doesn't change index unless you provide it 
print('-0'*30)
aa.index = range(len(aa))
display(aa)
print('-1'*30)
# note - you can shift index
aa.index = range(100,100+len(aa))
display(aa)
print('-2'*30)
# you can even make all index values the same - although it is pointless
aa.index = [2]*len(aa)
display(aa)

-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0

    ii  i1  i2   ff        f1    f2   ss   s1     s2     bb     b1  xx          yy
0  0.0   6   6  0.0  0.000000  1.11   s0   s0   1.11   True   True   0   60.933690
1  1.0   5   5  1.0  1.010000  2.22   s1   s1   2.22  False  False   1  110.699826
2  2.0   4   4  2.0  2.002000  3.33    狗   s2   3.33   True   True   2  160.672308
3  3.0   3   4  NaN  3.000300  4.44   汽车   s2   4.44  False  False   3  210.757148
4  4.0   2   1  4.0  4.000040  5.55  NaN  nan   5.55    NaN   True   4  258.728275
5  5.0   1   1  5.0  5.000005  7.77   s5   s5   7.77  False  False   5  309.719144
6  NaN   0   0  6.0  6.000001  9.99   s6   s6   9.99   True   True   6  360.026873
7  7.0  -1  -1  7.0  7.000000  0.01   s7   s7   0.01    NaN   True   7  411.288520
8  8.0  -2  -2  8.0  8.000000 -0.01   s8   s8  -0.01  False  False   8  459.479981
9  9.0  -3  -3  9.0  9.000000 -1.11   s9   s9  -1.11   True   True   9  509.188398

-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1

      ii  i1  i2   ff        f1    f2   ss   s1     s2     bb     b1  xx          yy
100  0.0   6   6  0.0  0.000000  1.11   s0   s0   1.11   True   True   0   60.933690
101  1.0   5   5  1.0  1.010000  2.22   s1   s1   2.22  False  False   1  110.699826
102  2.0   4   4  2.0  2.002000  3.33    狗   s2   3.33   True   True   2  160.672308
103  3.0   3   4  NaN  3.000300  4.44   汽车   s2   4.44  False  False   3  210.757148
104  4.0   2   1  4.0  4.000040  5.55  NaN  nan   5.55    NaN   True   4  258.728275
105  5.0   1   1  5.0  5.000005  7.77   s5   s5   7.77  False  False   5  309.719144
106  NaN   0   0  6.0  6.000001  9.99   s6   s6   9.99   True   True   6  360.026873
107  7.0  -1  -1  7.0  7.000000  0.01   s7   s7   0.01    NaN   True   7  411.288520
108  8.0  -2  -2  8.0  8.000000 -0.01   s8   s8  -0.01  False  False   8  459.479981
109  9.0  -3  -3  9.0  9.000000 -1.11   s9   s9  -1.11   True   True   9  509.188398

-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2

    ii  i1  i2   ff        f1    f2   ss   s1     s2     bb     b1  xx          yy
2  0.0   6   6  0.0  0.000000  1.11   s0   s0   1.11   True   True   0   60.933690
2  1.0   5   5  1.0  1.010000  2.22   s1   s1   2.22  False  False   1  110.699826
2  2.0   4   4  2.0  2.002000  3.33    狗   s2   3.33   True   True   2  160.672308
2  3.0   3   4  NaN  3.000300  4.44   汽车   s2   4.44  False  False   3  210.757148
2  4.0   2   1  4.0  4.000040  5.55  NaN  nan   5.55    NaN   True   4  258.728275
2  5.0   1   1  5.0  5.000005  7.77   s5   s5   7.77  False  False   5  309.719144
2  NaN   0   0  6.0  6.000001  9.99   s6   s6   9.99   True   True   6  360.026873
2  7.0  -1  -1  7.0  7.000000  0.01   s7   s7   0.01    NaN   True   7  411.288520
2  8.0  -2  -2  8.0  8.000000 -0.01   s8   s8  -0.01  False  False   8  459.479981
2  9.0  -3  -3  9.0  9.000000 -1.11   s9   s9  -1.11   True   True   9  509.188398

### -------------------- Question 15 --------------------

Show how to add rows to a dataframe 
<br>(add 2 dataframes together vertically - and reindex)

#### Answer

In [93]:
aa=ddd()
aa = aa.append(aa[2:4],ignore_index=True)
display(aa)

     ii  i1  i2   ff        f1    f2   ss   s1     s2     bb     b1  xx          yy
0   0.0   6   6  0.0  0.000000  1.11   s0   s0   1.11   True   True   0   60.329423
1   1.0   5   5  1.0  1.010000  2.22   s1   s1   2.22  False  False   1  111.109625
2   2.0   4   4  2.0  2.002000  3.33    狗   s2   3.33   True   True   2  158.160540
3   3.0   3   4  NaN  3.000300  4.44   汽车   s2   4.44  False  False   3  209.350694
4   4.0   2   1  4.0  4.000040  5.55  NaN  nan   5.55    NaN   True   4  261.399041
5   5.0   1   1  5.0  5.000005  7.77   s5   s5   7.77  False  False   5  309.632322
6   NaN   0   0  6.0  6.000001  9.99   s6   s6   9.99   True   True   6  361.936435
7   7.0  -1  -1  7.0  7.000000  0.01   s7   s7   0.01    NaN   True   7  411.774562
8   8.0  -2  -2  8.0  8.000000 -0.01   s8   s8  -0.01  False  False   8  458.355069
9   9.0  -3  -3  9.0  9.000000 -1.11   s9   s9  -1.11   True   True   9  512.663225
10  2.0   4   4  2.0  2.002000  3.33    狗   s2   3.33   True   True   2  158.160540
11  3.0   3   4  NaN  3.000300  4.44   汽车   s2   4.44  False  False   3  209.350694

### -------------------- Question 16 --------------------

- Show how to write dataframe to csv file
- Show how to read it back

#### Answer

In [94]:
aa = ddd()
aa.to_csv('junk.csv', sep='|', header=True, index=False)
bb = pd.read_csv('junk.csv', sep='|')
display(bb)

    ii  i1  i2   ff        f1    f2   ss   s1    s2     bb     b1  xx          yy
0  0.0   6   6  0.0  0.000000  1.11   s0   s0  1.11   True   True   0   59.708246
1  1.0   5   5  1.0  1.010000  2.22   s1   s1  2.22  False  False   1  109.081452
2  2.0   4   4  2.0  2.002000  3.33    狗   s2  3.33   True   True   2  158.355197
3  3.0   3   4  NaN  3.000300  4.44   汽车   s2  4.44  False  False   3  210.031526
4  4.0   2   1  4.0  4.000040  5.55  NaN  NaN  5.55    NaN   True   4  258.760208
5  5.0   1   1  5.0  5.000005  7.77   s5   s5  7.77  False  False   5  310.211160
6  NaN   0   0  6.0  6.000001  9.99   s6   s6  9.99   True   True   6  360.386184
7  7.0  -1  -1  7.0  7.000000  0.01   s7   s7  0.01    NaN   True   7  409.381673
8  8.0  -2  -2  8.0  8.000000 -0.01   s8   s8 -0.01  False  False   8  460.525343
9  9.0  -3  -3  9.0  9.000000 -1.11   s9   s9 -1.11   True   True   9  508.004750

### -------------------- Question 17 --------------------

- Show how to add columns to pandas DataFrame
- Show how to calculate column values from numeric/string values in other columns.
- Show how to delete one or more columns

#### Answer

In [46]:
aa = ddd()
aa['c4'] = None         # populate with same value
display(aa)
print('-0'*30)
col2=[1,2,3,4,5,6,7,8,9,0]
aa['c4'] = col2         # list becomes a column
display(aa)
print('-1'*30)
aa['c4'] = "-"
display(aa)
print('-2'*30)

# adding a column - and populating it using vectorized operation on columns
aa['c5']= 2*aa['i1'] + 3*aa['i2'] + 5
display(aa)
print('-3'*30)

# calculating column values from other columns:
aa['c4']= 2*aa['i1'] + 3*aa['i2'] + 5
aa['s2'] = aa.ss + '__' + aa.i1.map(lambda x: str(x))
display(aa)
print('-4'*30)

# Deleting one column
del aa['s1']
display(aa)
print('-5'*30)

# Deleting many columns
aa = aa.drop(['i1','i2','c4'], axis=1)
display(aa)

    ii  i1  i2   ff        f1    f2   ss   s1     s2     bb     b1  xx          yy    c4
0  0.0   6   6  0.0  0.000000  1.11   s0   s0   1.11   True   True   0   59.567414  None
1  1.0   5   5  1.0  1.010000  2.22   s1   s1   2.22  False  False   1  109.462456  None
2  2.0   4   4  2.0  2.002000  3.33    狗   s2   3.33   True   True   2  160.049983  None
3  3.0   3   4  NaN  3.000300  4.44   汽车   s2   4.44  False  False   3  209.791180  None
4  4.0   2   1  4.0  4.000040  5.55  NaN  nan   5.55    NaN   True   4  258.427552  None
5  5.0   1   1  5.0  5.000005  7.77   s5   s5   7.77  False  False   5  310.529344  None
6  NaN   0   0  6.0  6.000001  9.99   s6   s6   9.99   True   True   6  358.666357  None
7  7.0  -1  -1  7.0  7.000000  0.01   s7   s7   0.01    NaN   True   7  412.969295  None
8  8.0  -2  -2  8.0  8.000000 -0.01   s8   s8  -0.01  False  False   8  460.291307  None
9  9.0  -3  -3  9.0  9.000000 -1.11   s9   s9  -1.11   True   True   9  510.900566  None

-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0

    ii  i1  i2   ff        f1    f2   ss   s1     s2     bb     b1  xx          yy  c4
0  0.0   6   6  0.0  0.000000  1.11   s0   s0   1.11   True   True   0   59.567414   1
1  1.0   5   5  1.0  1.010000  2.22   s1   s1   2.22  False  False   1  109.462456   2
2  2.0   4   4  2.0  2.002000  3.33    狗   s2   3.33   True   True   2  160.049983   3
3  3.0   3   4  NaN  3.000300  4.44   汽车   s2   4.44  False  False   3  209.791180   4
4  4.0   2   1  4.0  4.000040  5.55  NaN  nan   5.55    NaN   True   4  258.427552   5
5  5.0   1   1  5.0  5.000005  7.77   s5   s5   7.77  False  False   5  310.529344   6
6  NaN   0   0  6.0  6.000001  9.99   s6   s6   9.99   True   True   6  358.666357   7
7  7.0  -1  -1  7.0  7.000000  0.01   s7   s7   0.01    NaN   True   7  412.969295   8
8  8.0  -2  -2  8.0  8.000000 -0.01   s8   s8  -0.01  False  False   8  460.291307   9
9  9.0  -3  -3  9.0  9.000000 -1.11   s9   s9  -1.11   True   True   9  510.900566   0

-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1

    ii  i1  i2   ff        f1    f2   ss   s1     s2     bb     b1  xx          yy c4
0  0.0   6   6  0.0  0.000000  1.11   s0   s0   1.11   True   True   0   59.567414  -
1  1.0   5   5  1.0  1.010000  2.22   s1   s1   2.22  False  False   1  109.462456  -
2  2.0   4   4  2.0  2.002000  3.33    狗   s2   3.33   True   True   2  160.049983  -
3  3.0   3   4  NaN  3.000300  4.44   汽车   s2   4.44  False  False   3  209.791180  -
4  4.0   2   1  4.0  4.000040  5.55  NaN  nan   5.55    NaN   True   4  258.427552  -
5  5.0   1   1  5.0  5.000005  7.77   s5   s5   7.77  False  False   5  310.529344  -
6  NaN   0   0  6.0  6.000001  9.99   s6   s6   9.99   True   True   6  358.666357  -
7  7.0  -1  -1  7.0  7.000000  0.01   s7   s7   0.01    NaN   True   7  412.969295  -
8  8.0  -2  -2  8.0  8.000000 -0.01   s8   s8  -0.01  False  False   8  460.291307  -
9  9.0  -3  -3  9.0  9.000000 -1.11   s9   s9  -1.11   True   True   9  510.900566  -

-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2

    ii  i1  i2   ff        f1    f2   ss   s1     s2     bb     b1  xx          yy c4  c5
0  0.0   6   6  0.0  0.000000  1.11   s0   s0   1.11   True   True   0   59.567414  -  35
1  1.0   5   5  1.0  1.010000  2.22   s1   s1   2.22  False  False   1  109.462456  -  30
2  2.0   4   4  2.0  2.002000  3.33    狗   s2   3.33   True   True   2  160.049983  -  25
3  3.0   3   4  NaN  3.000300  4.44   汽车   s2   4.44  False  False   3  209.791180  -  23
4  4.0   2   1  4.0  4.000040  5.55  NaN  nan   5.55    NaN   True   4  258.427552  -  12
5  5.0   1   1  5.0  5.000005  7.77   s5   s5   7.77  False  False   5  310.529344  -  10
6  NaN   0   0  6.0  6.000001  9.99   s6   s6   9.99   True   True   6  358.666357  -   5
7  7.0  -1  -1  7.0  7.000000  0.01   s7   s7   0.01    NaN   True   7  412.969295  -   0
8  8.0  -2  -2  8.0  8.000000 -0.01   s8   s8  -0.01  False  False   8  460.291307  -  -5
9  9.0  -3  -3  9.0  9.000000 -1.11   s9   s9  -1.11   True   True   9  510.900566  - -10

-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3

    ii  i1  i2   ff        f1    f2   ss   s1      s2     bb     b1  xx          yy  c4  c5
0  0.0   6   6  0.0  0.000000  1.11   s0   s0   s0__6   True   True   0   59.567414  35  35
1  1.0   5   5  1.0  1.010000  2.22   s1   s1   s1__5  False  False   1  109.462456  30  30
2  2.0   4   4  2.0  2.002000  3.33    狗   s2    狗__4   True   True   2  160.049983  25  25
3  3.0   3   4  NaN  3.000300  4.44   汽车   s2   汽车__3  False  False   3  209.791180  23  23
4  4.0   2   1  4.0  4.000040  5.55  NaN  nan     NaN    NaN   True   4  258.427552  12  12
5  5.0   1   1  5.0  5.000005  7.77   s5   s5   s5__1  False  False   5  310.529344  10  10
6  NaN   0   0  6.0  6.000001  9.99   s6   s6   s6__0   True   True   6  358.666357   5   5
7  7.0  -1  -1  7.0  7.000000  0.01   s7   s7  s7__-1    NaN   True   7  412.969295   0   0
8  8.0  -2  -2  8.0  8.000000 -0.01   s8   s8  s8__-2  False  False   8  460.291307  -5  -5
9  9.0  -3  -3  9.0  9.000000 -1.11   s9   s9  s9__-3   True   True   9  510.900566 -10 -10

-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4

    ii  i1  i2   ff        f1    f2   ss      s2     bb     b1  xx          yy  c4  c5
0  0.0   6   6  0.0  0.000000  1.11   s0   s0__6   True   True   0   59.567414  35  35
1  1.0   5   5  1.0  1.010000  2.22   s1   s1__5  False  False   1  109.462456  30  30
2  2.0   4   4  2.0  2.002000  3.33    狗    狗__4   True   True   2  160.049983  25  25
3  3.0   3   4  NaN  3.000300  4.44   汽车   汽车__3  False  False   3  209.791180  23  23
4  4.0   2   1  4.0  4.000040  5.55  NaN     NaN    NaN   True   4  258.427552  12  12
5  5.0   1   1  5.0  5.000005  7.77   s5   s5__1  False  False   5  310.529344  10  10
6  NaN   0   0  6.0  6.000001  9.99   s6   s6__0   True   True   6  358.666357   5   5
7  7.0  -1  -1  7.0  7.000000  0.01   s7  s7__-1    NaN   True   7  412.969295   0   0
8  8.0  -2  -2  8.0  8.000000 -0.01   s8  s8__-2  False  False   8  460.291307  -5  -5
9  9.0  -3  -3  9.0  9.000000 -1.11   s9  s9__-3   True   True   9  510.900566 -10 -10

-5-5-5-5-5-5-5-5-5-5-5-5-5-5-5-5-5-5-5-5-5-5-5-5-5-5-5-5-5-5

    ii   ff        f1    f2   ss      s2     bb     b1  xx          yy  c5
0  0.0  0.0  0.000000  1.11   s0   s0__6   True   True   0   59.567414  35
1  1.0  1.0  1.010000  2.22   s1   s1__5  False  False   1  109.462456  30
2  2.0  2.0  2.002000  3.33    狗    狗__4   True   True   2  160.049983  25
3  3.0  NaN  3.000300  4.44   汽车   汽车__3  False  False   3  209.791180  23
4  4.0  4.0  4.000040  5.55  NaN     NaN    NaN   True   4  258.427552  12
5  5.0  5.0  5.000005  7.77   s5   s5__1  False  False   5  310.529344  10
6  NaN  6.0  6.000001  9.99   s6   s6__0   True   True   6  358.666357   5
7  7.0  7.0  7.000000  0.01   s7  s7__-1    NaN   True   7  412.969295   0
8  8.0  8.0  8.000000 -0.01   s8  s8__-2  False  False   8  460.291307  -5
9  9.0  9.0  9.000000 -1.11   s9  s9__-3   True   True   9  510.900566 -10

### -------------------- Question 18 --------------------

Show how to calculate a pandas DataFrame column 
as a linear combination of some other columns

#### Answer

In [47]:
aa = ddd()
aa['c4']= 2*aa['i1'] + 3*aa['i2'] + 5 
display(aa)

    ii  i1  i2   ff        f1    f2   ss   s1     s2     bb     b1  xx          yy  c4
0  0.0   6   6  0.0  0.000000  1.11   s0   s0   1.11   True   True   0   60.577171  35
1  1.0   5   5  1.0  1.010000  2.22   s1   s1   2.22  False  False   1  111.630904  30
2  2.0   4   4  2.0  2.002000  3.33    狗   s2   3.33   True   True   2  160.385649  25
3  3.0   3   4  NaN  3.000300  4.44   汽车   s2   4.44  False  False   3  207.982657  23
4  4.0   2   1  4.0  4.000040  5.55  NaN  nan   5.55    NaN   True   4  260.449945  12
5  5.0   1   1  5.0  5.000005  7.77   s5   s5   7.77  False  False   5  310.969801  10
6  NaN   0   0  6.0  6.000001  9.99   s6   s6   9.99   True   True   6  360.532198   5
7  7.0  -1  -1  7.0  7.000000  0.01   s7   s7   0.01    NaN   True   7  408.712261   0
8  8.0  -2  -2  8.0  8.000000 -0.01   s8   s8  -0.01  False  False   8  458.474520  -5
9  9.0  -3  -3  9.0  9.000000 -1.11   s9   s9  -1.11   True   True   9  509.514207 -10

### -------------------- Question 19 --------------------

Show how to calculate a DataFrame column 
from several other columns while using str() and int().<br>
Hint - use map(lambda ..)

#### Answer

In [48]:
aa = ddd()
aa['s3'] = aa['yy'].map(lambda x: int(x)) 
aa['s4']= '>>>' + aa.s3.map(lambda x: str(x)) + '<<<'
display(aa)

    ii  i1  i2   ff        f1    f2   ss   s1     s2     bb     b1  xx          yy   s3         s4
0  0.0   6   6  0.0  0.000000  1.11   s0   s0   1.11   True   True   0   59.612088   59   >>>59<<<
1  1.0   5   5  1.0  1.010000  2.22   s1   s1   2.22  False  False   1  111.402120  111  >>>111<<<
2  2.0   4   4  2.0  2.002000  3.33    狗   s2   3.33   True   True   2  160.193581  160  >>>160<<<
3  3.0   3   4  NaN  3.000300  4.44   汽车   s2   4.44  False  False   3  210.944273  210  >>>210<<<
4  4.0   2   1  4.0  4.000040  5.55  NaN  nan   5.55    NaN   True   4  259.653609  259  >>>259<<<
5  5.0   1   1  5.0  5.000005  7.77   s5   s5   7.77  False  False   5  310.406136  310  >>>310<<<
6  NaN   0   0  6.0  6.000001  9.99   s6   s6   9.99   True   True   6  358.082566  358  >>>358<<<
7  7.0  -1  -1  7.0  7.000000  0.01   s7   s7   0.01    NaN   True   7  409.791309  409  >>>409<<<
8  8.0  -2  -2  8.0  8.000000 -0.01   s8   s8  -0.01  False  False   8  461.325895  461  >>>461<<<
9  9.0  -3  -3  9.0  9.000000 -1.11   s9   s9  -1.11   True   True   9  507.384341  507  >>>507<<<

### -------------------- Question 20 --------------------

Show how to define a mask using regex on one column, and numeric comparison on the other column

#### Answer

In [49]:
import re
aa = ddd()
mask = (aa.i2.map(lambda x: True if re.search(r'4',str(x)) else False)) & (aa.xx > 2)
display(mask)
display(aa[mask])

# more examples
# mask = ( df.a == 1) & (df.b == 2)
# mask = ( df.a == 1) | (df.b == 2)
# mask = ( df.a == 1) | df.b.isin([1,2,3])
# mask = ( df.a == 1) | df.b.map(lambda x: ......)
# mask = ( df.a == 1) | df.b.map(lambda x: ......)  |  df.c.map(lambda x: ......)

0    False
1    False
2    False
3     True
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

    ii  i1  i2  ff      f1    f2  ss  s1    s2     bb     b1  xx          yy
3  3.0   3   4 NaN  3.0003  4.44  汽车  s2  4.44  False  False   3  210.877042

### -------------------- Question 21 --------------------

String operations on columns
<br>How to define a mask using a regular expression

In [50]:
aa = ddd()
mask = aa.ss.map(lambda x: True if re.search(r's[1,3]',str(x)) else False)
display(aa[mask])

    ii  i1  i2   ff    f1    f2  ss  s1    s2     bb     b1  xx          yy
1  1.0   5   5  1.0  1.01  2.22  s1  s1  2.22  False  False   1  111.221273