# Python Test 100
## Group Pandas 1 Questions 1..21

In [1]:
import os,sys
import pandas as pd
import numpy as np
from IPython.display import display, Image

In [2]:
aa = np.array([range(10),range(10)])
print(aa)
print(aa.shape)

[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]
(2, 10)

In [3]:
print(pd.__file__)
print(pd.__version__)
print(np.__file__)
print(np.__version__)

/Users/levselector/anaconda3/lib/python3.8/site-packages/pandas/__init__.py
1.1.3
/Users/levselector/anaconda3/lib/python3.8/site-packages/numpy/__init__.py
1.19.2

### -------------------- Question 1 --------------------

Explain how to install/upgrade pandas module

#### Answer

``` python
pandas stands for "Panel Data"
http://pandas.pydata.org/
It is a python module which is great for  analytical calculations.
Original author - Wes McKinney
Installation - it comes with Anaconda Python.
It is recommended to add these two channels:
  conda config --add channels anaconda
  conda config --add channels conda-forge
Updates happen when you update anaconda:
  conda update conda
  conda update anaconda

To play with pandas I recommend to use the following 
simple function ddd()
```

In [4]:
mydict = {} # empty dict
mydict["c1"] = [1,2,3]
mydict['c2'] = [4,5,6]
print(mydict)
print('-'*40)
aa = pd.DataFrame(  mydict , 
                    index = ['mama','papa','me'],
                    columns = ['c2','c1'])
display(aa)
print('-'*40)
print(aa.columns)

{'c1': [1, 2, 3], 'c2': [4, 5, 6]}
----------------------------------------

      c2  c1
mama   4   1
papa   5   2
me     6   3

----------------------------------------
Index(['c2', 'c1'], dtype='object')

In [5]:
aa.index[1]

'papa'

In [6]:
def ddd(nrows=10):
    """
    # returns a simple pandas DataFrame - useful for quick tests
    # nrows is number of rows (divisible by 10), for example:
    #     df = ddd()
    #     df = ddd(100)
    #     df = ddd(10**6)   # million rows
    """
    n_aa = 10
    nn = int(nrows/n_aa)
    if nn < 1:
        nn = 1
    aa = pd.DataFrame({
          'ii':nn*[0,1,2,3,4,5,np.nan,7,8,9],
          'i1':nn*[6,5,4,3,2,1,0,-1,-2,-3],
          'i2':nn*[6,5,4,4,1,1,0,-1,-2,-3],
          'ff':nn*[0.0,1.0,2.0,np.NaN,4.0,5.0,6.0,7.0,8.0,9.0],
          'f1':nn*[0.0,1.01,2.002,3.0003,4.00004,5.000005,6.0000006,7.0,8.0,9.0],
          'f2':nn*[1.11,2.22,3.33,4.44,5.55,7.77,9.99,0.01,-0.01,-1.11],
          'ss':nn*['s0','s1','狗','汽车',np.nan,'s5','s6','s7','s8','s9'],
          's1':nn*list(np.array(['s0','s1','s2','s2',np.nan,'s5','s6','s7','s8','s9'],dtype=np.str)),
          's2':nn*['1.11','2.22','3.33','4.44','5.55','7.77','9.99','0.01','-0.01','-1.11'],
          'bb':nn*[True, False, True, False, np.nan, False, True,np.nan, False, True],
          'b1':nn*[True, False, True, False, True, False, True, True, False, True],
          'xx':nn*list(range(n_aa)),
          'yy':nn*[x*50 + 60 + np.random.randn() for x in range(n_aa)]
    })
    aa = aa[['ii','i1','i2','ff','f1','f2','ss','s1','s2','bb','b1','xx','yy']].copy()
    aa.index = range(len(aa))

    if 1 <= nrows < 10:
        aa = aa[:nrows+1]
        
    return aa

In [7]:
aa = ddd()
display(aa.head(5).tail(2))
print("-"*40)
display(aa.tail(6).T.copy())

    ii  i1  i2   ff       f1    f2   ss   s1    s2     bb     b1  xx          yy
3  3.0   3   4  NaN  3.00030  4.44   汽车   s2  4.44  False  False   3  209.938947
4  4.0   2   1  4.0  4.00004  5.55  NaN  nan  5.55    NaN   True   4  259.898000

----------------------------------------

          4        5        6        7        8        9
ii        4        5      NaN        7        8        9
i1        2        1        0       -1       -2       -3
i2        1        1        0       -1       -2       -3
ff        4        5        6        7        8        9
f1  4.00004        5        6        7        8        9
f2     5.55     7.77     9.99     0.01    -0.01    -1.11
ss      NaN       s5       s6       s7       s8       s9
s1      nan       s5       s6       s7       s8       s9
s2     5.55     7.77     9.99     0.01    -0.01    -1.11
bb      NaN    False     True      NaN    False     True
b1     True    False     True     True    False     True
xx        4        5        6        7        8        9
yy  259.898  311.153  359.672  411.351  460.156  509.752

### -------------------- Question 2 --------------------

- Show how to test the type of the variable (is it an int? float? str?, list? dict? etc.) 
- Show how to test type of a column in a DataFrame 
- Show how to list types of all columns in a DataFrame

#### Answer

In [8]:
type({1:2,3:4})
aa = ddd()
aa['i1'].dtype

dtype('int64')

In [9]:
print("type of a python variable")

def print_type(obj):
    if type(obj) == int:
        print("  int")
    elif type(obj) == float:
        print("  float")
    elif type(obj) == str:
        print("  str")
    else:
        print("  unknown type")

print_type(1)
print_type(1.1)
print_type('mama')
print_type([1,2,3])

print("type of pd.DataFrame column")
aa = ddd()
print("aa.f1.dtype    = ",aa.f1.dtype)
print("aa['f1'].dtype = ",aa['f1'].dtype)

print('-'*40)
print("types of all pd.DataFrame columns")
print(aa.dtypes)

type of a python variable
  int
  float
  str
  unknown type
type of pd.DataFrame column
aa.f1.dtype    =  float64
aa['f1'].dtype =  float64
----------------------------------------
types of all pd.DataFrame columns
ii    float64
i1      int64
i2      int64
ff    float64
f1    float64
f2    float64
ss     object
s1     object
s2     object
bb     object
b1       bool
xx      int64
yy    float64
dtype: object

### -------------------- Question 3 --------------------

Show how to take a value from a particular cell of a dataframe
 - using df[col][row]                  # label based
 - using df.loc [row_label, col_label] # label based
 - using df.iloc[row_index, col_index] # indexes start with 0

#### Answer

In [10]:
aa = ddd()
aa.index = range(len(aa))
# aa.index = range(len(aa)-1,  -1,  -1)
print("aa['i2'][1]     =", aa['i2'][1]   )     # order: column(s), row(s)
print("aa.loc [1,'i2'] =", aa.loc [1,'i2'] )   # order: row(s), column(s)
print("aa.iloc[1,1]    =", aa.iloc[1, 1  ] )   # order: row(s), column(s)

aa['i2'][1]     = 5
aa.loc [1,'i2'] = 5
aa.iloc[1,1]    = 5

In [11]:
aa = ddd()
mask = (aa.f1 >= 1.5) & (aa.f1 < 5)
print(mask)
aa[mask]
# aa[2:4]
# aa

0    False
1    False
2     True
3     True
4     True
5    False
6    False
7    False
8    False
9    False
Name: f1, dtype: bool

    ii  i1  i2   ff       f1    f2   ss   s1    s2     bb     b1  xx          yy
2  2.0   4   4  2.0  2.00200  3.33    狗   s2  3.33   True   True   2  160.102921
3  3.0   3   4  NaN  3.00030  4.44   汽车   s2  4.44  False  False   3  212.197454
4  4.0   2   1  4.0  4.00004  5.55  NaN  nan  5.55    NaN   True   4  259.963864

In [12]:
aa=ddd()
N = len(aa)
aa.index = range(N-1,-1,-1)
aa.loc[2,'ii']

7.0

In [13]:
aa = [5,6,7,8,9,10,11,12]
bb = aa[:]
cc = aa
cc = aa
for ii in range(len(cc)):
    cc[ii] = pow(cc[ii],2)
print("aa",id(aa))
print("cc",id(cc))
print("bb",id(bb))
print("aa",aa)
print("cc",cc)

aa 140578259400576
cc 140578259400576
bb 140578259400512
aa [25, 36, 49, 64, 81, 100, 121, 144]
cc [25, 36, 49, 64, 81, 100, 121, 144]

In [14]:
x = 10**8
e = (1+1/x)**x
print(e)
import math
print(math.exp(1))

2.7182817983473577
2.718281828459045

In [15]:
# Note:
#   loc  - by labels
#   iloc - by integer numbers of rows/columns - count starts with 0
#   ix   - deprecated, can do both

aa = ddd()
aa = aa.loc[:,['ii','i1','i2']] # [rows,cols]
aa.index = range(len(aa))  # 0,1,...,5,6
aa.index = aa.index.map(lambda x: 'm' + str(x))
display(aa)
#     id  i1  i2
# m0   0   6   6
# m1   1   5   5
# m2   2   4   4
# m3   3   3   4
# m4   4   2   1
# m5   5   1  1
# m6 NaN   0   0
print('-'*40)
print(aa.loc['m2','i2'])  # 4
# aa.iloc['m2','i2'] # ERROR
print(aa.iloc[2,2])       # 4

     ii  i1  i2
m0  0.0   6   6
m1  1.0   5   5
m2  2.0   4   4
m3  3.0   3   4
m4  4.0   2   1
m5  5.0   1   1
m6  NaN   0   0
m7  7.0  -1  -1
m8  8.0  -2  -2
m9  9.0  -3  -3

----------------------------------------
4
4

### -------------------- Question 4 --------------------

Extract a row from a DataFrame into a regular python list

#### Answer

In [16]:
aa=ddd()
print(aa.loc[1,:].values.tolist())
print(aa.loc[1,:].tolist())
print(type(aa.loc[1,:].tolist()))
print()
print(aa.iloc[len(aa)-1].tolist())

[1.0, 5, 5, 1.0, 1.01, 2.22, 's1', 's1', '2.22', False, False, 1, 111.49137281499715]
[1.0, 5, 5, 1.0, 1.01, 2.22, 's1', 's1', '2.22', False, False, 1, 111.49137281499715]
<class 'list'>

[9.0, -3, -3, 9.0, 9.0, -1.11, 's9', 's9', '-1.11', True, True, 9, 510.73969421367696]

In [17]:
aa=ddd()
type(aa.i1.values)

numpy.ndarray

### -------------------- Question 5 --------------------

- Show to find rows which has the same value in a particular column
- Show how to use value_counts()
- Show how to count number of times each unique value appears in group, and for multiple columns 
- What is np.unique - and how is it used?
- Write a procedure to extract duplicate rows (by one or more columns)

#### Answer

In [18]:
# duplicated() - create true/false mask
aa=ddd()
print(aa.i2)
aa.duplicated(['i2'])

0    6
1    5
2    4
3    4
4    1
5    1
6    0
7   -1
8   -2
9   -3
Name: i2, dtype: int64

0    False
1    False
2    False
3     True
4    False
5     True
6    False
7    False
8    False
9    False
dtype: bool

In [19]:
# value_counts()
# Returns pd.Series containing counts of unique values (excluding NaN)
# in descending order (the first element is the most frequently occuring).
aa['i2'].value_counts()

 4    2
 1    2
-2    1
 6    1
 5    1
-3    1
-1    1
 0    1
Name: i2, dtype: int64

In [20]:
aa=ddd()[["i2"]]  # DataFrame with one column
display(aa)

# when we use apply(some_function)
# it receives DataFrame as parameter

display(aa.groupby(["i2"],as_index=False).apply(lambda x: type(x)))

# to return the length of each group, we can simply
# return the length of DataFrames representing each group

display(aa.groupby(["i2"],as_index=False).apply(lambda x: len(x)))

   i2
0   6
1   5
2   4
3   4
4   1
5   1
6   0
7  -1
8  -2
9  -3

   i2                                    NaN
0  -3  <class 'pandas.core.frame.DataFrame'>
1  -2  <class 'pandas.core.frame.DataFrame'>
2  -1  <class 'pandas.core.frame.DataFrame'>
3   0  <class 'pandas.core.frame.DataFrame'>
4   1  <class 'pandas.core.frame.DataFrame'>
5   4  <class 'pandas.core.frame.DataFrame'>
6   5  <class 'pandas.core.frame.DataFrame'>
7   6  <class 'pandas.core.frame.DataFrame'>

   i2  NaN
0  -3    1
1  -2    1
2  -1    1
3   0    1
4   1    2
5   4    2
6   5    1
7   6    1

In [21]:
# Similarly - but now group by two columns:

aa=ddd()[["i1","i2"]].head()
display(aa)
display(aa.groupby(["i1","i2"],as_index=False).apply(lambda x: len(x)))

   i1  i2
0   6   6
1   5   5
2   4   4
3   3   4
4   2   1

       i1  i2  NaN
i1 i2
2  1    2   1    1
3  4    3   4    1
4  4    4   4    1
5  5    5   5    1
6  6    6   6    1

In [22]:
# Show how to count number of times each unique value appears in group, and for multiple columns

data = [
  ['amazon.com',  'correct',   'correct'  ], 
  ['amazon.com',  'incorrect', 'correct'  ], 
  ['walmart.com', 'incorrect', 'correct'  ], 
  ['walmart.com', 'incorrect', 'incorrect']
]

source = pd.DataFrame(data, columns=['domain', 'price', 'product'])

df = source.groupby('domain').apply(lambda x: x[['price','product']].apply(lambda y: y.value_counts())).fillna(0)
display(df)
df2= df.rename_axis(["domain","is_correct"]).reset_index()
display(df2)

                       price  product
domain
amazon.com  correct      1.0      2.0
            incorrect    1.0      0.0
walmart.com correct      0.0      1.0
            incorrect    2.0      1.0

        domain is_correct  price  product
0   amazon.com    correct    1.0      2.0
1   amazon.com  incorrect    1.0      0.0
2  walmart.com    correct    0.0      1.0
3  walmart.com  incorrect    2.0      1.0

In [23]:
# np.unique is a Numpy function which shows unique values in a column,
# and where they were found first time.

aa=ddd()
np.unique(aa.i2)

array([-3, -2, -1,  0,  1,  4,  5,  6])

In [24]:
# a procedure to extract duplicate rows (by one or more columns)

def show_duplicates(df, cols=[], include_nulls=True):
    """
    # accepts a dataframe df and a column (or list of columns)
    # if list of columns is not provided - uses all df columns
    # returns a dataframe consisting of rows of df
    # which have duplicate values in "cols"
    # sorted by "cols" so that duplciates are next to each other
    # Note - doesn't change index values of rows
    """
    # ---------------------------------
    aa = df.copy()
    mycols = cols
    # ---------------------------------
    if len(mycols) <= 0:
        mycols = aa.columns.tolist()
    elif type(mycols) != list:
        mycols = list(mycols)
    # ---------------------------------
    if not include_nulls:
        mask = False
        for mycol in mycols:
            mask = mask | (aa[mycol] != aa[mycol])  # test for null values
        aa = aa[~mask]                              # remove rows with nulls in mycols
    if len(aa) <= 0:
        return aa[:0]
    # ---------------------------------
    # duplicated() method returns Boolean Series denoting duplicate rows
    mask = aa.duplicated(subset=mycols, keep='first').values \
         | aa.duplicated(subset=mycols, keep='last').values
    aa = aa[mask]
    if len(aa) <= 0:
        return aa[:0]
    # ---------------------------------
    # sorting to keep duplicates together
    # Attention - can not sort by nulls
    # bb contains mycols except for cols which are completely nulls
    bb = aa[mycols]
    bb = bb.dropna(how='all',axis=1)
    # sort aa by columns in bb (thus avoiding nulls)
    aa = aa.sort_values(by=bb.columns.tolist())
    # ---------------------------------
    # sorting skips nulls thus messing up the order. 
    # Let's put nulls at the end
    mask = False
    for mycol in mycols:
        mask = mask | (aa[mycol] != aa[mycol])  # test for null values
    aa1 = aa[~mask]
    aa2 = aa[mask]
    aa = aa1.append(aa2)

    return aa

In [25]:
aa = ddd()
show_duplicates(df=aa, cols=['i2'], include_nulls=True)

    ii  i1  i2   ff        f1    f2   ss   s1    s2     bb     b1  xx          yy
4  4.0   2   1  4.0  4.000040  5.55  NaN  nan  5.55    NaN   True   4  259.730558
5  5.0   1   1  5.0  5.000005  7.77   s5   s5  7.77  False  False   5  310.967836
2  2.0   4   4  2.0  2.002000  3.33    狗   s2  3.33   True   True   2  159.781108
3  3.0   3   4  NaN  3.000300  4.44   汽车   s2  4.44  False  False   3  211.246377

### -------------------- Question 6 --------------------

- Show how to append dataframes
- Show how to append a list (or series) of data to a dataframe

#### Answer

In [26]:
# append two dataframes one on top of the other
aa1 = ddd(5)
aa2 = ddd(5)
aa = aa1.append(aa2)
aa.index = range(len(aa))
display(aa)

     ii  i1  i2   ff        f1    f2   ss   s1    s2     bb     b1  xx          yy
0   0.0   6   6  0.0  0.000000  1.11   s0   s0  1.11   True   True   0   59.830192
1   1.0   5   5  1.0  1.010000  2.22   s1   s1  2.22  False  False   1  109.496098
2   2.0   4   4  2.0  2.002000  3.33    狗   s2  3.33   True   True   2  161.525521
3   3.0   3   4  NaN  3.000300  4.44   汽车   s2  4.44  False  False   3  210.125854
4   4.0   2   1  4.0  4.000040  5.55  NaN  nan  5.55    NaN   True   4  260.469564
5   5.0   1   1  5.0  5.000005  7.77   s5   s5  7.77  False  False   5  310.492669
6   0.0   6   6  0.0  0.000000  1.11   s0   s0  1.11   True   True   0   61.284636
7   1.0   5   5  1.0  1.010000  2.22   s1   s1  2.22  False  False   1  109.210789
8   2.0   4   4  2.0  2.002000  3.33    狗   s2  3.33   True   True   2  159.662808
9   3.0   3   4  NaN  3.000300  4.44   汽车   s2  4.44  False  False   3  209.283565
10  4.0   2   1  4.0  4.000040  5.55  NaN  nan  5.55    NaN   True   4  260.165500
11  5.0   1   1  5.0  5.000005  7.77   s5   s5  7.77  False  False   5  308.368898

In [27]:
# append a series or list by converting it to a DataFrame
aa = ddd()
bb = aa.loc[1].tolist()   # take 2nd row as a list
dd = pd.DataFrame([bb], columns=aa.columns)

# now append list
aa = aa.append(dd)
display(aa)

# Note: alternatively you can make 1-column dataframe - and transpose it
# bb=DataFrame(ss)
# bb.index = aa.columns
# aa.append(bb.T)

    ii  i1  i2   ff        f1    f2   ss   s1     s2     bb     b1  xx          yy
0  0.0   6   6  0.0  0.000000  1.11   s0   s0   1.11   True   True   0   60.969569
1  1.0   5   5  1.0  1.010000  2.22   s1   s1   2.22  False  False   1  110.791612
2  2.0   4   4  2.0  2.002000  3.33    狗   s2   3.33   True   True   2  160.688541
3  3.0   3   4  NaN  3.000300  4.44   汽车   s2   4.44  False  False   3  209.707922
4  4.0   2   1  4.0  4.000040  5.55  NaN  nan   5.55    NaN   True   4  258.117990
5  5.0   1   1  5.0  5.000005  7.77   s5   s5   7.77  False  False   5  309.558969
6  NaN   0   0  6.0  6.000001  9.99   s6   s6   9.99   True   True   6  359.401384
7  7.0  -1  -1  7.0  7.000000  0.01   s7   s7   0.01    NaN   True   7  410.296374
8  8.0  -2  -2  8.0  8.000000 -0.01   s8   s8  -0.01  False  False   8  460.117663
9  9.0  -3  -3  9.0  9.000000 -1.11   s9   s9  -1.11   True   True   9  507.753601
0  1.0   5   5  1.0  1.010000  2.22   s1   s1   2.22  False  False   1  110.791612

### -------------------- Question 7 --------------------

Show how to remove duplicate rows (duplicate is defined as having same value in a list of columns)

#### Answer

In [28]:
aa = aa.drop_duplicates(['i2']) 
# or
aa = aa.drop_duplicates(['i2'], keep='last') 
display(aa)

    ii  i1  i2   ff        f1    f2   ss   s1     s2     bb     b1  xx          yy
0  0.0   6   6  0.0  0.000000  1.11   s0   s0   1.11   True   True   0   60.969569
1  1.0   5   5  1.0  1.010000  2.22   s1   s1   2.22  False  False   1  110.791612
2  2.0   4   4  2.0  2.002000  3.33    狗   s2   3.33   True   True   2  160.688541
4  4.0   2   1  4.0  4.000040  5.55  NaN  nan   5.55    NaN   True   4  258.117990
6  NaN   0   0  6.0  6.000001  9.99   s6   s6   9.99   True   True   6  359.401384
7  7.0  -1  -1  7.0  7.000000  0.01   s7   s7   0.01    NaN   True   7  410.296374
8  8.0  -2  -2  8.0  8.000000 -0.01   s8   s8  -0.01  False  False   8  460.117663
9  9.0  -3  -3  9.0  9.000000 -1.11   s9   s9  -1.11   True   True   9  507.753601

### -------------------- Question 8 --------------------

Show how to use a mask using   &, |, ~, .isin(), .isnull()

#### Answer

In [29]:
aa=ddd()
mask = aa.f2.isnull()
display(aa[mask])
print('-'*40)
mask = aa.i1.isin([1,3,5])
display(aa[mask])
print('-'*40)
display(aa[~mask]) # shows the records where mask is False
print('-'*40)

# examples of masks based on more than one column
# mask = (aa.ii==1) & (aa.i2 == 4)
# mask = (aa.ii==1) | (aa.i2 == 4)

Empty DataFrame
Columns: [ii, i1, i2, ff, f1, f2, ss, s1, s2, bb, b1, xx, yy]
Index: []

----------------------------------------

    ii  i1  i2   ff        f1    f2  ss  s1    s2     bb     b1  xx          yy
1  1.0   5   5  1.0  1.010000  2.22  s1  s1  2.22  False  False   1  111.424072
3  3.0   3   4  NaN  3.000300  4.44  汽车  s2  4.44  False  False   3  210.172177
5  5.0   1   1  5.0  5.000005  7.77  s5  s5  7.77  False  False   5  309.631891

----------------------------------------

    ii  i1  i2   ff        f1    f2   ss   s1     s2     bb     b1  xx          yy
0  0.0   6   6  0.0  0.000000  1.11   s0   s0   1.11   True   True   0   59.596080
2  2.0   4   4  2.0  2.002000  3.33    狗   s2   3.33   True   True   2  160.178226
4  4.0   2   1  4.0  4.000040  5.55  NaN  nan   5.55    NaN   True   4  258.604110
6  NaN   0   0  6.0  6.000001  9.99   s6   s6   9.99   True   True   6  360.043442
7  7.0  -1  -1  7.0  7.000000  0.01   s7   s7   0.01    NaN   True   7  409.502520
8  8.0  -2  -2  8.0  8.000000 -0.01   s8   s8  -0.01  False  False   8  462.541019
9  9.0  -3  -3  9.0  9.000000 -1.11   s9   s9  -1.11   True   True   9  509.641345

----------------------------------------

Note:
    isnull()  & isna()   functions are the same thing
    notnull() & notna()  are also equivalent
    
All these functions identify both Numpy "np.nan" and Python "None" values. 
So you can deal with both cases of missing values at the same time.

### -------------------- Question 9 --------------------

Give an example of using a map() function on a pandas DataFrame column

#### Answer

In [30]:
aa=ddd()
str(aa.yy)

'0     60.267249\n1    110.050693\n2    159.577370\n3    209.139997\n4    260.054336\n5    311.174605\n6    359.702453\n7    409.510651\n8    461.079077\n9    508.891782\nName: yy, dtype: float64'

In [31]:
aa=ddd()
display(aa.yy.dtype)
aa['yy'] = aa.yy.map(lambda crocodile : str(round(crocodile,2)) + "abc")
display(aa)

dtype('float64')

    ii  i1  i2   ff        f1    f2   ss   s1     s2     bb     b1  xx         yy
0  0.0   6   6  0.0  0.000000  1.11   s0   s0   1.11   True   True   0   60.99abc
1  1.0   5   5  1.0  1.010000  2.22   s1   s1   2.22  False  False   1  110.14abc
2  2.0   4   4  2.0  2.002000  3.33    狗   s2   3.33   True   True   2  158.54abc
3  3.0   3   4  NaN  3.000300  4.44   汽车   s2   4.44  False  False   3  209.15abc
4  4.0   2   1  4.0  4.000040  5.55  NaN  nan   5.55    NaN   True   4  260.17abc
5  5.0   1   1  5.0  5.000005  7.77   s5   s5   7.77  False  False   5  308.85abc
6  NaN   0   0  6.0  6.000001  9.99   s6   s6   9.99   True   True   6  359.54abc
7  7.0  -1  -1  7.0  7.000000  0.01   s7   s7   0.01    NaN   True   7  410.39abc
8  8.0  -2  -2  8.0  8.000000 -0.01   s8   s8  -0.01  False  False   8  462.37abc
9  9.0  -3  -3  9.0  9.000000 -1.11   s9   s9  -1.11   True   True   9  509.98abc

### -------------------- Question 10 --------------------

Give example using map with lambda for dataframe operations

#### Answer

In [32]:
aa = ddd()
aa['s2'] = aa.ss + '__' + aa.i1.map(lambda x: str(x))

# make a list of values in column 'yy' 
# rounded to 2 digits after dot
aa['zz'] = aa['yy'].map(lambda x: round(x,2))
display(aa)

    ii  i1  i2   ff        f1    f2   ss   s1      s2     bb     b1  xx          yy      zz
0  0.0   6   6  0.0  0.000000  1.11   s0   s0   s0__6   True   True   0   59.829130   59.83
1  1.0   5   5  1.0  1.010000  2.22   s1   s1   s1__5  False  False   1  107.919578  107.92
2  2.0   4   4  2.0  2.002000  3.33    狗   s2    狗__4   True   True   2  158.669650  158.67
3  3.0   3   4  NaN  3.000300  4.44   汽车   s2   汽车__3  False  False   3  212.443432  212.44
4  4.0   2   1  4.0  4.000040  5.55  NaN  nan     NaN    NaN   True   4  258.868737  258.87
5  5.0   1   1  5.0  5.000005  7.77   s5   s5   s5__1  False  False   5  312.267060  312.27
6  NaN   0   0  6.0  6.000001  9.99   s6   s6   s6__0   True   True   6  357.905019  357.91
7  7.0  -1  -1  7.0  7.000000  0.01   s7   s7  s7__-1    NaN   True   7  411.228596  411.23
8  8.0  -2  -2  8.0  8.000000 -0.01   s8   s8  s8__-2  False  False   8  461.114196  461.11
9  9.0  -3  -3  9.0  9.000000 -1.11   s9   s9  s9__-3   True   True   9  508.181706  508.18

### -------------------- Question 11 --------------------

Give example using groupby().sum()

#### Answer

In [33]:
aa = ddd()
cc = aa.groupby(['i2'], as_index=False).sum()
display(cc)
print("-"*40)

# note - groupby().sum() will usually remove all 
# string columns from the result. To avoid it, you can use agg()
# But be carefull to avoid mixing NaN with strings - causes error 

aa = ddd()
aa['ss'] = aa.ss.fillna('_') # this removes NaN
cc = aa.groupby('i2', as_index=False).agg({'i1':np.sum,'ss':np.max})
display(cc)

   i2   ii  i1   ff        f1     f2  b1  xx          yy
0  -3  9.0  -3  9.0  9.000000  -1.11   1   9  509.234671
1  -2  8.0  -2  8.0  8.000000  -0.01   0   8  461.159415
2  -1  7.0  -1  7.0  7.000000   0.01   1   7  409.097871
3   0  0.0   0  6.0  6.000001   9.99   1   6  359.537131
4   1  9.0   3  9.0  9.000045  13.32   1   9  566.902706
5   4  5.0   7  2.0  5.002300   7.77   1   5  368.730045
6   5  1.0   5  1.0  1.010000   2.22   0   1  111.399308
7   6  0.0   6  0.0  0.000000   1.11   1   0   59.354759

----------------------------------------

   i2  i1  ss
0  -3  -3  s9
1  -2  -2  s8
2  -1  -1  s7
3   0   0  s6
4   1   3  s5
5   4   7   狗
6   5   5  s1
7   6   6  s0

### -------------------- Question 12 --------------------

Give example using groupby().aggregate()

#### Answer

In [34]:
aa = ddd()
bb = aa.groupby('i2', as_index=True).aggregate({'yy':np.sum, 'xx':np.max}) 
display(bb)

            yy  xx
i2
-3  511.460659   9
-2  458.519219   8
-1  409.816814   7
 0  360.169770   6
 1  570.987686   5
 4  369.605792   3
 5  110.863450   1
 6   59.362732   0

### -------------------- Question 13 --------------------

Show how to sort a dataframe by a list of columns

#### Answer

In [35]:
cc = aa.sort_values(by=['i2','yy'])
display(cc)

    ii  i1  i2   ff        f1    f2   ss   s1     s2     bb     b1  xx          yy
9  9.0  -3  -3  9.0  9.000000 -1.11   s9   s9  -1.11   True   True   9  511.460659
8  8.0  -2  -2  8.0  8.000000 -0.01   s8   s8  -0.01  False  False   8  458.519219
7  7.0  -1  -1  7.0  7.000000  0.01   s7   s7   0.01    NaN   True   7  409.816814
6  NaN   0   0  6.0  6.000001  9.99   s6   s6   9.99   True   True   6  360.169770
4  4.0   2   1  4.0  4.000040  5.55  NaN  nan   5.55    NaN   True   4  260.942425
5  5.0   1   1  5.0  5.000005  7.77   s5   s5   7.77  False  False   5  310.045261
2  2.0   4   4  2.0  2.002000  3.33    狗   s2   3.33   True   True   2  160.722904
3  3.0   3   4  NaN  3.000300  4.44   汽车   s2   4.44  False  False   3  208.882888
1  1.0   5   5  1.0  1.010000  2.22   s1   s1   2.22  False  False   1  110.863450
0  0.0   6   6  0.0  0.000000  1.11   s0   s0   1.11   True   True   0   59.362732

### -------------------- Question 14 --------------------

Show how to delete some rows from dataframe - and reindex

#### Answer

In [36]:
aa = ddd()
aa = aa.drop([1,3,5]) # remove several rows 
display(aa)

    ii  i1  i2   ff        f1    f2   ss   s1     s2     bb     b1  xx          yy
0  0.0   6   6  0.0  0.000000  1.11   s0   s0   1.11   True   True   0   59.967335
2  2.0   4   4  2.0  2.002000  3.33    狗   s2   3.33   True   True   2  160.281921
4  4.0   2   1  4.0  4.000040  5.55  NaN  nan   5.55    NaN   True   4  260.921958
6  NaN   0   0  6.0  6.000001  9.99   s6   s6   9.99   True   True   6  362.262240
7  7.0  -1  -1  7.0  7.000000  0.01   s7   s7   0.01    NaN   True   7  409.410943
8  8.0  -2  -2  8.0  8.000000 -0.01   s8   s8  -0.01  False  False   8  460.596296
9  9.0  -3  -3  9.0  9.000000 -1.11   s9   s9  -1.11   True   True   9  509.651154

In [37]:
# remove rows based on a mask
aa = ddd()
mask = aa['ii'].map(lambda x: x > 3) # True when aa.ii > 3
aa = aa[~mask]                       # take only where a.ii <= 3 or NaN
display(aa)
print('-'*40)
mask = aa['ii'].map(lambda x: x in (0,1,4))
aa = aa[~mask]
display(aa)

    ii  i1  i2   ff        f1    f2  ss  s1    s2     bb     b1  xx          yy
0  0.0   6   6  0.0  0.000000  1.11  s0  s0  1.11   True   True   0   58.029269
1  1.0   5   5  1.0  1.010000  2.22  s1  s1  2.22  False  False   1  109.752446
2  2.0   4   4  2.0  2.002000  3.33   狗  s2  3.33   True   True   2  159.697184
3  3.0   3   4  NaN  3.000300  4.44  汽车  s2  4.44  False  False   3  210.316855
6  NaN   0   0  6.0  6.000001  9.99  s6  s6  9.99   True   True   6  359.825106

----------------------------------------

    ii  i1  i2   ff        f1    f2  ss  s1    s2     bb     b1  xx          yy
2  2.0   4   4  2.0  2.002000  3.33   狗  s2  3.33   True   True   2  159.697184
3  3.0   3   4  NaN  3.000300  4.44  汽车  s2  4.44  False  False   3  210.316855
6  NaN   0   0  6.0  6.000001  9.99  s6  s6  9.99   True   True   6  359.825106

In [38]:
# after removing rows you may want to index rows sequentially
aa = ddd()
aa.reindex() # doesn't change index unless you provide it 
print('-0'*30)
aa.index = range(len(aa))
display(aa)
print('-1'*30)
# note - you can shift index
aa.index = range(100,100+len(aa))
display(aa)
print('-2'*30)
# you can even make all index values the same - although it is pointless
aa.index = [2]*len(aa)
display(aa)

-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0

    ii  i1  i2   ff        f1    f2   ss   s1     s2     bb     b1  xx          yy
0  0.0   6   6  0.0  0.000000  1.11   s0   s0   1.11   True   True   0   61.710494
1  1.0   5   5  1.0  1.010000  2.22   s1   s1   2.22  False  False   1  109.994115
2  2.0   4   4  2.0  2.002000  3.33    狗   s2   3.33   True   True   2  159.580964
3  3.0   3   4  NaN  3.000300  4.44   汽车   s2   4.44  False  False   3  209.237637
4  4.0   2   1  4.0  4.000040  5.55  NaN  nan   5.55    NaN   True   4  260.004828
5  5.0   1   1  5.0  5.000005  7.77   s5   s5   7.77  False  False   5  309.823276
6  NaN   0   0  6.0  6.000001  9.99   s6   s6   9.99   True   True   6  360.199728
7  7.0  -1  -1  7.0  7.000000  0.01   s7   s7   0.01    NaN   True   7  408.240815
8  8.0  -2  -2  8.0  8.000000 -0.01   s8   s8  -0.01  False  False   8  458.374015
9  9.0  -3  -3  9.0  9.000000 -1.11   s9   s9  -1.11   True   True   9  508.564301

-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1

      ii  i1  i2   ff        f1    f2   ss   s1     s2     bb     b1  xx          yy
100  0.0   6   6  0.0  0.000000  1.11   s0   s0   1.11   True   True   0   61.710494
101  1.0   5   5  1.0  1.010000  2.22   s1   s1   2.22  False  False   1  109.994115
102  2.0   4   4  2.0  2.002000  3.33    狗   s2   3.33   True   True   2  159.580964
103  3.0   3   4  NaN  3.000300  4.44   汽车   s2   4.44  False  False   3  209.237637
104  4.0   2   1  4.0  4.000040  5.55  NaN  nan   5.55    NaN   True   4  260.004828
105  5.0   1   1  5.0  5.000005  7.77   s5   s5   7.77  False  False   5  309.823276
106  NaN   0   0  6.0  6.000001  9.99   s6   s6   9.99   True   True   6  360.199728
107  7.0  -1  -1  7.0  7.000000  0.01   s7   s7   0.01    NaN   True   7  408.240815
108  8.0  -2  -2  8.0  8.000000 -0.01   s8   s8  -0.01  False  False   8  458.374015
109  9.0  -3  -3  9.0  9.000000 -1.11   s9   s9  -1.11   True   True   9  508.564301

-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2

    ii  i1  i2   ff        f1    f2   ss   s1     s2     bb     b1  xx          yy
2  0.0   6   6  0.0  0.000000  1.11   s0   s0   1.11   True   True   0   61.710494
2  1.0   5   5  1.0  1.010000  2.22   s1   s1   2.22  False  False   1  109.994115
2  2.0   4   4  2.0  2.002000  3.33    狗   s2   3.33   True   True   2  159.580964
2  3.0   3   4  NaN  3.000300  4.44   汽车   s2   4.44  False  False   3  209.237637
2  4.0   2   1  4.0  4.000040  5.55  NaN  nan   5.55    NaN   True   4  260.004828
2  5.0   1   1  5.0  5.000005  7.77   s5   s5   7.77  False  False   5  309.823276
2  NaN   0   0  6.0  6.000001  9.99   s6   s6   9.99   True   True   6  360.199728
2  7.0  -1  -1  7.0  7.000000  0.01   s7   s7   0.01    NaN   True   7  408.240815
2  8.0  -2  -2  8.0  8.000000 -0.01   s8   s8  -0.01  False  False   8  458.374015
2  9.0  -3  -3  9.0  9.000000 -1.11   s9   s9  -1.11   True   True   9  508.564301

### -------------------- Question 15 --------------------

Show how to add rows to a dataframe 
<br>(add 2 dataframes together vertically - and reindex)

#### Answer

In [39]:
aa=ddd()
aa = aa.append(aa[2:4],ignore_index=True)
display(aa)

     ii  i1  i2   ff        f1    f2   ss   s1     s2     bb     b1  xx          yy
0   0.0   6   6  0.0  0.000000  1.11   s0   s0   1.11   True   True   0   59.436064
1   1.0   5   5  1.0  1.010000  2.22   s1   s1   2.22  False  False   1  109.332297
2   2.0   4   4  2.0  2.002000  3.33    狗   s2   3.33   True   True   2  159.831625
3   3.0   3   4  NaN  3.000300  4.44   汽车   s2   4.44  False  False   3  209.448210
4   4.0   2   1  4.0  4.000040  5.55  NaN  nan   5.55    NaN   True   4  258.849733
5   5.0   1   1  5.0  5.000005  7.77   s5   s5   7.77  False  False   5  310.134182
6   NaN   0   0  6.0  6.000001  9.99   s6   s6   9.99   True   True   6  360.066465
7   7.0  -1  -1  7.0  7.000000  0.01   s7   s7   0.01    NaN   True   7  411.199626
8   8.0  -2  -2  8.0  8.000000 -0.01   s8   s8  -0.01  False  False   8  459.089508
9   9.0  -3  -3  9.0  9.000000 -1.11   s9   s9  -1.11   True   True   9  509.668449
10  2.0   4   4  2.0  2.002000  3.33    狗   s2   3.33   True   True   2  159.831625
11  3.0   3   4  NaN  3.000300  4.44   汽车   s2   4.44  False  False   3  209.448210

### -------------------- Question 16 --------------------

- Show how to write dataframe to csv file
- Show how to read it back

#### Answer

In [40]:
aa = ddd()
aa.to_csv('junk.csv', sep='|', header=True, index=False)
bb = pd.read_csv('junk.csv', sep='|')
display(bb)

    ii  i1  i2   ff        f1    f2   ss   s1    s2     bb     b1  xx          yy
0  0.0   6   6  0.0  0.000000  1.11   s0   s0  1.11   True   True   0   58.877278
1  1.0   5   5  1.0  1.010000  2.22   s1   s1  2.22  False  False   1  110.732742
2  2.0   4   4  2.0  2.002000  3.33    狗   s2  3.33   True   True   2  159.300862
3  3.0   3   4  NaN  3.000300  4.44   汽车   s2  4.44  False  False   3  211.562227
4  4.0   2   1  4.0  4.000040  5.55  NaN  NaN  5.55    NaN   True   4  257.730958
5  5.0   1   1  5.0  5.000005  7.77   s5   s5  7.77  False  False   5  311.411412
6  NaN   0   0  6.0  6.000001  9.99   s6   s6  9.99   True   True   6  359.476589
7  7.0  -1  -1  7.0  7.000000  0.01   s7   s7  0.01    NaN   True   7  412.877511
8  8.0  -2  -2  8.0  8.000000 -0.01   s8   s8 -0.01  False  False   8  458.532228
9  9.0  -3  -3  9.0  9.000000 -1.11   s9   s9 -1.11   True   True   9  511.738299

### -------------------- Question 17 --------------------

- Show how to add columns to pandas DataFrame
- Show how to calculate column values from numeric/string values in other columns.
- Show how to delete one or more columns

#### Answer

In [41]:
aa = ddd()
aa['c4'] = None         # populate with same value
display(aa)
print('-0'*30)
col2=[1,2,3,4,5,6,7,8,9,0]
aa['c4'] = col2         # list becomes a column
display(aa)
print('-1'*30)
aa['c4'] = "-"
display(aa)
print('-2'*30)

# adding a column - and populating it using vectorized operation on columns
aa['c5']= 2*aa['i1'] + 3*aa['i2'] + 5
display(aa)
print('-3'*30)

# calculating column values from other columns:
aa['c4']= 2*aa['i1'] + 3*aa['i2'] + 5
aa['s2'] = aa.ss + '__' + aa.i1.map(lambda x: str(x))
display(aa)
print('-4'*30)

# Deleting one column
del aa['s1']
display(aa)
print('-5'*30)

# Deleting many columns
aa = aa.drop(['i1','i2','c4'], axis=1)
display(aa)

    ii  i1  i2   ff        f1    f2   ss   s1     s2     bb     b1  xx          yy    c4
0  0.0   6   6  0.0  0.000000  1.11   s0   s0   1.11   True   True   0   60.015384  None
1  1.0   5   5  1.0  1.010000  2.22   s1   s1   2.22  False  False   1  109.752942  None
2  2.0   4   4  2.0  2.002000  3.33    狗   s2   3.33   True   True   2  156.827024  None
3  3.0   3   4  NaN  3.000300  4.44   汽车   s2   4.44  False  False   3  210.075801  None
4  4.0   2   1  4.0  4.000040  5.55  NaN  nan   5.55    NaN   True   4  259.969925  None
5  5.0   1   1  5.0  5.000005  7.77   s5   s5   7.77  False  False   5  310.152449  None
6  NaN   0   0  6.0  6.000001  9.99   s6   s6   9.99   True   True   6  361.260813  None
7  7.0  -1  -1  7.0  7.000000  0.01   s7   s7   0.01    NaN   True   7  408.684975  None
8  8.0  -2  -2  8.0  8.000000 -0.01   s8   s8  -0.01  False  False   8  460.152865  None
9  9.0  -3  -3  9.0  9.000000 -1.11   s9   s9  -1.11   True   True   9  511.084131  None

-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0

    ii  i1  i2   ff        f1    f2   ss   s1     s2     bb     b1  xx          yy  c4
0  0.0   6   6  0.0  0.000000  1.11   s0   s0   1.11   True   True   0   60.015384   1
1  1.0   5   5  1.0  1.010000  2.22   s1   s1   2.22  False  False   1  109.752942   2
2  2.0   4   4  2.0  2.002000  3.33    狗   s2   3.33   True   True   2  156.827024   3
3  3.0   3   4  NaN  3.000300  4.44   汽车   s2   4.44  False  False   3  210.075801   4
4  4.0   2   1  4.0  4.000040  5.55  NaN  nan   5.55    NaN   True   4  259.969925   5
5  5.0   1   1  5.0  5.000005  7.77   s5   s5   7.77  False  False   5  310.152449   6
6  NaN   0   0  6.0  6.000001  9.99   s6   s6   9.99   True   True   6  361.260813   7
7  7.0  -1  -1  7.0  7.000000  0.01   s7   s7   0.01    NaN   True   7  408.684975   8
8  8.0  -2  -2  8.0  8.000000 -0.01   s8   s8  -0.01  False  False   8  460.152865   9
9  9.0  -3  -3  9.0  9.000000 -1.11   s9   s9  -1.11   True   True   9  511.084131   0

-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1

    ii  i1  i2   ff        f1    f2   ss   s1     s2     bb     b1  xx          yy c4
0  0.0   6   6  0.0  0.000000  1.11   s0   s0   1.11   True   True   0   60.015384  -
1  1.0   5   5  1.0  1.010000  2.22   s1   s1   2.22  False  False   1  109.752942  -
2  2.0   4   4  2.0  2.002000  3.33    狗   s2   3.33   True   True   2  156.827024  -
3  3.0   3   4  NaN  3.000300  4.44   汽车   s2   4.44  False  False   3  210.075801  -
4  4.0   2   1  4.0  4.000040  5.55  NaN  nan   5.55    NaN   True   4  259.969925  -
5  5.0   1   1  5.0  5.000005  7.77   s5   s5   7.77  False  False   5  310.152449  -
6  NaN   0   0  6.0  6.000001  9.99   s6   s6   9.99   True   True   6  361.260813  -
7  7.0  -1  -1  7.0  7.000000  0.01   s7   s7   0.01    NaN   True   7  408.684975  -
8  8.0  -2  -2  8.0  8.000000 -0.01   s8   s8  -0.01  False  False   8  460.152865  -
9  9.0  -3  -3  9.0  9.000000 -1.11   s9   s9  -1.11   True   True   9  511.084131  -

-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2

    ii  i1  i2   ff        f1    f2   ss   s1     s2     bb     b1  xx          yy c4  c5
0  0.0   6   6  0.0  0.000000  1.11   s0   s0   1.11   True   True   0   60.015384  -  35
1  1.0   5   5  1.0  1.010000  2.22   s1   s1   2.22  False  False   1  109.752942  -  30
2  2.0   4   4  2.0  2.002000  3.33    狗   s2   3.33   True   True   2  156.827024  -  25
3  3.0   3   4  NaN  3.000300  4.44   汽车   s2   4.44  False  False   3  210.075801  -  23
4  4.0   2   1  4.0  4.000040  5.55  NaN  nan   5.55    NaN   True   4  259.969925  -  12
5  5.0   1   1  5.0  5.000005  7.77   s5   s5   7.77  False  False   5  310.152449  -  10
6  NaN   0   0  6.0  6.000001  9.99   s6   s6   9.99   True   True   6  361.260813  -   5
7  7.0  -1  -1  7.0  7.000000  0.01   s7   s7   0.01    NaN   True   7  408.684975  -   0
8  8.0  -2  -2  8.0  8.000000 -0.01   s8   s8  -0.01  False  False   8  460.152865  -  -5
9  9.0  -3  -3  9.0  9.000000 -1.11   s9   s9  -1.11   True   True   9  511.084131  - -10

-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3

    ii  i1  i2   ff        f1    f2   ss   s1      s2     bb     b1  xx          yy  c4  c5
0  0.0   6   6  0.0  0.000000  1.11   s0   s0   s0__6   True   True   0   60.015384  35  35
1  1.0   5   5  1.0  1.010000  2.22   s1   s1   s1__5  False  False   1  109.752942  30  30
2  2.0   4   4  2.0  2.002000  3.33    狗   s2    狗__4   True   True   2  156.827024  25  25
3  3.0   3   4  NaN  3.000300  4.44   汽车   s2   汽车__3  False  False   3  210.075801  23  23
4  4.0   2   1  4.0  4.000040  5.55  NaN  nan     NaN    NaN   True   4  259.969925  12  12
5  5.0   1   1  5.0  5.000005  7.77   s5   s5   s5__1  False  False   5  310.152449  10  10
6  NaN   0   0  6.0  6.000001  9.99   s6   s6   s6__0   True   True   6  361.260813   5   5
7  7.0  -1  -1  7.0  7.000000  0.01   s7   s7  s7__-1    NaN   True   7  408.684975   0   0
8  8.0  -2  -2  8.0  8.000000 -0.01   s8   s8  s8__-2  False  False   8  460.152865  -5  -5
9  9.0  -3  -3  9.0  9.000000 -1.11   s9   s9  s9__-3   True   True   9  511.084131 -10 -10

-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4

    ii  i1  i2   ff        f1    f2   ss      s2     bb     b1  xx          yy  c4  c5
0  0.0   6   6  0.0  0.000000  1.11   s0   s0__6   True   True   0   60.015384  35  35
1  1.0   5   5  1.0  1.010000  2.22   s1   s1__5  False  False   1  109.752942  30  30
2  2.0   4   4  2.0  2.002000  3.33    狗    狗__4   True   True   2  156.827024  25  25
3  3.0   3   4  NaN  3.000300  4.44   汽车   汽车__3  False  False   3  210.075801  23  23
4  4.0   2   1  4.0  4.000040  5.55  NaN     NaN    NaN   True   4  259.969925  12  12
5  5.0   1   1  5.0  5.000005  7.77   s5   s5__1  False  False   5  310.152449  10  10
6  NaN   0   0  6.0  6.000001  9.99   s6   s6__0   True   True   6  361.260813   5   5
7  7.0  -1  -1  7.0  7.000000  0.01   s7  s7__-1    NaN   True   7  408.684975   0   0
8  8.0  -2  -2  8.0  8.000000 -0.01   s8  s8__-2  False  False   8  460.152865  -5  -5
9  9.0  -3  -3  9.0  9.000000 -1.11   s9  s9__-3   True   True   9  511.084131 -10 -10

-5-5-5-5-5-5-5-5-5-5-5-5-5-5-5-5-5-5-5-5-5-5-5-5-5-5-5-5-5-5

    ii   ff        f1    f2   ss      s2     bb     b1  xx          yy  c5
0  0.0  0.0  0.000000  1.11   s0   s0__6   True   True   0   60.015384  35
1  1.0  1.0  1.010000  2.22   s1   s1__5  False  False   1  109.752942  30
2  2.0  2.0  2.002000  3.33    狗    狗__4   True   True   2  156.827024  25
3  3.0  NaN  3.000300  4.44   汽车   汽车__3  False  False   3  210.075801  23
4  4.0  4.0  4.000040  5.55  NaN     NaN    NaN   True   4  259.969925  12
5  5.0  5.0  5.000005  7.77   s5   s5__1  False  False   5  310.152449  10
6  NaN  6.0  6.000001  9.99   s6   s6__0   True   True   6  361.260813   5
7  7.0  7.0  7.000000  0.01   s7  s7__-1    NaN   True   7  408.684975   0
8  8.0  8.0  8.000000 -0.01   s8  s8__-2  False  False   8  460.152865  -5
9  9.0  9.0  9.000000 -1.11   s9  s9__-3   True   True   9  511.084131 -10

### -------------------- Question 18 --------------------

Show how to calculate a pandas DataFrame column 
as a linear combination of some other columns

#### Answer

In [42]:
aa = ddd()
aa['c4']= 2*aa['i1'] + 3*aa['i2'] + 5 
display(aa)

    ii  i1  i2   ff        f1    f2   ss   s1     s2     bb     b1  xx          yy  c4
0  0.0   6   6  0.0  0.000000  1.11   s0   s0   1.11   True   True   0   60.846969  35
1  1.0   5   5  1.0  1.010000  2.22   s1   s1   2.22  False  False   1  110.009180  30
2  2.0   4   4  2.0  2.002000  3.33    狗   s2   3.33   True   True   2  160.631642  25
3  3.0   3   4  NaN  3.000300  4.44   汽车   s2   4.44  False  False   3  209.671339  23
4  4.0   2   1  4.0  4.000040  5.55  NaN  nan   5.55    NaN   True   4  259.690893  12
5  5.0   1   1  5.0  5.000005  7.77   s5   s5   7.77  False  False   5  308.888928  10
6  NaN   0   0  6.0  6.000001  9.99   s6   s6   9.99   True   True   6  360.831729   5
7  7.0  -1  -1  7.0  7.000000  0.01   s7   s7   0.01    NaN   True   7  408.916180   0
8  8.0  -2  -2  8.0  8.000000 -0.01   s8   s8  -0.01  False  False   8  459.611572  -5
9  9.0  -3  -3  9.0  9.000000 -1.11   s9   s9  -1.11   True   True   9  509.946671 -10

### -------------------- Question 19 --------------------

Show how to calculate a DataFrame column 
from several other columns while using str() and int().<br>
Hint - use map(lambda ..)

#### Answer

In [43]:
aa = ddd()
aa['s3'] = aa['yy'].map(lambda x: int(x)) 
aa['s4']= '>>>' + aa.s3.map(lambda x: str(x)) + '<<<'
display(aa)

    ii  i1  i2   ff        f1    f2   ss   s1     s2     bb     b1  xx          yy   s3         s4
0  0.0   6   6  0.0  0.000000  1.11   s0   s0   1.11   True   True   0   58.842826   58   >>>58<<<
1  1.0   5   5  1.0  1.010000  2.22   s1   s1   2.22  False  False   1  109.131828  109  >>>109<<<
2  2.0   4   4  2.0  2.002000  3.33    狗   s2   3.33   True   True   2  160.963124  160  >>>160<<<
3  3.0   3   4  NaN  3.000300  4.44   汽车   s2   4.44  False  False   3  209.365021  209  >>>209<<<
4  4.0   2   1  4.0  4.000040  5.55  NaN  nan   5.55    NaN   True   4  258.596811  258  >>>258<<<
5  5.0   1   1  5.0  5.000005  7.77   s5   s5   7.77  False  False   5  309.369452  309  >>>309<<<
6  NaN   0   0  6.0  6.000001  9.99   s6   s6   9.99   True   True   6  359.736560  359  >>>359<<<
7  7.0  -1  -1  7.0  7.000000  0.01   s7   s7   0.01    NaN   True   7  410.847353  410  >>>410<<<
8  8.0  -2  -2  8.0  8.000000 -0.01   s8   s8  -0.01  False  False   8  459.575142  459  >>>459<<<
9  9.0  -3  -3  9.0  9.000000 -1.11   s9   s9  -1.11   True   True   9  509.845129  509  >>>509<<<

### -------------------- Question 20 --------------------

Show how to define a mask using regex on one column, and numeric comparison on the other column

#### Answer

In [44]:
import re
aa = ddd()
mask = (aa.i2.map(lambda x: True if re.search(r'4',str(x)) else False)) & (aa.xx > 2)
display(mask)
display(aa[mask])

# more examples
# mask = ( df.a == 1) & (df.b == 2)
# mask = ( df.a == 1) | (df.b == 2)
# mask = ( df.a == 1) | df.b.isin([1,2,3])
# mask = ( df.a == 1) | df.b.map(lambda x: ......)
# mask = ( df.a == 1) | df.b.map(lambda x: ......)  |  df.c.map(lambda x: ......)

0    False
1    False
2    False
3     True
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

    ii  i1  i2  ff      f1    f2  ss  s1    s2     bb     b1  xx          yy
3  3.0   3   4 NaN  3.0003  4.44  汽车  s2  4.44  False  False   3  210.935618

### -------------------- Question 21 --------------------

String operations on columns
<br>How to define a mask using a regular expression

In [45]:
aa = ddd()
mask = aa.ss.map(lambda x: True if re.search(r's[1,3]',str(x)) else False)
display(aa[mask])

    ii  i1  i2   ff    f1    f2  ss  s1    s2     bb     b1  xx          yy
1  1.0   5   5  1.0  1.01  2.22  s1  s1  2.22  False  False   1  110.137456

# what you can do with a DataFrame?

df.abs()
df.sum()
df.min()
df.max()
etc.

pd.DataFrame.<tab>

abs()             corr              first_valid_index last              pivot_table       set_axis          to_json
add               corrwith          floordiv          last_valid_index  plot              set_index         to_latex
add_prefix        count             from_dict         le                pop               shape             to_markdown
add_suffix        cov               from_records      loc               pow               shift             to_numpy
agg               cummax            ge                lookup            prod              size              to_parquet
aggregate         cummin            get               lt                product           skew              to_period
align             cumprod           groupby           mad               quantile          slice_shift       to_pickle
all               cumsum            gt                mask              query             sort_index        to_records
any               describe          head              max               radd              sort_values       to_sql
append            diff              hist              mean              rank              sparse            to_stata
apply             div               iat               median            rdiv              squeeze           to_string
applymap          divide            idxmax            melt              reindex           stack             to_timestamp
asfreq            dot               idxmin            memory_usage      reindex_like      std               to_xarray
asof              drop              iloc              merge             rename            style             transform
assign            drop_duplicates   index             min               rename_axis       sub               transpose
astype            droplevel         infer_objects     mod               reorder_levels    subtract          truediv
at                dropna            info              mode              replace           sum               truncate
at_time           dtypes            insert            mro               resample          swapaxes          tshift
attrs             duplicated        interpolate       mul               reset_index       swaplevel         tz_convert
axes              empty             isin              multiply          rfloordiv         T                 tz_localize
between_time      eq                isna              ndim              rmod              tail              unstack
bfill             equals            isnull            ne                rmul              take              update
bool              eval              items             nlargest          rolling           to_clipboard      values
boxplot           ewm               iteritems         notna             round             to_csv            var
clip              expanding         iterrows          notnull           rpow              to_dict           where
columns           explode           itertuples        nsmallest         rsub              to_excel          xs
combine           ffill             join              nunique           rtruediv          to_feather
combine_first     fillna            keys              pct_change        sample            to_gbq
convert_dtypes    filter            kurt              pipe              select_dtypes     to_hdf
copy              first             kurtosis          pivot             sem               to_html

### -------------------- Question 22 --------------------

How to calculate number of rows in groups

#### Answer

In [46]:
# see discussion here:
# https://stackoverflow.com/questions/19384532/get-statistics-for-each-group-such-as-count-mean-etc-using-pandas-groupby

# Example 1:
#   df = df0.groupby([c1,c2]).size().reset_index(name='mycounts')

# Example 2:
#  df.groupby([c1, c2])[c3].describe()[['count', 'mean']]

### -------------------- Question 23 --------------------

How to avoid SettingWithCopyWarning

You should avoid chained assignments that combine two or more indexing operations.
Because you can't know if pandas will use view or copy after first step.
The choice depends on internal optimization strategy it uses.

If it makes copy, then the copy will be updated instead of original DataFrame.

Bad (not predictable):
       df["z"][mask] = 0
       df.loc[mask]["z"] = 0

Good:
       df.loc[mask, "z"] = 0

Note:
    Sometimes chained operations may be split between several lines of code
       df1 = df["z"]   # df1 may be a view on df
       ... 
       df1[mask] = 0   # you may get a warning here because df1 may be a view or a copy.

    If you want to change the df1 without changing the original df, you can do this:
       df1 = df["z"].copy()  # force copying
       ... 
       df1[mask] = 0         # no warning, changes df1, doesn't chane df

Read this:
 - https://www.dataquest.io/blog/settingwithcopywarning/
 - https://realpython.com/pandas-settingwithcopywarning/

In [47]:
# Example
arr = np.arange(3)
data = { "x": 2**arr, "y": 3**arr}
df = pd.DataFrame(data)
print("original df")
display(df)
# -------------------------
print("chained assignment doesn't change the original DataFrame")
mask = df["y"] < 5
df[mask]["y"] = 0
display(df)
# -------------------------
print("two-parameter .loc[rows, cols] operation does the trick")
df.loc[mask,"y"] = 0
display(df)

original df

   x  y
0  1  1
1  2  3
2  4  9

chained assignment doesn't change the original DataFrame

<ipython-input-47-de8ed88ccd0f>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[mask]["y"] = 0

   x  y
0  1  1
1  2  3
2  4  9

two-parameter .loc[rows, cols] operation does the trick

   x  y
0  1  0
1  2  0
2  4  9