## Python Test 100
## Group Pandas 2 Questions 1..20

In [1]:
import os,sys
import pandas as pd
import numpy as np
from IPython.display import display

In [2]:
def ddd(nrows=10):
    """
    # returns a simple pandas DataFrame - useful for quick tests
    # nrows is number of rows (divisible by 10), for example:
    #     df = ddd()
    #     df = ddd(100)
    #     df = ddd(10**6)   # million rows
    """
    n_aa = 10
    nn = int(nrows/n_aa)
    if nn < 1:
        nn = 1
    aa = pd.DataFrame({
          'ii':nn*[0,1,2,3,4,5,np.nan,7,8,9],
          'i1':nn*[6,5,4,3,2,1,0,-1,-2,-3],
          'i2':nn*[6,5,4,4,1,1,0,-1,-2,-3],
          'ff':nn*[0.0,1.0,2.0,np.NaN,4.0,5.0,6.0,7.0,8.0,9.0],
          'f1':nn*[0.0,1.01,2.002,3.0003,4.00004,5.000005,6.0000006,7.0,8.0,9.0],
          'f2':nn*[1.11,2.22,3.33,4.44,5.55,7.77,9.99,0.01,-0.01,-1.11],
          'ss':nn*['s0','s1','狗','汽车',np.nan,'s5','s6','s7','s8','s9'],
          's1':nn*list(np.array(['s0','s1','s2','s2',np.nan,'s5','s6','s7','s8','s9'],dtype=np.str)),
          's2':nn*['1.11','2.22','3.33','4.44','5.55','7.77','9.99','0.01','-0.01','-1.11'],
          'bb':nn*[True, False, True, False, np.nan, False, True,np.nan, False, True],
          'b1':nn*[True, False, True, False, True, False, True, True, False, True],
          'xx':nn*list(range(n_aa)),
          'yy':nn*[x*50 + 60 + np.random.randn() for x in range(n_aa)]
    })
    aa = aa[['ii','i1','i2','ff','f1','f2','ss','s1','s2','bb','b1','xx','yy']].copy()
    aa.index = range(len(aa))

    if 1 <= nrows < 10:
        aa = aa[:nrows+1]
        
    return aa

### -------------------- Question 1 --------------------

Changing the order of columns in a DataFrame.

#### Answer

In [3]:
aa = pd.DataFrame({
    'a' : [0,1,2],
    'b' : [0,2,4],
    'c' : [0,1,3]
})
display(aa)

col_list_ordered = ['b','c','a']    # When you reorder using these methods, the data in the columns also shift along with names 
aa = aa[col_list_ordered]
display(aa)

print('-'*40)

# or (notice double-brackets)
aa = aa[['c','b','a']]
display(aa)

aa.columns = ['b','a','c']    # Rename columns without changing contents of the columns
display(aa)

   a  b  c
0  0  0  0
1  1  2  1
2  2  4  3

   b  c  a
0  0  0  0
1  2  1  1
2  4  3  2

----------------------------------------

   c  b  a
0  0  0  0
1  1  2  1
2  3  4  2

   b  a  c
0  0  0  0
1  1  2  1
2  3  4  2

### -------------------- Question 2 --------------------

Show how to check if a dataframe has a column with a particular name

#### Answer

In [4]:
aa = ddd()
display(aa.head())
if 'i2' in aa.columns:
    print("true")

    ii  i1  i2   ff       f1    f2   ss   s1    s2     bb     b1  xx          yy
0  0.0   6   6  0.0  0.00000  1.11   s0   s0  1.11   True   True   0   59.860131
1  1.0   5   5  1.0  1.01000  2.22   s1   s1  2.22  False  False   1  109.539767
2  2.0   4   4  2.0  2.00200  3.33    狗   s2  3.33   True   True   2  157.695720
3  3.0   3   4  NaN  3.00030  4.44   汽车   s2  4.44  False  False   3  209.249611
4  4.0   2   1  4.0  4.00004  5.55  NaN  nan  5.55    NaN   True   4  258.656499

true

### -------------------- Question 3 --------------------

Select rows of a pandas DataFrame which have null values (in any column)

#### Answer

In [45]:
mask = False
def rows_with_nulls(df):
    #mask=pd.Series(data = [False]*len(df), index = df.index)
    global mask
    # mask = False
    for col in df.columns:
        print(mask)
        mask = mask | df[col].isnull()

    return df.loc[mask,:].copy()

aa = ddd()
display(aa)
print('-' * 40)
bb = rows_with_nulls(aa)
display(bb)

    ii  i1  i2   ff        f1    f2   ss   s1     s2     bb     b1  xx          yy
0  0.0   6   6  0.0  0.000000  1.11   s0   s0   1.11   True   True   0   60.130148
1  1.0   5   5  1.0  1.010000  2.22   s1   s1   2.22  False  False   1  110.673429
2  2.0   4   4  2.0  2.002000  3.33    狗   s2   3.33   True   True   2  159.560806
3  3.0   3   4  NaN  3.000300  4.44   汽车   s2   4.44  False  False   3  209.549895
4  4.0   2   1  4.0  4.000040  5.55  NaN  nan   5.55    NaN   True   4  261.543588
5  5.0   1   1  5.0  5.000005  7.77   s5   s5   7.77  False  False   5  309.825075
6  NaN   0   0  6.0  6.000001  9.99   s6   s6   9.99   True   True   6  358.233033
7  7.0  -1  -1  7.0  7.000000  0.01   s7   s7   0.01    NaN   True   7  411.395191
8  8.0  -2  -2  8.0  8.000000 -0.01   s8   s8  -0.01  False  False   8  459.287144
9  9.0  -3  -3  9.0  9.000000 -1.11   s9   s9  -1.11   True   True   9  510.620955

----------------------------------------
False
0    False
1    False
2    False
3    False
4    False
5    False
6     True
7    False
8    False
9    False
Name: ii, dtype: bool
0    False
1    False
2    False
3    False
4    False
5    False
6     True
7    False
8    False
9    False
dtype: bool
0    False
1    False
2    False
3    False
4    False
5    False
6     True
7    False
8    False
9    False
dtype: bool
0    False
1    False
2    False
3     True
4    False
5    False
6     True
7    False
8    False
9    False
dtype: bool
0    False
1    False
2    False
3     True
4    False
5    False
6     True
7    False
8    False
9    False
dtype: bool
0    False
1    False
2    False
3     True
4    False
5    False
6     True
7    False
8    False
9    False
dtype: bool
0    False
1    False
2    False
3     True
4     True
5    False
6     True
7    False
8    False
9    False
dtype: bool
0    False
1    False
2    False
3     True
4     True
5    False
6     True
7    False
8    False
9    False
dtype: bool
0    False
1    False
2    False
3     True
4     True
5    False
6     True
7    False
8    False
9    False
dtype: bool
0    False
1    False
2    False
3     True
4     True
5    False
6     True
7     True
8    False
9    False
dtype: bool
0    False
1    False
2    False
3     True
4     True
5    False
6     True
7     True
8    False
9    False
dtype: bool
0    False
1    False
2    False
3     True
4     True
5    False
6     True
7     True
8    False
9    False
dtype: bool

    ii  i1  i2   ff        f1    f2   ss   s1    s2     bb     b1  xx          yy
3  3.0   3   4  NaN  3.000300  4.44   汽车   s2  4.44  False  False   3  209.549895
4  4.0   2   1  4.0  4.000040  5.55  NaN  nan  5.55    NaN   True   4  261.543588
6  NaN   0   0  6.0  6.000001  9.99   s6   s6  9.99   True   True   6  358.233033
7  7.0  -1  -1  7.0  7.000000  0.01   s7   s7  0.01    NaN   True   7  411.395191

### -------------------- Question 4 --------------------

Show how to substitute for null values 
- in a column 
- in the whole dataframe

#### Answer

In [53]:
# IN COLUMN
aa = ddd()
display(aa)
aa['ss'] = aa.ss.fillna('hello')
#          aa.ss.fillna(0)
#          aa.ss.fillna('-')
display(aa)
print('-'*40)

# IN ENTIRE DATAFRAME
aa = ddd()
aa.fillna(0, inplace=True)
display(aa)

    ii  i1  i2   ff        f1    f2   ss   s1     s2     bb     b1  xx          yy
0  0.0   6   6  0.0  0.000000  1.11   s0   s0   1.11   True   True   0   59.509449
1  1.0   5   5  1.0  1.010000  2.22   s1   s1   2.22  False  False   1  108.583535
2  2.0   4   4  2.0  2.002000  3.33    狗   s2   3.33   True   True   2  160.232588
3  3.0   3   4  NaN  3.000300  4.44   汽车   s2   4.44  False  False   3  212.162370
4  4.0   2   1  4.0  4.000040  5.55  NaN  nan   5.55    NaN   True   4  259.296264
5  5.0   1   1  5.0  5.000005  7.77   s5   s5   7.77  False  False   5  309.296272
6  NaN   0   0  6.0  6.000001  9.99   s6   s6   9.99   True   True   6  360.811639
7  7.0  -1  -1  7.0  7.000000  0.01   s7   s7   0.01    NaN   True   7  410.684245
8  8.0  -2  -2  8.0  8.000000 -0.01   s8   s8  -0.01  False  False   8  458.661569
9  9.0  -3  -3  9.0  9.000000 -1.11   s9   s9  -1.11   True   True   9  511.880710

    ii  i1  i2   ff        f1    f2     ss   s1     s2     bb     b1  xx          yy
0  0.0   6   6  0.0  0.000000  1.11     s0   s0   1.11   True   True   0   59.509449
1  1.0   5   5  1.0  1.010000  2.22     s1   s1   2.22  False  False   1  108.583535
2  2.0   4   4  2.0  2.002000  3.33      狗   s2   3.33   True   True   2  160.232588
3  3.0   3   4  NaN  3.000300  4.44     汽车   s2   4.44  False  False   3  212.162370
4  4.0   2   1  4.0  4.000040  5.55  hello  nan   5.55    NaN   True   4  259.296264
5  5.0   1   1  5.0  5.000005  7.77     s5   s5   7.77  False  False   5  309.296272
6  NaN   0   0  6.0  6.000001  9.99     s6   s6   9.99   True   True   6  360.811639
7  7.0  -1  -1  7.0  7.000000  0.01     s7   s7   0.01    NaN   True   7  410.684245
8  8.0  -2  -2  8.0  8.000000 -0.01     s8   s8  -0.01  False  False   8  458.661569
9  9.0  -3  -3  9.0  9.000000 -1.11     s9   s9  -1.11   True   True   9  511.880710

----------------------------------------

    ii  i1  i2   ff        f1    f2  ss   s1     s2     bb     b1  xx          yy
0  0.0   6   6  0.0  0.000000  1.11  s0   s0   1.11   True   True   0   61.328141
1  1.0   5   5  1.0  1.010000  2.22  s1   s1   2.22  False  False   1  109.651309
2  2.0   4   4  2.0  2.002000  3.33   狗   s2   3.33   True   True   2  159.446878
3  3.0   3   4  0.0  3.000300  4.44  汽车   s2   4.44  False  False   3  210.502386
4  4.0   2   1  4.0  4.000040  5.55   0  nan   5.55      0   True   4  261.544168
5  5.0   1   1  5.0  5.000005  7.77  s5   s5   7.77  False  False   5  309.425736
6  0.0   0   0  6.0  6.000001  9.99  s6   s6   9.99   True   True   6  360.890545
7  7.0  -1  -1  7.0  7.000000  0.01  s7   s7   0.01      0   True   7  409.024325
8  8.0  -2  -2  8.0  8.000000 -0.01  s8   s8  -0.01  False  False   8  460.936867
9  9.0  -3  -3  9.0  9.000000 -1.11  s9   s9  -1.11   True   True   9  510.041276

### -------------------- Question 5 --------------------

Can an integer column in pandas DataFrame have a NaN value?

#### Answer

```
No. Float column can.
If you insert a NaN value into integer column, 
the column type will be changed to float64
```

In [8]:
aa = ddd()
display(aa)
print(aa.i1.dtype)
aa.loc[1,'i1'] = np.NaN
print(aa.i1.dtype)
display(aa)

    ii  i1  i2   ff        f1    f2   ss   s1     s2     bb     b1  xx          yy
0  0.0   6   6  0.0  0.000000  1.11   s0   s0   1.11   True   True   0   59.176624
1  1.0   5   5  1.0  1.010000  2.22   s1   s1   2.22  False  False   1  111.065150
2  2.0   4   4  2.0  2.002000  3.33    狗   s2   3.33   True   True   2  161.599625
3  3.0   3   4  NaN  3.000300  4.44   汽车   s2   4.44  False  False   3  209.677101
4  4.0   2   1  4.0  4.000040  5.55  NaN  nan   5.55    NaN   True   4  258.198532
5  5.0   1   1  5.0  5.000005  7.77   s5   s5   7.77  False  False   5  310.117072
6  NaN   0   0  6.0  6.000001  9.99   s6   s6   9.99   True   True   6  360.600666
7  7.0  -1  -1  7.0  7.000000  0.01   s7   s7   0.01    NaN   True   7  409.056941
8  8.0  -2  -2  8.0  8.000000 -0.01   s8   s8  -0.01  False  False   8  461.289384
9  9.0  -3  -3  9.0  9.000000 -1.11   s9   s9  -1.11   True   True   9  507.972834

int64
float64

    ii   i1  i2   ff        f1    f2   ss   s1     s2     bb     b1  xx          yy
0  0.0  6.0   6  0.0  0.000000  1.11   s0   s0   1.11   True   True   0   59.176624
1  1.0  NaN   5  1.0  1.010000  2.22   s1   s1   2.22  False  False   1  111.065150
2  2.0  4.0   4  2.0  2.002000  3.33    狗   s2   3.33   True   True   2  161.599625
3  3.0  3.0   4  NaN  3.000300  4.44   汽车   s2   4.44  False  False   3  209.677101
4  4.0  2.0   1  4.0  4.000040  5.55  NaN  nan   5.55    NaN   True   4  258.198532
5  5.0  1.0   1  5.0  5.000005  7.77   s5   s5   7.77  False  False   5  310.117072
6  NaN  0.0   0  6.0  6.000001  9.99   s6   s6   9.99   True   True   6  360.600666
7  7.0 -1.0  -1  7.0  7.000000  0.01   s7   s7   0.01    NaN   True   7  409.056941
8  8.0 -2.0  -2  8.0  8.000000 -0.01   s8   s8  -0.01  False  False   8  461.289384
9  9.0 -3.0  -3  9.0  9.000000 -1.11   s9   s9  -1.11   True   True   9  507.972834

### -------------------- Question 6 --------------------

Show how to convert value type of a column to int64 or float64

#### Answer

In [58]:
aa = ddd()
display(aa)
print(aa.i1.dtype)
aa['i1'] = aa.i1.astype(np.float64)
print(aa.i1.dtype)
display(aa)
aa['i1'] = aa.i1.astype(np.int64)
print(aa.i1.dtype)
display(aa)

    ii  i1  i2   ff        f1    f2   ss   s1     s2     bb     b1  xx          yy
0  0.0   6   6  0.0  0.000000  1.11   s0   s0   1.11   True   True   0   59.534173
1  1.0   5   5  1.0  1.010000  2.22   s1   s1   2.22  False  False   1  109.544821
2  2.0   4   4  2.0  2.002000  3.33    狗   s2   3.33   True   True   2  161.000153
3  3.0   3   4  NaN  3.000300  4.44   汽车   s2   4.44  False  False   3  209.278505
4  4.0   2   1  4.0  4.000040  5.55  NaN  nan   5.55    NaN   True   4  259.778781
5  5.0   1   1  5.0  5.000005  7.77   s5   s5   7.77  False  False   5  312.221307
6  NaN   0   0  6.0  6.000001  9.99   s6   s6   9.99   True   True   6  359.674662
7  7.0  -1  -1  7.0  7.000000  0.01   s7   s7   0.01    NaN   True   7  409.241357
8  8.0  -2  -2  8.0  8.000000 -0.01   s8   s8  -0.01  False  False   8  458.165060
9  9.0  -3  -3  9.0  9.000000 -1.11   s9   s9  -1.11   True   True   9  508.892297

int64
float64

    ii   i1  i2   ff        f1    f2   ss   s1     s2     bb     b1  xx          yy
0  0.0  6.0   6  0.0  0.000000  1.11   s0   s0   1.11   True   True   0   59.534173
1  1.0  5.0   5  1.0  1.010000  2.22   s1   s1   2.22  False  False   1  109.544821
2  2.0  4.0   4  2.0  2.002000  3.33    狗   s2   3.33   True   True   2  161.000153
3  3.0  3.0   4  NaN  3.000300  4.44   汽车   s2   4.44  False  False   3  209.278505
4  4.0  2.0   1  4.0  4.000040  5.55  NaN  nan   5.55    NaN   True   4  259.778781
5  5.0  1.0   1  5.0  5.000005  7.77   s5   s5   7.77  False  False   5  312.221307
6  NaN  0.0   0  6.0  6.000001  9.99   s6   s6   9.99   True   True   6  359.674662
7  7.0 -1.0  -1  7.0  7.000000  0.01   s7   s7   0.01    NaN   True   7  409.241357
8  8.0 -2.0  -2  8.0  8.000000 -0.01   s8   s8  -0.01  False  False   8  458.165060
9  9.0 -3.0  -3  9.0  9.000000 -1.11   s9   s9  -1.11   True   True   9  508.892297

int64

    ii  i1  i2   ff        f1    f2   ss   s1     s2     bb     b1  xx          yy
0  0.0   6   6  0.0  0.000000  1.11   s0   s0   1.11   True   True   0   59.534173
1  1.0   5   5  1.0  1.010000  2.22   s1   s1   2.22  False  False   1  109.544821
2  2.0   4   4  2.0  2.002000  3.33    狗   s2   3.33   True   True   2  161.000153
3  3.0   3   4  NaN  3.000300  4.44   汽车   s2   4.44  False  False   3  209.278505
4  4.0   2   1  4.0  4.000040  5.55  NaN  nan   5.55    NaN   True   4  259.778781
5  5.0   1   1  5.0  5.000005  7.77   s5   s5   7.77  False  False   5  312.221307
6  NaN   0   0  6.0  6.000001  9.99   s6   s6   9.99   True   True   6  359.674662
7  7.0  -1  -1  7.0  7.000000  0.01   s7   s7   0.01    NaN   True   7  409.241357
8  8.0  -2  -2  8.0  8.000000 -0.01   s8   s8  -0.01  False  False   8  458.165060
9  9.0  -3  -3  9.0  9.000000 -1.11   s9   s9  -1.11   True   True   9  508.892297

### -------------------- Question 7 (Exercise) --------------------

Do the following:
- Take first several rows for a dataframe (regardless of index)
- Take last several rows of a dataframe (regardless of index)
- Take group of rows in the middle (regardless of index)
- Take one row as a list (first / last / middle)

#### Answer

In [10]:
print("first rows as dataframe")
aa = ddd()
print(aa.head())  # by default takes up to 5 rows
print('-'*40)
print(aa.head(2)) 
print('-'*40)
print(aa[:3]) # slice - same as .head(3)
print('-'*40)
print("last rows as dataframe")
print(aa.tail())
print('-'*40)
print(aa[-5:])
print('-'*40)

print("rows in the middle as dataframe")
print(aa[2:4])

print("Take one row as a list (first / last / middle)")
print(aa.loc[aa.index[0]].tolist())
print(aa.loc[aa.index[-1]].tolist())
print(aa.loc[aa.index[3]].tolist())

first rows as dataframe
    ii  i1  i2   ff       f1    f2   ss   s1    s2     bb     b1  xx          yy
0  0.0   6   6  0.0  0.00000  1.11   s0   s0  1.11   True   True   0   59.754204
1  1.0   5   5  1.0  1.01000  2.22   s1   s1  2.22  False  False   1  110.351935
2  2.0   4   4  2.0  2.00200  3.33    狗   s2  3.33   True   True   2  161.378273
3  3.0   3   4  NaN  3.00030  4.44   汽车   s2  4.44  False  False   3  211.010980
4  4.0   2   1  4.0  4.00004  5.55  NaN  nan  5.55    NaN   True   4  260.611136
----------------------------------------
    ii  i1  i2   ff    f1    f2  ss  s1    s2     bb     b1  xx          yy
0  0.0   6   6  0.0  0.00  1.11  s0  s0  1.11   True   True   0   59.754204
1  1.0   5   5  1.0  1.01  2.22  s1  s1  2.22  False  False   1  110.351935
----------------------------------------
    ii  i1  i2   ff     f1    f2  ss  s1    s2     bb     b1  xx          yy
0  0.0   6   6  0.0  0.000  1.11  s0  s0  1.11   True   True   0   59.754204
1  1.0   5   5  1.0  1.010  2.22  s1  s1  2.22  False  False   1  110.351935
2  2.0   4   4  2.0  2.002  3.33   狗  s2  3.33   True   True   2  161.378273
----------------------------------------
last rows as dataframe
    ii  i1  i2   ff        f1    f2  ss  s1     s2     bb     b1  xx          yy
5  5.0   1   1  5.0  5.000005  7.77  s5  s5   7.77  False  False   5  310.102179
6  NaN   0   0  6.0  6.000001  9.99  s6  s6   9.99   True   True   6  360.407825
7  7.0  -1  -1  7.0  7.000000  0.01  s7  s7   0.01    NaN   True   7  409.334871
8  8.0  -2  -2  8.0  8.000000 -0.01  s8  s8  -0.01  False  False   8  460.352302
9  9.0  -3  -3  9.0  9.000000 -1.11  s9  s9  -1.11   True   True   9  511.352780
----------------------------------------
    ii  i1  i2   ff        f1    f2  ss  s1     s2     bb     b1  xx          yy
5  5.0   1   1  5.0  5.000005  7.77  s5  s5   7.77  False  False   5  310.102179
6  NaN   0   0  6.0  6.000001  9.99  s6  s6   9.99   True   True   6  360.407825
7  7.0  -1  -1  7.0  7.000000  0.01  s7  s7   0.01    NaN   True   7  409.334871
8  8.0  -2  -2  8.0  8.000000 -0.01  s8  s8  -0.01  False  False   8  460.352302
9  9.0  -3  -3  9.0  9.000000 -1.11  s9  s9  -1.11   True   True   9  511.352780
----------------------------------------
rows in the middle as dataframe
    ii  i1  i2   ff      f1    f2  ss  s1    s2     bb     b1  xx          yy
2  2.0   4   4  2.0  2.0020  3.33   狗  s2  3.33   True   True   2  161.378273
3  3.0   3   4  NaN  3.0003  4.44  汽车  s2  4.44  False  False   3  211.010980
Take one row as a list (first / last / middle)
[0.0, 6, 6, 0.0, 0.0, 1.11, 's0', 's0', '1.11', True, True, 0, 59.754203750106264]
[9.0, -3, -3, 9.0, 9.0, -1.11, 's9', 's9', '-1.11', True, True, 9, 511.3527796662196]
[3.0, 3, 4, nan, 3.0003, 4.44, '汽车', 's2', '4.44', False, False, 3, 211.01098037722284]

### -------------------- Question 8 --------------------

Show how to take the first row of a DataFrame as a list or dict

#### Answer

In [59]:
aa = ddd()
#aa.index = [6,5,4,3,2,1,0]
display(aa)
mylist = aa.loc[aa.index[0]].tolist()
mydict = aa.loc[aa.index[4]].to_dict()
print(mylist)
print(mydict)

    ii  i1  i2   ff        f1    f2   ss   s1     s2     bb     b1  xx          yy
0  0.0   6   6  0.0  0.000000  1.11   s0   s0   1.11   True   True   0   60.962326
1  1.0   5   5  1.0  1.010000  2.22   s1   s1   2.22  False  False   1  109.699184
2  2.0   4   4  2.0  2.002000  3.33    狗   s2   3.33   True   True   2  161.301707
3  3.0   3   4  NaN  3.000300  4.44   汽车   s2   4.44  False  False   3  211.035736
4  4.0   2   1  4.0  4.000040  5.55  NaN  nan   5.55    NaN   True   4  260.478174
5  5.0   1   1  5.0  5.000005  7.77   s5   s5   7.77  False  False   5  309.815864
6  NaN   0   0  6.0  6.000001  9.99   s6   s6   9.99   True   True   6  358.625458
7  7.0  -1  -1  7.0  7.000000  0.01   s7   s7   0.01    NaN   True   7  410.327381
8  8.0  -2  -2  8.0  8.000000 -0.01   s8   s8  -0.01  False  False   8  459.055550
9  9.0  -3  -3  9.0  9.000000 -1.11   s9   s9  -1.11   True   True   9  508.329729

[0.0, 6, 6, 0.0, 0.0, 1.11, 's0', 's0', '1.11', True, True, 0, 60.9623258912277]
{'ii': 4.0, 'i1': 2, 'i2': 1, 'ff': 4.0, 'f1': 4.00004, 'f2': 5.55, 'ss': nan, 's1': 'nan', 's2': '5.55', 'bb': nan, 'b1': True, 'xx': 4, 'yy': 260.4781743782018}

### -------------------- Question 9 --------------------

Show the following ways of combining two pandas DataFrames
- merge
- append
- concat
- combine_first

#### Answer

In [12]:
# Pandas DataFrames are similar to SQL database tables.
# they can be joined using two mechanisms: join() and merge()
# join() does joining on indexes, merge() - on columns
# I usually use merge()
#
# df_joined = merge(df1, df2, on=[columns], how='inner')
# df_joined = merge(df1, df2, on=[columns], how='left')


# This is exactly like joining 2 tables in SQL
# you can use inner join ('inner') or left outer join ('left')

In [13]:
# append allows to append two DataFrames vertically one on top of another
# 
df = aa.append(bb,ignore_index=True)
display(df)

     ii  i1  i2   ff        f1    f2   ss   s1     s2     bb     b1  xx          yy
0   0.0   6   6  0.0  0.000000  1.11   s0   s0   1.11   True   True   0   60.893387
1   1.0   5   5  1.0  1.010000  2.22   s1   s1   2.22  False  False   1  111.783977
2   2.0   4   4  2.0  2.002000  3.33    狗   s2   3.33   True   True   2  158.515781
3   3.0   3   4  NaN  3.000300  4.44   汽车   s2   4.44  False  False   3  208.546035
4   4.0   2   1  4.0  4.000040  5.55  NaN  nan   5.55    NaN   True   4  260.079489
5   5.0   1   1  5.0  5.000005  7.77   s5   s5   7.77  False  False   5  310.245125
6   NaN   0   0  6.0  6.000001  9.99   s6   s6   9.99   True   True   6  359.007239
7   7.0  -1  -1  7.0  7.000000  0.01   s7   s7   0.01    NaN   True   7  411.273457
8   8.0  -2  -2  8.0  8.000000 -0.01   s8   s8  -0.01  False  False   8  459.628502
9   9.0  -3  -3  9.0  9.000000 -1.11   s9   s9  -1.11   True   True   9  508.327580
10  3.0   3   4  NaN  3.000300  4.44   汽车   s2   4.44  False  False   3  209.533875
11  4.0   2   1  4.0  4.000040  5.55  NaN  nan   5.55    NaN   True   4  261.406502
12  NaN   0   0  6.0  6.000001  9.99   s6   s6   9.99   True   True   6  360.166691
13  7.0  -1  -1  7.0  7.000000  0.01   s7   s7   0.01    NaN   True   7  411.613357

In [14]:
# concat() allows to stack DataFrames vertically (default) or horizontally
#   concat([s1,s2,s3])      - stacks together objects along an axis (vertically)
#   concat([aa,bb],axis=1) - stacking horizontally

In [15]:
aa = ddd()
bb = ddd()
display(aa)
cc = pd.merge(aa, bb, on='i2')
display(cc)
# pd.merge?

    ii  i1  i2   ff        f1    f2   ss   s1     s2     bb     b1  xx          yy
0  0.0   6   6  0.0  0.000000  1.11   s0   s0   1.11   True   True   0   59.213787
1  1.0   5   5  1.0  1.010000  2.22   s1   s1   2.22  False  False   1  109.404442
2  2.0   4   4  2.0  2.002000  3.33    狗   s2   3.33   True   True   2  161.753045
3  3.0   3   4  NaN  3.000300  4.44   汽车   s2   4.44  False  False   3  211.670273
4  4.0   2   1  4.0  4.000040  5.55  NaN  nan   5.55    NaN   True   4  257.754038
5  5.0   1   1  5.0  5.000005  7.77   s5   s5   7.77  False  False   5  308.943908
6  NaN   0   0  6.0  6.000001  9.99   s6   s6   9.99   True   True   6  360.124415
7  7.0  -1  -1  7.0  7.000000  0.01   s7   s7   0.01    NaN   True   7  410.258917
8  8.0  -2  -2  8.0  8.000000 -0.01   s8   s8  -0.01  False  False   8  460.680413
9  9.0  -3  -3  9.0  9.000000 -1.11   s9   s9  -1.11   True   True   9  510.504730

    ii_x  i1_x  i2  ff_x      f1_x  f2_x ss_x s1_x   s2_x   bb_x  ...  ff_y      f1_y  f2_y  ss_y  s1_y   s2_y   bb_y   b1_y xx_y        yy_y
0    0.0     6   6   0.0  0.000000  1.11   s0   s0   1.11   True  ...   0.0  0.000000  1.11    s0    s0   1.11   True   True    0   59.489951
1    1.0     5   5   1.0  1.010000  2.22   s1   s1   2.22  False  ...   1.0  1.010000  2.22    s1    s1   2.22  False  False    1  110.858145
2    2.0     4   4   2.0  2.002000  3.33    狗   s2   3.33   True  ...   2.0  2.002000  3.33     狗    s2   3.33   True   True    2  160.955997
3    2.0     4   4   2.0  2.002000  3.33    狗   s2   3.33   True  ...   NaN  3.000300  4.44    汽车    s2   4.44  False  False    3  210.149333
4    3.0     3   4   NaN  3.000300  4.44   汽车   s2   4.44  False  ...   2.0  2.002000  3.33     狗    s2   3.33   True   True    2  160.955997
5    3.0     3   4   NaN  3.000300  4.44   汽车   s2   4.44  False  ...   NaN  3.000300  4.44    汽车    s2   4.44  False  False    3  210.149333
6    4.0     2   1   4.0  4.000040  5.55  NaN  nan   5.55    NaN  ...   4.0  4.000040  5.55   NaN   nan   5.55    NaN   True    4  258.920980
7    4.0     2   1   4.0  4.000040  5.55  NaN  nan   5.55    NaN  ...   5.0  5.000005  7.77    s5    s5   7.77  False  False    5  310.770765
8    5.0     1   1   5.0  5.000005  7.77   s5   s5   7.77  False  ...   4.0  4.000040  5.55   NaN   nan   5.55    NaN   True    4  258.920980
9    5.0     1   1   5.0  5.000005  7.77   s5   s5   7.77  False  ...   5.0  5.000005  7.77    s5    s5   7.77  False  False    5  310.770765
10   NaN     0   0   6.0  6.000001  9.99   s6   s6   9.99   True  ...   6.0  6.000001  9.99    s6    s6   9.99   True   True    6  360.685029
11   7.0    -1  -1   7.0  7.000000  0.01   s7   s7   0.01    NaN  ...   7.0  7.000000  0.01    s7    s7   0.01    NaN   True    7  409.636744
12   8.0    -2  -2   8.0  8.000000 -0.01   s8   s8  -0.01  False  ...   8.0  8.000000 -0.01    s8    s8  -0.01  False  False    8  460.064456
13   9.0    -3  -3   9.0  9.000000 -1.11   s9   s9  -1.11   True  ...   9.0  9.000000 -1.11    s9    s9  -1.11   True   True    9  509.760075

[14 rows x 25 columns]

In [16]:
# df1.combine_first(df2)
#   Combine two DataFrames
#   uses df2 to fill-in null values in df1

df1 = pd.DataFrame([[1, np.nan]])
df2 = pd.DataFrame([[3, 4]])
aa = df1.combine_first(df2)
display(df1)
print('---------')
display(df2)
print('---------')
display(aa)

   0   1
0  1 NaN

---------

   0  1
0  3  4

---------

   0    1
0  1  4.0

### -------------------- Question 10 --------------------

Show the following:
- pandas stack()/unstack() functions
- grouping by mask

#### Answer

In [62]:
xx = pd.DataFrame(
    [ ["Jan","name1",1,2,3],   
      ["Jan","name2",4,5,6],
      ["Mar","name1",11,12,13],
      ["Mar","name2",14,15,16] 
    ],
    columns=["Month","Name","c1","c2","c3"])

display(xx)
print('-----------------------------')
# convert Month and Name into index
yy = xx.set_index(["Month","Name"])
display(yy)
print('-----------------------------')
# Stack all remaining columns (c1,c2,c3) - make a one-column Series
yy = xx.set_index(["Month","Name"]).stack()
display(yy)
print('-----------------------------')
# Unstack column "Month" - values will become columns
yy = xx.set_index(["Month","Name"]).stack().unstack('Month')
display(yy)
print('-----------------------------')

  Month   Name  c1  c2  c3
0   Jan  name1   1   2   3
1   Jan  name2   4   5   6
2   Mar  name1  11  12  13
3   Mar  name2  14  15  16

-----------------------------

             c1  c2  c3
Month Name
Jan   name1   1   2   3
      name2   4   5   6
Mar   name1  11  12  13
      name2  14  15  16

-----------------------------

Month  Name
Jan    name1  c1     1
              c2     2
              c3     3
       name2  c1     4
              c2     5
              c3     6
Mar    name1  c1    11
              c2    12
              c3    13
       name2  c1    14
              c2    15
              c3    16
dtype: int64

-----------------------------

Month     Jan  Mar
Name
name1 c1    1   11
      c2    2   12
      c3    3   13
name2 c1    4   14
      c2    5   15
      c3    6   16

-----------------------------

In [63]:
# grouping by mask
mask = yy.Jan > 3
zz = yy.groupby(by=mask).sum()
display(zz)

Month  Jan  Mar
Jan
False    6   36
True    15   45

### -------------------- Question 11 --------------------

Show use of pandas DataFrame.pivot()

#### Answer

In [18]:
aa = pd.DataFrame(
    { 'foo' : 3*['one'] + 3*['two'],
      'bar' : 2*['A','B','C'],
      'baz' : [1,2,3,4,5,6]
    }
)

aa = aa[['foo','bar','baz']]
display(aa)
print("---------------")
#       foo bar  baz
#    0  one   A    1
#    1  one   B    2
#    2  one   C    3
#    3  two   A    4
#    4  two   B    5
#    5  two   C    6

display(aa.pivot('foo','bar','baz'))
print("---------------")
display(aa.pivot('foo', 'bar')['baz'])

   foo bar  baz
0  one   A    1
1  one   B    2
2  one   C    3
3  two   A    4
4  two   B    5
5  two   C    6

---------------

bar  A  B  C
foo
one  1  2  3
two  4  5  6

---------------

bar  A  B  C
foo
one  1  2  3
two  4  5  6

### -------------------- Question 12 --------------------

Create a pandas DataFrame and populate with data
- from dict of columns,
- from list
- from numpy array
- from list of series
- from list of lists

#### Answer

In [69]:
df = pd.DataFrame({
    'x'  : 3 * ['a'] + 2 * ['b'],
    'nn' : np.arange(5, dtype=np.float64), 
    'y'  : np.random.rand(5),
    'z'  : range(5)
})

# -------------------------------------------------------
df = pd.DataFrame([[1,2,3]], columns=['A','B','C'])
#   A B C
# 0 1 2 3

# -------------------------------------------------------
df = pd.DataFrame(
    np.arange(12).reshape((3,4)),
    index = ['A','B','C'],
    columns = ['AA','BB','CC','DD']
)

#    AA  BB  CC  DD
# A   0   1   2   3
# B   4   5   6   7
# C   8   9  10  11

# display(df)
# print(df)

# -------------------------------------------------------
nrows  = 10
ncols  =  5
mydata = np.random.rand(nrows, ncols)
#mydata = np.random.randn(nrows, ncols)

aa = pd.DataFrame(data=mydata)
# -------------------------------------------------------
aa = pd.DataFrame(data=mydata, 
                  index=range(nrows), 
                  columns=[chr(65+x)*2 for x in range(ncols)])
# -------------------------------------------------------
aa = pd.DataFrame( np.random.normal(size=12).reshape((3,4)), 
                   index = ['A','B','C'], 
                   columns = ['AA','BB','CC','DD'] )
# -------------------------------------------------------
s1 = pd.Series({'x':1,'y':2})
s2 = pd.Series({'x':3,'y':4})
aa = pd.DataFrame([s1,s2])   # s1 and s2 - rows
#    x  y
# 0  1  2
# 1  3  4
# -------------------------------------------------------
mydata = [[1,2],[3,4],[5,6]]
aa = pd.DataFrame(mydata, columns=['AA','BB'])
#    AA  BB
# 0   1   2
# 1   3   4
# 2   5   6

### -------------------- Question 13 --------------------

Generate random numbers to populate a DataFrame
<br>use Numpy  np.random

#### Answer

In [20]:
# np.random.<TAB>
# np.random.seed(int)
Ncols = 4
Nrows = 5

# several ways to generate numbers
data = np.random.rand(Nrows, Ncols)
data = np.random.randn(Nrows, Ncols)
data = np.random.normal(size=Nrows*Ncols).reshape(Nrows,Ncols)
data = np.random.normal(size=Nrows*Ncols, loc=10.0, scale=1.0).reshape(Nrows,Ncols)

aa = pd.DataFrame(data, columns = ['c1','c2','c3','c4'] )
print(aa)

          c1         c2         c3         c4
0  10.607392  11.997504   9.787119  10.107880
1  10.643957  10.428765   9.467504   9.291963
2  12.002384   9.243630   8.477588  11.250811
3  10.751122  11.529113  11.301866  10.549605
4   9.979983  11.713888   9.885746  11.047864

## -------------------- Question 13a --------------------

transform a row using flexible 
    custom function operating on all columns

In [21]:
list(range(4,-1,-1))

[4, 3, 2, 1, 0]

In [22]:
df = pd.DataFrame({'aa':range(5), 'bb':range(5)})
print(df) # 5 rows
print('-'*40)

   aa  bb
0   0   0
1   1   1
2   2   2
3   3   3
4   4   4
----------------------------------------

In [23]:
# ------------------------------------
def myfunc(df):
    """ This function is applied to a subset (groupping) of rows"""
    df['lev'] = df['aa'].map(lambda x: str(x**2)) + '_' + df['bb'].map(lambda x: str(x**2))
    df['bb'] = df.bb**3
    return df

df2 = df.groupby(df.bb, as_index=False).apply(myfunc)
print(df2)

   aa  bb    lev
0   0   0    0_0
1   1   1    1_1
2   2   8    4_4
3   3  27    9_9
4   4  64  16_16

### -------------------- Question 14 --------------------

Show how to iterate through rows of pandas DataFrame

#### Answer

In [24]:
aa=ddd()
for rr in aa.itertuples(): 
    print(rr)

print('-'*40)
for rr in aa.itertuples(index=False): 
    print(rr)

# pd.DataFrame.iterrows()  - a generator
#     yields tuple (index, row_as_Series)
#     Slow, because needs to create a Series from each row.
  
print('-'*40)
for row in aa.iterrows():
    ind = row[0]
    ser = row[1]
    cols = list(ser.index)
    vals = list(ser)
    print("ind = ",ind,", vals = ",vals)

print('-'*40)
for row in aa.iterrows():
    print(row[1].values)
print('-'*40)
for row in aa.iterrows():
    print(list(row[1].values))

# Another way:
# for ii in aa.index: 
#     do_something(aa.loc[ii])

Pandas(Index=0, ii=0.0, i1=6, i2=6, ff=0.0, f1=0.0, f2=1.11, ss='s0', s1='s0', s2='1.11', bb=True, b1=True, xx=0, yy=59.57966522287072)
Pandas(Index=1, ii=1.0, i1=5, i2=5, ff=1.0, f1=1.01, f2=2.22, ss='s1', s1='s1', s2='2.22', bb=False, b1=False, xx=1, yy=109.94828772638684)
Pandas(Index=2, ii=2.0, i1=4, i2=4, ff=2.0, f1=2.002, f2=3.33, ss='狗', s1='s2', s2='3.33', bb=True, b1=True, xx=2, yy=160.53794264788507)
Pandas(Index=3, ii=3.0, i1=3, i2=4, ff=nan, f1=3.0003, f2=4.44, ss='汽车', s1='s2', s2='4.44', bb=False, b1=False, xx=3, yy=210.31062543515955)
Pandas(Index=4, ii=4.0, i1=2, i2=1, ff=4.0, f1=4.00004, f2=5.55, ss=nan, s1='nan', s2='5.55', bb=nan, b1=True, xx=4, yy=258.38455484369473)
Pandas(Index=5, ii=5.0, i1=1, i2=1, ff=5.0, f1=5.000005, f2=7.77, ss='s5', s1='s5', s2='7.77', bb=False, b1=False, xx=5, yy=308.91502628887264)
Pandas(Index=6, ii=nan, i1=0, i2=0, ff=6.0, f1=6.0000006, f2=9.99, ss='s6', s1='s6', s2='9.99', bb=True, b1=True, xx=6, yy=358.4634973809877)
Pandas(Index=7, ii=7.0, i1=-1, i2=-1, ff=7.0, f1=7.0, f2=0.01, ss='s7', s1='s7', s2='0.01', bb=nan, b1=True, xx=7, yy=411.90051018075303)
Pandas(Index=8, ii=8.0, i1=-2, i2=-2, ff=8.0, f1=8.0, f2=-0.01, ss='s8', s1='s8', s2='-0.01', bb=False, b1=False, xx=8, yy=460.50572390064826)
Pandas(Index=9, ii=9.0, i1=-3, i2=-3, ff=9.0, f1=9.0, f2=-1.11, ss='s9', s1='s9', s2='-1.11', bb=True, b1=True, xx=9, yy=509.53032915513927)
----------------------------------------
Pandas(ii=0.0, i1=6, i2=6, ff=0.0, f1=0.0, f2=1.11, ss='s0', s1='s0', s2='1.11', bb=True, b1=True, xx=0, yy=59.57966522287072)
Pandas(ii=1.0, i1=5, i2=5, ff=1.0, f1=1.01, f2=2.22, ss='s1', s1='s1', s2='2.22', bb=False, b1=False, xx=1, yy=109.94828772638684)
Pandas(ii=2.0, i1=4, i2=4, ff=2.0, f1=2.002, f2=3.33, ss='狗', s1='s2', s2='3.33', bb=True, b1=True, xx=2, yy=160.53794264788507)
Pandas(ii=3.0, i1=3, i2=4, ff=nan, f1=3.0003, f2=4.44, ss='汽车', s1='s2', s2='4.44', bb=False, b1=False, xx=3, yy=210.31062543515955)
Pandas(ii=4.0, i1=2, i2=1, ff=4.0, f1=4.00004, f2=5.55, ss=nan, s1='nan', s2='5.55', bb=nan, b1=True, xx=4, yy=258.38455484369473)
Pandas(ii=5.0, i1=1, i2=1, ff=5.0, f1=5.000005, f2=7.77, ss='s5', s1='s5', s2='7.77', bb=False, b1=False, xx=5, yy=308.91502628887264)
Pandas(ii=nan, i1=0, i2=0, ff=6.0, f1=6.0000006, f2=9.99, ss='s6', s1='s6', s2='9.99', bb=True, b1=True, xx=6, yy=358.4634973809877)
Pandas(ii=7.0, i1=-1, i2=-1, ff=7.0, f1=7.0, f2=0.01, ss='s7', s1='s7', s2='0.01', bb=nan, b1=True, xx=7, yy=411.90051018075303)
Pandas(ii=8.0, i1=-2, i2=-2, ff=8.0, f1=8.0, f2=-0.01, ss='s8', s1='s8', s2='-0.01', bb=False, b1=False, xx=8, yy=460.50572390064826)
Pandas(ii=9.0, i1=-3, i2=-3, ff=9.0, f1=9.0, f2=-1.11, ss='s9', s1='s9', s2='-1.11', bb=True, b1=True, xx=9, yy=509.53032915513927)
----------------------------------------
ind =  0 , vals =  [0.0, 6, 6, 0.0, 0.0, 1.11, 's0', 's0', '1.11', True, True, 0, 59.57966522287072]
ind =  1 , vals =  [1.0, 5, 5, 1.0, 1.01, 2.22, 's1', 's1', '2.22', False, False, 1, 109.94828772638684]
ind =  2 , vals =  [2.0, 4, 4, 2.0, 2.002, 3.33, '狗', 's2', '3.33', True, True, 2, 160.53794264788507]
ind =  3 , vals =  [3.0, 3, 4, nan, 3.0003, 4.44, '汽车', 's2', '4.44', False, False, 3, 210.31062543515955]
ind =  4 , vals =  [4.0, 2, 1, 4.0, 4.00004, 5.55, nan, 'nan', '5.55', nan, True, 4, 258.38455484369473]
ind =  5 , vals =  [5.0, 1, 1, 5.0, 5.000005, 7.77, 's5', 's5', '7.77', False, False, 5, 308.91502628887264]
ind =  6 , vals =  [nan, 0, 0, 6.0, 6.0000006, 9.99, 's6', 's6', '9.99', True, True, 6, 358.4634973809877]
ind =  7 , vals =  [7.0, -1, -1, 7.0, 7.0, 0.01, 's7', 's7', '0.01', nan, True, 7, 411.90051018075303]
ind =  8 , vals =  [8.0, -2, -2, 8.0, 8.0, -0.01, 's8', 's8', '-0.01', False, False, 8, 460.50572390064826]
ind =  9 , vals =  [9.0, -3, -3, 9.0, 9.0, -1.11, 's9', 's9', '-1.11', True, True, 9, 509.53032915513927]
----------------------------------------
[0.0 6 6 0.0 0.0 1.11 's0' 's0' '1.11' True True 0 59.57966522287072]
[1.0 5 5 1.0 1.01 2.22 's1' 's1' '2.22' False False 1 109.94828772638684]
[2.0 4 4 2.0 2.002 3.33 '狗' 's2' '3.33' True True 2 160.53794264788507]
[3.0 3 4 nan 3.0003 4.44 '汽车' 's2' '4.44' False False 3 210.31062543515955]
[4.0 2 1 4.0 4.00004 5.55 nan 'nan' '5.55' nan True 4 258.38455484369473]
[5.0 1 1 5.0 5.000005 7.77 's5' 's5' '7.77' False False 5
 308.91502628887264]
[nan 0 0 6.0 6.0000006 9.99 's6' 's6' '9.99' True True 6 358.4634973809877]
[7.0 -1 -1 7.0 7.0 0.01 's7' 's7' '0.01' nan True 7 411.90051018075303]
[8.0 -2 -2 8.0 8.0 -0.01 's8' 's8' '-0.01' False False 8
 460.50572390064826]
[9.0 -3 -3 9.0 9.0 -1.11 's9' 's9' '-1.11' True True 9 509.53032915513927]
----------------------------------------
[0.0, 6, 6, 0.0, 0.0, 1.11, 's0', 's0', '1.11', True, True, 0, 59.57966522287072]
[1.0, 5, 5, 1.0, 1.01, 2.22, 's1', 's1', '2.22', False, False, 1, 109.94828772638684]
[2.0, 4, 4, 2.0, 2.002, 3.33, '狗', 's2', '3.33', True, True, 2, 160.53794264788507]
[3.0, 3, 4, nan, 3.0003, 4.44, '汽车', 's2', '4.44', False, False, 3, 210.31062543515955]
[4.0, 2, 1, 4.0, 4.00004, 5.55, nan, 'nan', '5.55', nan, True, 4, 258.38455484369473]
[5.0, 1, 1, 5.0, 5.000005, 7.77, 's5', 's5', '7.77', False, False, 5, 308.91502628887264]
[nan, 0, 0, 6.0, 6.0000006, 9.99, 's6', 's6', '9.99', True, True, 6, 358.4634973809877]
[7.0, -1, -1, 7.0, 7.0, 0.01, 's7', 's7', '0.01', nan, True, 7, 411.90051018075303]
[8.0, -2, -2, 8.0, 8.0, -0.01, 's8', 's8', '-0.01', False, False, 8, 460.50572390064826]
[9.0, -3, -3, 9.0, 9.0, -1.11, 's9', 's9', '-1.11', True, True, 9, 509.53032915513927]

### -------------------- Question 15 --------------------

Show how to do string operations on columns

#### Answer

In [71]:
aa = pd.DataFrame({
    'ss':['aa1','bb2','cc3',np.nan],
    'ff':['  11.11  ','  22.22  ','  33.33  ','  44.44  '],
    'ii':['  11     ','  22     ','  33     ','  44     ']
})
display(aa)
# use str method on Series/Column:
# aa.ss.str.<TAB>
print(aa.ss.str.contains('bb'))
print('-'*40)
print(aa.ss.str[:2])   # first 2 characters
print('-'*40)
print(aa.ss.str.upper())
print('-'*40)
print(aa.ss.str.len())
print('-'*40)
# etc.

# using regular expression
mask = aa.ss.map(lambda x: True if re.search(r'b[23]',str(x)) else False)
print(mask)
print('-'*40)
# --------------------
# convert from string to number and back
# aa['zz'] = aa.ff.astype(np.int64) # error
aa['zz'] = aa.ff.map(lambda x: int(float(x)) if x==x else np.nan).astype(np.int64)
display(aa)
print('-'*40)

aa['zz'] = aa.ii.astype(np.int64) # works
display(aa.zz.dtype)
aa['zz'] = aa.ff.astype(np.float64) # works
aa['zz'] = aa.ii.astype(np.float64) # works
print(aa.zz.dtype)
aa['zz'] = aa.ii.str.strip().astype(float)
print(aa.zz.dtype)
aa['zz'] = aa.ii.str.strip().str[0].astype(int)
print(aa.zz.dtype)
aa['zz'] = aa.ff.astype(object)  # use this to work with a string
print(aa.zz.dtype)
print("~"*40)
aa['zz'] = aa.ff.astype(str)     # silent error?
print(aa['zz'])
print(aa.zz.dtype)

# mask = aa.ss.str.match(r'1|3') - doesn't work yet
# mask = aa.ss.get(label) # ??

    ss         ff         ii
0  aa1    11.11      11
1  bb2    22.22      22
2  cc3    33.33      33
3  NaN    44.44      44

0    False
1     True
2    False
3      NaN
Name: ss, dtype: object
----------------------------------------
0     aa
1     bb
2     cc
3    NaN
Name: ss, dtype: object
----------------------------------------
0    AA1
1    BB2
2    CC3
3    NaN
Name: ss, dtype: object
----------------------------------------
0    3.0
1    3.0
2    3.0
3    NaN
Name: ss, dtype: float64
----------------------------------------
0    False
1     True
2    False
3    False
Name: ss, dtype: bool
----------------------------------------

    ss         ff         ii  zz
0  aa1    11.11      11       11
1  bb2    22.22      22       22
2  cc3    33.33      33       33
3  NaN    44.44      44       44

----------------------------------------

dtype('int64')

float64
float64
int64
object
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
0      11.11
1      22.22
2      33.33
3      44.44
Name: zz, dtype: object
object

### -------------------- Question 16 --------------------

Make a histogram (cutting data into bins) from DataFrame

#### Answer

In [26]:
aa=np.random.normal(size=100)
print(aa)
bins=[-3, -2.5, -2, -1.5, -1, -0.5, 0, 0.5, 1, 1.5, 2, 2.5, 3]
vals = pd.cut(aa,bins)
pd.value_counts(vals)

# also look at pd.qcut

[ 0.4866515   0.82599944  1.00694779  1.55477905 -1.03850381  0.62042546
 -1.3443649  -0.63274914  0.2252523   2.46295547 -0.81633296  0.27424954
  0.04942263 -0.21832698  0.42000284  0.5696221   1.32109517 -0.5514184
 -0.33003969 -0.57471708  1.67749561  2.10590807 -1.02213969 -0.0709277
  0.33981484 -0.6162469   0.68408902  0.16312476  0.72801893  0.02553748
  1.21684091  2.0433738  -2.06704102  0.66874899  0.67163962 -0.36490457
  0.53309608  1.80971896  0.15561228 -0.91368766 -0.19502104  1.77787697
 -1.17593766 -0.66826773 -0.53528437  1.52851798  0.09751279 -0.59163029
  0.72349054  1.1525893   0.55895097  0.46281217  0.13117817 -0.09886429
  1.81343711 -0.5433069   1.87390274 -1.41584407  1.52561023 -1.04386686
  1.39604343  0.2973104  -0.47353233  0.84161694 -1.65164042 -0.35410304
 -2.22981483 -0.44876239 -0.39160147 -0.93637846 -1.27550497  1.06929159
 -0.37709038  0.76705303 -0.98240804 -1.02586845 -0.58661832 -0.77897811
 -0.17849927  1.4266176  -0.71256336 -0.99988971  0.99117963 -0.94302036
  1.96645176  1.34130831 -0.97644851 -0.10080941  0.9989896   0.64943151
 -0.07981501 -0.51708088 -2.25008122  0.70465014  0.42299459 -1.43365076
 -0.56880033 -0.36898212 -0.96868722 -0.64260311]

(-1.0, -0.5]    22
(0.5, 1.0]      16
(-0.5, 0.0]     15
(0.0, 0.5]      14
(1.5, 2.0]       9
(-1.5, -1.0]     9
(1.0, 1.5]       8
(2.0, 2.5]       3
(-2.5, -2.0]     3
(-2.0, -1.5]     1
(2.5, 3.0]       0
(-3.0, -2.5]     0
dtype: int64

### -------------------- Question 17 --------------------

- Show how to get a short summary of data in the numeric DataFrame?
- Show how to remove outliers (values which are too big or small)

#### Answer

In [27]:
# short answer: use df.describe() method

aa = ddd()
#display(aa)
display(aa.describe())
print("-"*40)

np.random.seed(12345)
df = pd.DataFrame(np.random.randn(1000, 4), columns=['A','B','C','D'])
print(df)
print("-"*40)
print(df.describe())
print("-"*40)
print(df.describe().index)  # [count, mean, std, min, 25%, 50%, 75%, max]
print("-"*40)

             ii        i1         i2        ff         f1         f2        xx          yy
count  9.000000  10.00000  10.000000  9.000000  10.000000  10.000000  10.00000   10.000000
mean   4.333333   1.50000   1.500000  4.666667   4.501235   3.330000   4.50000  284.255032
std    3.162278   3.02765   3.100179  3.162278   3.026167   3.625248   3.02765  151.831893
min    0.000000  -3.00000  -3.000000  0.000000   0.000000  -1.110000   0.00000   57.875099
25%    2.000000  -0.75000  -0.750000  2.000000   2.251575   0.285000   2.25000  171.772223
50%    4.000000   1.50000   1.000000  5.000000   4.500023   2.775000   4.50000  284.731108
75%    7.000000   3.75000   4.000000  7.000000   6.750000   5.272500   6.75000  396.515033
max    9.000000   6.00000   6.000000  9.000000   9.000000   9.990000   9.00000  509.664239

----------------------------------------
            A         B         C         D
0   -0.204708  0.478943 -0.519439 -0.555730
1    1.965781  1.393406  0.092908  0.281746
2    0.769023  1.246435  1.007189 -1.296221
3    0.274992  0.228913  1.352917  0.886429
4   -2.001637 -0.371843  1.669025 -0.438570
..        ...       ...       ...       ...
995  1.089085  0.251232 -1.451985  1.653126
996 -0.478509 -0.010663 -1.060881 -1.502870
997 -1.946267  1.013592  0.037333  0.133304
998 -1.293122 -0.322542 -0.782960 -0.303340
999  0.089987  0.292291  1.177706  0.882755

[1000 rows x 4 columns]
----------------------------------------
                 A            B            C            D
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.067684     0.067924     0.025598    -0.002298
std       0.998035     0.992106     1.006835     0.996794
min      -3.428254    -3.548824    -3.184377    -3.745356
25%      -0.774890    -0.591841    -0.641675    -0.644144
50%      -0.116401     0.101143     0.002073    -0.013611
75%       0.616366     0.780282     0.680391     0.654328
max       3.366626     2.653656     3.260383     3.927528
----------------------------------------
Index(['count', 'mean', 'std', 'min', '25%', '50%', '75%', 'max'], dtype='object')
----------------------------------------

### Here is how to remove outliers

In [78]:
# look at outliers (numbers with abs. value more than 1.5)
df = pd.DataFrame(np.random.randn(10, 4), columns=['A','B','C','D'])
mask = np.abs(df) > .5
print("type of the mask is - ", type(mask))
print("Here is the mask:")
display(mask)
print("Here is the series showing for each row")
print("if it contains a True value in any column:")
display(df[mask].any(1)) # True if there is a True value in any column

print("-"*40)
print("remove outliers - apply some mask to every element of the DataFrame")
df[mask] = np.sign(df) #  * 1.5  
display(df)

type of the mask is -  <class 'pandas.core.frame.DataFrame'>
Here is the mask:

       A      B      C      D
0   True   True   True   True
1  False  False   True  False
2  False  False   True   True
3  False   True  False  False
4   True   True   True  False
5   True  False   True   True
6   True  False   True   True
7  False   True   True  False
8   True   True   True  False
9  False   True   True   True

Here is the series showing for each row
if it contains a True value in any column:

0    True
1    True
2    True
3    True
4    True
5    True
6    True
7    True
8    True
9    True
dtype: bool

----------------------------------------
remove outliers - apply some mask to every element of the DataFrame

          A         B         C         D
0 -1.000000  1.000000  1.000000  1.000000
1  0.303898 -0.366966  1.000000 -0.129593
2  0.472386 -0.044917  1.000000 -1.000000
3  0.246979 -1.000000  0.239866 -0.209258
4  1.000000  1.000000 -1.000000 -0.019433
5  1.000000 -0.092619  1.000000 -1.000000
6 -1.000000  0.027772 -1.000000 -1.000000
7  0.435560 -1.000000 -1.000000  0.429796
8  1.000000  1.000000 -1.000000  0.276039
9  0.301343  1.000000 -1.000000  1.000000

### -------------------- Question 18 --------------------

Show how to search and replace values in a column in a DataFrame

#### Answer

In [29]:
# most common way is in 2 steps:
#   step1 - create a mask to identify rows in which we need to do the change
#   step2 - do the change to the column using the mask
#   df.loc[mask,'col1'] = df.col1[mask] + df.col2[mask]

# alternative may be to use replace based on value(s)
#   df.col1.replace(list_of_values, replacing_value)
# or
#   df.col1.replace({val1:repl1, val2:repl2, etc.})

### -------------------- Question 19 --------------------

Difference between .apply() and .transform()

#### Answer

In [30]:
# It is described here:
# https://stackoverflow.com/questions/27517425/apply-vs-transform-on-a-group-object

# There are two major differences between "transform" and "apply".
# "transform" works on just one Series at a time, wherease "apply" works on the entire DataFrame at once.

# apply     - passes DataFrame of all columns   (to custom function)
# transform - passes each column as a Series    (to custom function)

# The custom function passed to apply can return 
# a scalar, or a Series, a DataFrame, numpy array, list

# The custom function passed to transform must return
# a sequence (a one dimensional Series, array or list) 
# the same length as the group

In [79]:
# Example of using "apply"
df = pd.DataFrame({'State':['Texas', 'Texas', 'Florida', 'Florida'], 
                   'a':[4,5,1,3], 'b':[6,10,3,11]})
display(df)

     State  a   b
0    Texas  4   6
1    Texas  5  10
2  Florida  1   3
3  Florida  3  11

In [82]:
def subtract_two(x):
    return x['a'] - x['b']

# The above function will not work with transform()
# because it references two columns
#      df.groupby('State').transform(subtract_two)
#      KeyError: ('a', 'occurred at index a')

# But it will work OK with apply():
df2 = df.groupby('State').apply(subtract_two)
display(df2)
display(df2.index)

State
Florida  2   -2
         3   -8
Texas    0   -2
         1   -5
dtype: int64

MultiIndex([('Florida', 2),
            ('Florida', 3),
            (  'Texas', 0),
            (  'Texas', 1)],
           names=['State', None])

In [33]:
# Example of using "transform"
df = pd.DataFrame({"c1":['shirt','shirt','pants','pants'],
                   "c2":['white','blue','black','brown'],
                   "amnt":[100,200,300,100]})
display(df)

      c1     c2  amnt
0  shirt  white   100
1  shirt   blue   200
2  pants  black   300
3  pants  brown   100

In [34]:
# lets index by c1,c2:
df = df.set_index(['c1','c2'])
display(df)

             amnt
c1    c2
shirt white   100
      blue    200
pants black   300
      brown   100

In [35]:
# now lets calculate the percentage of each color 
# for each clothing type (shirt or pants):
df = df.groupby(level=0).transform(lambda x: 100*x/x.sum())
display(df)

                  amnt
c1    c2
shirt white  33.333333
      blue   66.666667
pants black  75.000000
      brown  25.000000

### -------------------- Question 20 --------------------

df.aggregate()

In [83]:
df = pd.DataFrame([[1,      2,      3     ],
                   [4,      5,      6     ],
                   [7,      8,      9     ],
                   [np.nan, np.nan, np.nan]],
                  columns=['A', 'B', 'C'])
display(df)

     A    B    C
0  1.0  2.0  3.0
1  4.0  5.0  6.0
2  7.0  8.0  9.0
3  NaN  NaN  NaN

In [37]:
# Aggregate these two functions over all rows.
df.agg(['sum', 'min'])

        A     B     C
sum  12.0  15.0  18.0
min   1.0   2.0   3.0

In [38]:
# Different aggregations per column.
df.agg({'A' : ['sum', 'min'], 'B' : ['min', 'max']})

        A    B
max   NaN  8.0
min   1.0  2.0
sum  12.0  NaN

In [39]:
# Aggregate over the columns.
df.agg("mean", axis="columns")

0    2.0
1    5.0
2    8.0
3    NaN
dtype: float64

In [40]:
# combine groupby().agg()
df = pd.DataFrame(data={
'country': [1,1,1, 2,2,2, 3,3,3],
'user'   : [1,2,2, 3,3,4, 5,5,5],
'event'  : [1,1,1, 1,0,0, 1,1,0]})
df['unit'] = 1
df

   country  user  event  unit
0        1     1      1     1
1        1     2      1     1
2        1     2      1     1
3        2     3      1     1
4        2     3      0     1
5        2     4      0     1
6        3     5      1     1
7        3     5      1     1
8        3     5      0     1

In [41]:
df2 = df.groupby(['country','user'],as_index=False).agg({'event':np.mean, 'unit':np.sum})
df2

   country  user     event  unit
0        1     1  1.000000     1
1        1     2  1.000000     2
2        2     3  0.500000     2
3        2     4  0.000000     1
4        3     5  0.666667     3