# Python Test 100
## Group Pandas 1

In [1]:
import os,sys
import pandas as pd
import numpy as np
from IPython.display import display, Image

In [2]:
aa = np.array([range(10),range(10)])
print(aa)
print(aa.shape)

[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]
(2, 10)

In [3]:
print(pd.__file__)
print(pd.__version__)
print(np.__file__)
print(np.__version__)

/Users/levselector/anaconda3/lib/python3.7/site-packages/pandas/__init__.py
0.24.2
/Users/levselector/anaconda3/lib/python3.7/site-packages/numpy/__init__.py
1.16.4

### Question 1

Explain how to install/upgrade pandas module

#### Answer

``` python
pandas stands for "Panel Data"
http://pandas.pydata.org/
It is a python module which is great for  analytical calculations.
Original author - Wes McKinney
Installation - it comes with Anaconda Python.
It is recommended to add these two channels:
  conda config --add channels anaconda
  conda config --add channels conda-forge
Updates happen when you update anaconda:
  conda update conda
  conda update anaconda

To play with pandas I recommend to use the following 
simple function ddd()
```

In [4]:
mydict = {} # empty dict
mydict["c1"] = [1,2,3]
mydict['c2'] = [4,5,6]
print(mydict)
print('-'*40)
aa = pd.DataFrame(  mydict , 
                    index = ['mama','papa','me'],
                    columns = ['c2','c1'])
display(aa)
print('-'*40)
print(aa.columns)

{'c1': [1, 2, 3], 'c2': [4, 5, 6]}
----------------------------------------

      c2  c1
mama   4   1
papa   5   2
me     6   3

----------------------------------------
Index(['c2', 'c1'], dtype='object')

In [5]:
aa.index[1]

'papa'

In [6]:
def ddd():
    """
    # returns a simple pandas DataFrame - useful for quick tests
    """
    nrows = 7
    aa = pd.DataFrame({
        'ii':[0,1,2,3,4,5,np.nan],                                  # float64
        'i1':[6,5,4,3,2,1,0],
        'i2':[6,5,4,4,1,1,0],
        'ff':[0.0,1.0,2.0,np.NaN,4.0,5.0,6.0],                      # float64
        'f1':[0.0,1.01,2.002,3.0003,4.00004,5.000005,6.0000006],
        'f2':[1.11,2.22,3.33,4.44,5.55,7.77,9.99],
        'ss':['s0','s1','狗','汽车',np.nan,'s5','s6'],               # dtype=object, np.nan is float64
        's1':np.array(['s0','s1','s2','s2',np.nan,'s5','s6'],
                      dtype=np.str), # dtype=object, 'nan' is string
        's2':['1.11','2.22','3.33','4.44','5.55','7.77','9.99'],
        'bb':[True, False, True, False, np.nan, False, True],       # dtype=object, np.nan is float64
        'b1':[True, False, True, False, True, False, True],         # dtype=bool
        'xx':range(nrows),
        'yy':[x*50 + 60 + np.random.randn() for x in range(nrows)]
    })

    return aa[['ii','i1','i2','ff','f1','f2','ss','s1','s2','bb','b1','xx','yy']]

In [7]:
aa = ddd()
aa.head(5).tail(2)
aa.tail(6).T.copy()

         1        2       3        4        5       6
ii       1        2       3        4        5     NaN
i1       5        4       3        2        1       0
i2       5        4       4        1        1       0
ff       1        2     NaN        4        5       6
f1    1.01    2.002  3.0003  4.00004        5       6
f2    2.22     3.33    4.44     5.55     7.77    9.99
ss      s1        狗      汽车      NaN       s5      s6
s1      s1       s2      s2      nan       s5      s6
s2    2.22     3.33    4.44     5.55     7.77    9.99
bb   False     True   False      NaN    False    True
b1   False     True   False     True    False    True
xx       1        2       3        4        5       6
yy  110.45  161.703  210.66  259.954  311.035  358.74

### Question 2

- Show how to test the type of the variable (is it an int? float? str?, list? dict? etc.) 
- Show how to test type of a column in a DataFrame 
- Show how to list types of all columns in a DataFrame

#### Answer

In [8]:
type({1:2,3:4})
aa = ddd()
aa['i1'].dtype

dtype('int64')

In [9]:
print("type of a python variable")

def print_type(obj):
    if type(obj) == int:
        print("  int")
    elif type(obj) == float:
        print("  float")
    elif type(obj) == str:
        print("  str")
    else:
        print("  unknown type")

print_type(1)
print_type(1.1)
print_type('mama')
print_type([1,2,3])

print("type of pd.DataFrame column")
aa = ddd()
print("aa.f1.dtype    = ",aa.f1.dtype)
print("aa['f1'].dtype = ",aa['f1'].dtype)

print('-'*40)
print("types of all pd.DataFrame columns")
print(aa.dtypes)

type of a python variable
  int
  float
  str
  unknown type
type of pd.DataFrame column
aa.f1.dtype    =  float64
aa['f1'].dtype =  float64
----------------------------------------
types of all pd.DataFrame columns
ii    float64
i1      int64
i2      int64
ff    float64
f1    float64
f2    float64
ss     object
s1     object
s2     object
bb     object
b1       bool
xx      int64
yy    float64
dtype: object

### Question 3

Show how to take a value from a particular cell of a dataframe
 - using df[col][row]                  # label based
 - using df.loc [row_label, col_label] # label based
 - using df.iloc[row_index, col_index] # indexes start with 0

#### Answer

In [10]:
aa = ddd()
aa.index = range(len(aa))
# aa.index = range(len(aa)-1,  -1,  -1)
print("aa['i2'][1]     =", aa['i2'][1]   )     # order: column(s), row(s)
print("aa.loc [1,'i2'] =", aa.loc [1,'i2'] )   # order: row(s), column(s)
print("aa.iloc[1,1]    =", aa.iloc[1, 1  ] )   # order: row(s), column(s)

aa['i2'][1]     = 5
aa.loc [1,'i2'] = 5
aa.iloc[1,1]    = 5

In [11]:
aa = ddd()
mask = (aa.f1 >= 1.5) & (aa.f1 < 5)
print(mask)
aa[mask]
# aa[2:4]
# aa

0    False
1    False
2     True
3     True
4     True
5    False
6    False
Name: f1, dtype: bool

    ii  i1  i2   ff       f1    f2   ss   s1    s2     bb     b1  xx          yy
2  2.0   4   4  2.0  2.00200  3.33    狗   s2  3.33   True   True   2  159.479811
3  3.0   3   4  NaN  3.00030  4.44   汽车   s2  4.44  False  False   3  210.256078
4  4.0   2   1  4.0  4.00004  5.55  NaN  nan  5.55    NaN   True   4  259.180665

In [12]:
aa=ddd()
aa.index = range(6,-1,-1)
aa.loc[2,'ii']

4.0

In [13]:
aa = [5,6,7,8,9,10,11,12]
bb = aa[:]
cc = aa
cc = aa
for ii in range(len(cc)):
    cc[ii] = pow(cc[ii],2)
print(id(aa))
print(id(cc))
print(id(bb))
print(aa)
print(cc)

4630090760
4630090760
4630090824
[25, 36, 49, 64, 81, 100, 121, 144]
[25, 36, 49, 64, 81, 100, 121, 144]

In [14]:
x = 100000000
e = (1+1/x)**x
print(e)

2.7182817983473577

In [15]:
# Note:
#   loc  - by labels
#   iloc - by integer numbers of rows/columns - count starts with 0
#   ix   - deprecated, can do both

aa = ddd()
aa = aa.loc[:,['ii','i1','i2']] # [rows,cols]
aa.index = range(len(aa))  # 0,1,...,5,6
aa.index = aa.index.map(lambda x: 'm' + str(x))
display(aa)
#     id  i1  i2
# m0   0   6   6
# m1   1   5   5
# m2   2   4   4
# m3   3   3   4
# m4   4   2   1
# m5   5   1  1
# m6 NaN   0   0
print('-'*40)
print(aa.loc['m2','i2'])  # 4
# aa.iloc['m2','i2'] # ERROR
print(aa.iloc[2,2])       # 4

     ii  i1  i2
m0  0.0   6   6
m1  1.0   5   5
m2  2.0   4   4
m3  3.0   3   4
m4  4.0   2   1
m5  5.0   1   1
m6  NaN   0   0

----------------------------------------
4
4

### Question 4

Extract a row from a DataFrame into a regular python list

#### Answer

In [16]:
aa=ddd()
print(aa.loc[1,:].values.tolist())
print(aa.loc[1,:].tolist())
print(aa.iloc[len(aa)-1].tolist())

[1.0, 5, 5, 1.0, 1.01, 2.22, 's1', 's1', '2.22', False, False, 1, 108.61474462264229]
[1.0, 5, 5, 1.0, 1.01, 2.22, 's1', 's1', '2.22', False, False, 1, 108.61474462264229]
[nan, 0, 0, 6.0, 6.0000006, 9.99, 's6', 's6', '9.99', True, True, 6, 358.4277938195921]

In [17]:
aa=ddd()
type(aa.i1.values)

numpy.ndarray

### Question 5

- Show to find rows which has the same value in a particular column
- Show how to use value_counts()
- Show how to count number of times each unique value appears in group, and for multiple columns 
- What is np.unique - and how is it used?
- Write a procedure to extract duplicate rows (by one or more columns)

#### Answer

In [18]:
# duplicated() - create true/false mask
aa=ddd()
aa.duplicated(['i2'])

0    False
1    False
2    False
3     True
4    False
5     True
6    False
dtype: bool

In [19]:
# value_counts()
# Returns pd.Series containing counts of unique values (excluding NaN)
# in descending order (the first element is the most frequently occuring).

aa['i2'].value_counts()

4    2
1    2
6    1
5    1
0    1
Name: i2, dtype: int64

In [20]:
# Show how to count number of times each unique value appears in group, and for multiple columns

data = [
  ['amazon.com',  'correct',   'correct'  ], 
  ['amazon.com',  'incorrect', 'correct'  ], 
  ['walmart.com', 'incorrect', 'correct'  ], 
  ['walmart.com', 'incorrect', 'incorrect']
]

source = pd.DataFrame(data, columns=['domain', 'price', 'product'])

source.groupby('domain').apply(lambda x: x[['price','product']].apply(lambda y: y.value_counts())).fillna(0)

                       price  product
domain
amazon.com  correct      1.0      2.0
            incorrect    1.0      0.0
walmart.com correct      0.0      1.0
            incorrect    2.0      1.0

In [21]:
# np.unique is a Numpy function which shows unique values in a column,
# and where they were found first time.

aa=ddd()
np.unique(aa.i2)

array([0, 1, 4, 5, 6])

In [22]:
# a procedure to extract duplicate rows (by one or more columns)

def show_duplicates(df, cols=[], include_nulls=True):
    """
    # accepts a dataframe df and a column (or list of columns)
    # if list of columns is not provided - uses all df columns
    # returns a dataframe consisting of rows of df
    # which have duplicate values in "cols"
    # sorted by "cols" so that duplciates are next to each other
    # Note - doesn't change index values of rows
    """
    # ---------------------------------
    aa = df.copy()
    mycols = cols
    # ---------------------------------
    if len(mycols) <= 0:
        mycols = aa.columns.tolist()
    elif type(mycols) != list:
        mycols = list(mycols)
    # ---------------------------------
    if not include_nulls:
        mask = False
        for mycol in mycols:
            mask = mask | (aa[mycol] != aa[mycol])  # test for null values
        aa = aa[~mask]                              # remove rows with nulls in mycols
    if len(aa) <= 0:
        return aa[:0]
    # ---------------------------------
    # duplicated() method returns Boolean Series denoting duplicate rows
    mask = aa.duplicated(subset=mycols, keep='first').values \
         | aa.duplicated(subset=mycols, keep='first').values
    aa = aa[mask]
    if len(aa) <= 0:
        return aa[:0]
    # ---------------------------------
    # sorting to keep duplicates together
    # Attention - can not sort by nulls
    # bb contains mycols except for cols which are completely nulls
    bb = aa[mycols]
    bb = bb.dropna(how='all',axis=1)
    # sort aa by columns in bb (thus avoiding nulls)
    aa = aa.sort_values(by=bb.columns.tolist())
    # ---------------------------------
    # sorting skips nulls thus messing up the order. 
    # Let's put nulls at the end
    mask = False
    for mycol in mycols:
        mask = mask | (aa[mycol] != aa[mycol])  # test for null values
    aa1 = aa[~mask]
    aa2 = aa[mask]
    aa = aa1.append(aa2)

    return aa

In [23]:
aa = ddd()
show_duplicates(df=aa, cols=['i2'], include_nulls=True)

    ii  i1  i2   ff        f1    f2  ss  s1    s2     bb     b1  xx          yy
5  5.0   1   1  5.0  5.000005  7.77  s5  s5  7.77  False  False   5  310.705452
3  3.0   3   4  NaN  3.000300  4.44  汽车  s2  4.44  False  False   3  209.229425

### Question 6

- Show how to append dataframes
- Show how to append a list (or series) of data to a dataframe

#### Answer

In [24]:
# append two dataframes one on top of the other
aa1 = ddd()
aa2 = ddd()
aa = aa1.append(aa2)
aa.index = range(len(aa))
display(aa)

     ii  i1  i2   ff        f1    f2   ss   s1    s2     bb     b1  xx          yy
0   0.0   6   6  0.0  0.000000  1.11   s0   s0  1.11   True   True   0   58.962607
1   1.0   5   5  1.0  1.010000  2.22   s1   s1  2.22  False  False   1  110.341238
2   2.0   4   4  2.0  2.002000  3.33    狗   s2  3.33   True   True   2  160.361777
3   3.0   3   4  NaN  3.000300  4.44   汽车   s2  4.44  False  False   3  210.263638
4   4.0   2   1  4.0  4.000040  5.55  NaN  nan  5.55    NaN   True   4  260.238428
5   5.0   1   1  5.0  5.000005  7.77   s5   s5  7.77  False  False   5  308.177043
6   NaN   0   0  6.0  6.000001  9.99   s6   s6  9.99   True   True   6  359.992572
7   0.0   6   6  0.0  0.000000  1.11   s0   s0  1.11   True   True   0   59.147103
8   1.0   5   5  1.0  1.010000  2.22   s1   s1  2.22  False  False   1  110.262736
9   2.0   4   4  2.0  2.002000  3.33    狗   s2  3.33   True   True   2  159.878356
10  3.0   3   4  NaN  3.000300  4.44   汽车   s2  4.44  False  False   3  210.039593
11  4.0   2   1  4.0  4.000040  5.55  NaN  nan  5.55    NaN   True   4  260.871233
12  5.0   1   1  5.0  5.000005  7.77   s5   s5  7.77  False  False   5  309.446310
13  NaN   0   0  6.0  6.000001  9.99   s6   s6  9.99   True   True   6  359.887713

In [25]:
# append a series or list by converting it to a DataFrame
aa = ddd()
bb = aa.loc[1].tolist()   # take 2nd row as a list
dd = pd.DataFrame([bb], columns=aa.columns)

# now append list
aa = aa.append(dd)
display(aa)

# Note: alternatively you can make 1-column dataframe - and transpose it
# bb=DataFrame(ss)
# bb.index = aa.columns
# aa.append(bb.T)

    ii  i1  i2   ff        f1    f2   ss   s1    s2     bb     b1  xx          yy
0  0.0   6   6  0.0  0.000000  1.11   s0   s0  1.11   True   True   0   60.365421
1  1.0   5   5  1.0  1.010000  2.22   s1   s1  2.22  False  False   1  110.886877
2  2.0   4   4  2.0  2.002000  3.33    狗   s2  3.33   True   True   2  161.672697
3  3.0   3   4  NaN  3.000300  4.44   汽车   s2  4.44  False  False   3  210.404792
4  4.0   2   1  4.0  4.000040  5.55  NaN  nan  5.55    NaN   True   4  259.589652
5  5.0   1   1  5.0  5.000005  7.77   s5   s5  7.77  False  False   5  308.272131
6  NaN   0   0  6.0  6.000001  9.99   s6   s6  9.99   True   True   6  359.437122
0  1.0   5   5  1.0  1.010000  2.22   s1   s1  2.22  False  False   1  110.886877

### Question 7

Show how to remove duplicate rows (duplicate is defined as having same value in a list of columns)

#### Answer

In [26]:
aa = aa.drop_duplicates(['i2']) 
# or
aa = aa.drop_duplicates(['i2'], keep='last') 
display(aa)

    ii  i1  i2   ff        f1    f2   ss   s1    s2     bb     b1  xx          yy
0  0.0   6   6  0.0  0.000000  1.11   s0   s0  1.11   True   True   0   60.365421
1  1.0   5   5  1.0  1.010000  2.22   s1   s1  2.22  False  False   1  110.886877
2  2.0   4   4  2.0  2.002000  3.33    狗   s2  3.33   True   True   2  161.672697
4  4.0   2   1  4.0  4.000040  5.55  NaN  nan  5.55    NaN   True   4  259.589652
6  NaN   0   0  6.0  6.000001  9.99   s6   s6  9.99   True   True   6  359.437122

### Question 8

Show how to use a mask using   &, |, ~, .isin(), .isnull()

#### Answer

In [27]:
aa=ddd()
mask = aa.f2.isnull()
display(aa[mask])
print('-'*40)
mask = aa.i1.isin([1,3,5])
display(aa[mask])
print('-'*40)
display(aa[~mask]) # shows the records where mask is False
print('-'*40)

# examples of masks based on more than one column
# mask = (aa.ii==1) & (aa.i2 == 4)
# mask = (aa.ii==1) | (aa.i2 == 4)

Empty DataFrame
Columns: [ii, i1, i2, ff, f1, f2, ss, s1, s2, bb, b1, xx, yy]
Index: []

----------------------------------------

    ii  i1  i2   ff        f1    f2  ss  s1    s2     bb     b1  xx          yy
1  1.0   5   5  1.0  1.010000  2.22  s1  s1  2.22  False  False   1  109.856027
3  3.0   3   4  NaN  3.000300  4.44  汽车  s2  4.44  False  False   3  209.852564
5  5.0   1   1  5.0  5.000005  7.77  s5  s5  7.77  False  False   5  308.938276

----------------------------------------

    ii  i1  i2   ff        f1    f2   ss   s1    s2    bb    b1  xx          yy
0  0.0   6   6  0.0  0.000000  1.11   s0   s0  1.11  True  True   0   58.781492
2  2.0   4   4  2.0  2.002000  3.33    狗   s2  3.33  True  True   2  159.236668
4  4.0   2   1  4.0  4.000040  5.55  NaN  nan  5.55   NaN  True   4  260.206426
6  NaN   0   0  6.0  6.000001  9.99   s6   s6  9.99  True  True   6  360.074373

----------------------------------------

### Question 9

Give an example of using a map() function on a pandas DataFrame column

#### Answer

In [28]:
aa=ddd()
str(aa.yy)

'0     59.811605\n1    109.807470\n2    159.152299\n3    210.950268\n4    261.238154\n5    308.860858\n6    357.757351\nName: yy, dtype: float64'

In [29]:
aa=ddd()
display(aa.yy.dtype)
aa['yy'] = aa.yy.map(lambda crocodile : str(round(crocodile,2)) + "abc")
display(aa)

dtype('float64')

    ii  i1  i2   ff        f1    f2   ss   s1    s2     bb     b1  xx         yy
0  0.0   6   6  0.0  0.000000  1.11   s0   s0  1.11   True   True   0   59.83abc
1  1.0   5   5  1.0  1.010000  2.22   s1   s1  2.22  False  False   1  110.72abc
2  2.0   4   4  2.0  2.002000  3.33    狗   s2  3.33   True   True   2  160.14abc
3  3.0   3   4  NaN  3.000300  4.44   汽车   s2  4.44  False  False   3  209.05abc
4  4.0   2   1  4.0  4.000040  5.55  NaN  nan  5.55    NaN   True   4  260.49abc
5  5.0   1   1  5.0  5.000005  7.77   s5   s5  7.77  False  False   5  311.41abc
6  NaN   0   0  6.0  6.000001  9.99   s6   s6  9.99   True   True   6  359.89abc

### Question 10

Give example using map with lambda for dataframe operations

#### Answer

In [30]:
aa = ddd()
aa['s2'] = aa.ss + '__' + aa.i1.map(lambda x: str(x))

# make a list of values in column 'yy' 
# rounded to 2 digits after dot
aa['zz'] = aa['yy'].map(lambda x: round(x,2))
display(aa)

    ii  i1  i2   ff        f1    f2   ss   s1     s2     bb     b1  xx          yy      zz
0  0.0   6   6  0.0  0.000000  1.11   s0   s0  s0__6   True   True   0   59.087476   59.09
1  1.0   5   5  1.0  1.010000  2.22   s1   s1  s1__5  False  False   1  109.627202  109.63
2  2.0   4   4  2.0  2.002000  3.33    狗   s2   狗__4   True   True   2  159.717347  159.72
3  3.0   3   4  NaN  3.000300  4.44   汽车   s2  汽车__3  False  False   3  209.150198  209.15
4  4.0   2   1  4.0  4.000040  5.55  NaN  nan    NaN    NaN   True   4  261.514639  261.51
5  5.0   1   1  5.0  5.000005  7.77   s5   s5  s5__1  False  False   5  309.963971  309.96
6  NaN   0   0  6.0  6.000001  9.99   s6   s6  s6__0   True   True   6  359.229546  359.23

### Question 11

Give example using groupby().sum()

#### Answer

In [31]:
aa = ddd()
cc = aa.groupby(['i2'], as_index=False).sum()
display(cc)
print("-"*40)

# note - groupby().sum() will usually remove all 
# string columns from the result. To avoid it, you can use agg()
# But be carefull to avoid mixing NaN with strings - causes error 

aa = ddd()
aa['ss'] = aa.ss.fillna('_') # this removes NaN
cc = aa.groupby('i2', as_index=False).agg({'i1':np.sum,'ss':np.max})
display(cc)

   i2   ii  i1   ff        f1     f2     b1  xx          yy
0   0  0.0   0  6.0  6.000001   9.99   True   6  358.228862
1   1  9.0   3  9.0  9.000045  13.32   True   9  569.023013
2   4  5.0   7  2.0  5.002300   7.77   True   5  370.369933
3   5  1.0   5  1.0  1.010000   2.22  False   1  108.572199
4   6  0.0   6  0.0  0.000000   1.11   True   0   60.977137

----------------------------------------

   i2  i1  ss
0   0   0  s6
1   1   3  s5
2   4   7   狗
3   5   5  s1
4   6   6  s0

### Question 12

Give example using groupby().aggregate()

#### Answer

In [32]:
aa = ddd()
bb = aa.groupby('i2', as_index=True).aggregate({'yy':np.sum, 'xx':np.max}) 
display(bb)

            yy  xx
i2
0   359.774998   6
1   571.117968   5
4   370.317193   3
5   110.949770   1
6    59.639027   0

### Question 13

Show how to sort a dataframe by a list of columns

#### Answer

In [33]:
cc = aa.sort_values(by=['i2','yy'])
display(cc)

    ii  i1  i2   ff        f1    f2   ss   s1    s2     bb     b1  xx          yy
6  NaN   0   0  6.0  6.000001  9.99   s6   s6  9.99   True   True   6  359.774998
4  4.0   2   1  4.0  4.000040  5.55  NaN  nan  5.55    NaN   True   4  260.667278
5  5.0   1   1  5.0  5.000005  7.77   s5   s5  7.77  False  False   5  310.450690
2  2.0   4   4  2.0  2.002000  3.33    狗   s2  3.33   True   True   2  160.019973
3  3.0   3   4  NaN  3.000300  4.44   汽车   s2  4.44  False  False   3  210.297220
1  1.0   5   5  1.0  1.010000  2.22   s1   s1  2.22  False  False   1  110.949770
0  0.0   6   6  0.0  0.000000  1.11   s0   s0  1.11   True   True   0   59.639027

### Question 14

Show how to delete some rows from dataframe - and reindex

#### Answer

In [34]:
aa = ddd()
aa = aa.drop([1,3,5]) # remove several rows 
display(aa)

    ii  i1  i2   ff        f1    f2   ss   s1    s2    bb    b1  xx          yy
0  0.0   6   6  0.0  0.000000  1.11   s0   s0  1.11  True  True   0   58.603342
2  2.0   4   4  2.0  2.002000  3.33    狗   s2  3.33  True  True   2  159.352915
4  4.0   2   1  4.0  4.000040  5.55  NaN  nan  5.55   NaN  True   4  260.566789
6  NaN   0   0  6.0  6.000001  9.99   s6   s6  9.99  True  True   6  362.975468

In [35]:
# remove rows based on a mask
aa = ddd()
mask = aa['ii'].map(lambda x: x > 3) # True when aa.ii > 3
aa = aa[~mask]                       # take only where a.ii <= 3 or NaN
display(aa)
print('-'*40)
mask = aa['ii'].map(lambda x: x in (0,1,4))
aa = aa[~mask]
display(aa)

    ii  i1  i2   ff        f1    f2  ss  s1    s2     bb     b1  xx          yy
0  0.0   6   6  0.0  0.000000  1.11  s0  s0  1.11   True   True   0   60.365666
1  1.0   5   5  1.0  1.010000  2.22  s1  s1  2.22  False  False   1  110.974737
2  2.0   4   4  2.0  2.002000  3.33   狗  s2  3.33   True   True   2  160.506301
3  3.0   3   4  NaN  3.000300  4.44  汽车  s2  4.44  False  False   3  209.099436
6  NaN   0   0  6.0  6.000001  9.99  s6  s6  9.99   True   True   6  359.286895

----------------------------------------

    ii  i1  i2   ff        f1    f2  ss  s1    s2     bb     b1  xx          yy
2  2.0   4   4  2.0  2.002000  3.33   狗  s2  3.33   True   True   2  160.506301
3  3.0   3   4  NaN  3.000300  4.44  汽车  s2  4.44  False  False   3  209.099436
6  NaN   0   0  6.0  6.000001  9.99  s6  s6  9.99   True   True   6  359.286895

In [36]:
# after removing rows you may want to index rows sequentially
aa = ddd()
aa.reindex() # doesn't change index unless you provide it 
print('-0'*30)
aa.index = range(len(aa))
display(aa)
print('-1'*30)
# note - you can shift index
aa.index = range(100,100+len(aa))
display(aa)
print('-2'*30)
# you can even make all index values the same - although it is pointless
aa.index = [2]*len(aa)
display(aa)

-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0

    ii  i1  i2   ff        f1    f2   ss   s1    s2     bb     b1  xx          yy
0  0.0   6   6  0.0  0.000000  1.11   s0   s0  1.11   True   True   0   60.306059
1  1.0   5   5  1.0  1.010000  2.22   s1   s1  2.22  False  False   1  110.240528
2  2.0   4   4  2.0  2.002000  3.33    狗   s2  3.33   True   True   2  158.405993
3  3.0   3   4  NaN  3.000300  4.44   汽车   s2  4.44  False  False   3  207.662142
4  4.0   2   1  4.0  4.000040  5.55  NaN  nan  5.55    NaN   True   4  260.230352
5  5.0   1   1  5.0  5.000005  7.77   s5   s5  7.77  False  False   5  309.573691
6  NaN   0   0  6.0  6.000001  9.99   s6   s6  9.99   True   True   6  357.177744

-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1

      ii  i1  i2   ff        f1    f2   ss   s1    s2     bb     b1  xx          yy
100  0.0   6   6  0.0  0.000000  1.11   s0   s0  1.11   True   True   0   60.306059
101  1.0   5   5  1.0  1.010000  2.22   s1   s1  2.22  False  False   1  110.240528
102  2.0   4   4  2.0  2.002000  3.33    狗   s2  3.33   True   True   2  158.405993
103  3.0   3   4  NaN  3.000300  4.44   汽车   s2  4.44  False  False   3  207.662142
104  4.0   2   1  4.0  4.000040  5.55  NaN  nan  5.55    NaN   True   4  260.230352
105  5.0   1   1  5.0  5.000005  7.77   s5   s5  7.77  False  False   5  309.573691
106  NaN   0   0  6.0  6.000001  9.99   s6   s6  9.99   True   True   6  357.177744

-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2

    ii  i1  i2   ff        f1    f2   ss   s1    s2     bb     b1  xx          yy
2  0.0   6   6  0.0  0.000000  1.11   s0   s0  1.11   True   True   0   60.306059
2  1.0   5   5  1.0  1.010000  2.22   s1   s1  2.22  False  False   1  110.240528
2  2.0   4   4  2.0  2.002000  3.33    狗   s2  3.33   True   True   2  158.405993
2  3.0   3   4  NaN  3.000300  4.44   汽车   s2  4.44  False  False   3  207.662142
2  4.0   2   1  4.0  4.000040  5.55  NaN  nan  5.55    NaN   True   4  260.230352
2  5.0   1   1  5.0  5.000005  7.77   s5   s5  7.77  False  False   5  309.573691
2  NaN   0   0  6.0  6.000001  9.99   s6   s6  9.99   True   True   6  357.177744

### Question 15

Show how to add rows to a dataframe 
<br>(add 2 dataframes together vertically - and reindex)

#### Answer

In [37]:
aa=ddd()
aa = aa.append(aa[2:4],ignore_index=True)
display(aa)

    ii  i1  i2   ff        f1    f2   ss   s1    s2     bb     b1  xx          yy
0  0.0   6   6  0.0  0.000000  1.11   s0   s0  1.11   True   True   0   60.951932
1  1.0   5   5  1.0  1.010000  2.22   s1   s1  2.22  False  False   1  110.085379
2  2.0   4   4  2.0  2.002000  3.33    狗   s2  3.33   True   True   2  160.914493
3  3.0   3   4  NaN  3.000300  4.44   汽车   s2  4.44  False  False   3  208.892905
4  4.0   2   1  4.0  4.000040  5.55  NaN  nan  5.55    NaN   True   4  258.456661
5  5.0   1   1  5.0  5.000005  7.77   s5   s5  7.77  False  False   5  311.423221
6  NaN   0   0  6.0  6.000001  9.99   s6   s6  9.99   True   True   6  360.131651
7  2.0   4   4  2.0  2.002000  3.33    狗   s2  3.33   True   True   2  160.914493
8  3.0   3   4  NaN  3.000300  4.44   汽车   s2  4.44  False  False   3  208.892905

### Question 16

- Show how to write dataframe to csv file
- Show how to read it back

#### Answer

In [38]:
aa = ddd()
aa.to_csv('junk.csv', sep='|', header=True, index=False)
bb = pd.read_csv('junk.csv', sep='|')
display(bb)

    ii  i1  i2   ff        f1    f2   ss   s1    s2     bb     b1  xx          yy
0  0.0   6   6  0.0  0.000000  1.11   s0   s0  1.11   True   True   0   62.518683
1  1.0   5   5  1.0  1.010000  2.22   s1   s1  2.22  False  False   1  110.867047
2  2.0   4   4  2.0  2.002000  3.33    狗   s2  3.33   True   True   2  158.723228
3  3.0   3   4  NaN  3.000300  4.44   汽车   s2  4.44  False  False   3  211.164207
4  4.0   2   1  4.0  4.000040  5.55  NaN  NaN  5.55    NaN   True   4  261.321666
5  5.0   1   1  5.0  5.000005  7.77   s5   s5  7.77  False  False   5  311.393075
6  NaN   0   0  6.0  6.000001  9.99   s6   s6  9.99   True   True   6  361.284078

### Question 17

- Show how to add columns to pandas DataFrame
- Show how to calculate column values from numeric/string values in other columns.
- Show how to delete one or more columns

#### Answer

In [39]:
aa = ddd()
aa['c4'] = None         # populate with same value
display(aa)
print('-0'*30)
col2=[1,2,3,4,5,6,7]
aa['c4'] = col2         # list becomes a column
display(aa)
print('-1'*30)
aa['c4'] = "-"
display(aa)
print('-2'*30)

# adding a column - and populating it using vectorized operation on columns
aa['c5']= 2*aa['i1'] + 3*aa['i2'] + 5
display(aa)
print('-3'*30)

# calculating column values from other columns:
aa['c4']= 2*aa['i1'] + 3*aa['i2'] + 5
aa['s2'] = aa.ss + '__' + aa.i1.map(lambda x: str(x))
display(aa)
print('-4'*30)

# Deleting one column
del aa['s1']
display(aa)
print('-5'*30)

# Deleting many columns
aa = aa.drop(['i1','i2','c4'], axis=1)
display(aa)

    ii  i1  i2   ff        f1    f2   ss   s1    s2     bb     b1  xx          yy    c4
0  0.0   6   6  0.0  0.000000  1.11   s0   s0  1.11   True   True   0   61.960696  None
1  1.0   5   5  1.0  1.010000  2.22   s1   s1  2.22  False  False   1  110.954124  None
2  2.0   4   4  2.0  2.002000  3.33    狗   s2  3.33   True   True   2  158.785236  None
3  3.0   3   4  NaN  3.000300  4.44   汽车   s2  4.44  False  False   3  211.240446  None
4  4.0   2   1  4.0  4.000040  5.55  NaN  nan  5.55    NaN   True   4  261.161846  None
5  5.0   1   1  5.0  5.000005  7.77   s5   s5  7.77  False  False   5  311.051283  None
6  NaN   0   0  6.0  6.000001  9.99   s6   s6  9.99   True   True   6  361.248450  None

-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0-0

    ii  i1  i2   ff        f1    f2   ss   s1    s2     bb     b1  xx          yy  c4
0  0.0   6   6  0.0  0.000000  1.11   s0   s0  1.11   True   True   0   61.960696   1
1  1.0   5   5  1.0  1.010000  2.22   s1   s1  2.22  False  False   1  110.954124   2
2  2.0   4   4  2.0  2.002000  3.33    狗   s2  3.33   True   True   2  158.785236   3
3  3.0   3   4  NaN  3.000300  4.44   汽车   s2  4.44  False  False   3  211.240446   4
4  4.0   2   1  4.0  4.000040  5.55  NaN  nan  5.55    NaN   True   4  261.161846   5
5  5.0   1   1  5.0  5.000005  7.77   s5   s5  7.77  False  False   5  311.051283   6
6  NaN   0   0  6.0  6.000001  9.99   s6   s6  9.99   True   True   6  361.248450   7

-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1

    ii  i1  i2   ff        f1    f2   ss   s1    s2     bb     b1  xx          yy c4
0  0.0   6   6  0.0  0.000000  1.11   s0   s0  1.11   True   True   0   61.960696  -
1  1.0   5   5  1.0  1.010000  2.22   s1   s1  2.22  False  False   1  110.954124  -
2  2.0   4   4  2.0  2.002000  3.33    狗   s2  3.33   True   True   2  158.785236  -
3  3.0   3   4  NaN  3.000300  4.44   汽车   s2  4.44  False  False   3  211.240446  -
4  4.0   2   1  4.0  4.000040  5.55  NaN  nan  5.55    NaN   True   4  261.161846  -
5  5.0   1   1  5.0  5.000005  7.77   s5   s5  7.77  False  False   5  311.051283  -
6  NaN   0   0  6.0  6.000001  9.99   s6   s6  9.99   True   True   6  361.248450  -

-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2-2

    ii  i1  i2   ff        f1    f2   ss   s1    s2     bb     b1  xx          yy c4  c5
0  0.0   6   6  0.0  0.000000  1.11   s0   s0  1.11   True   True   0   61.960696  -  35
1  1.0   5   5  1.0  1.010000  2.22   s1   s1  2.22  False  False   1  110.954124  -  30
2  2.0   4   4  2.0  2.002000  3.33    狗   s2  3.33   True   True   2  158.785236  -  25
3  3.0   3   4  NaN  3.000300  4.44   汽车   s2  4.44  False  False   3  211.240446  -  23
4  4.0   2   1  4.0  4.000040  5.55  NaN  nan  5.55    NaN   True   4  261.161846  -  12
5  5.0   1   1  5.0  5.000005  7.77   s5   s5  7.77  False  False   5  311.051283  -  10
6  NaN   0   0  6.0  6.000001  9.99   s6   s6  9.99   True   True   6  361.248450  -   5

-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3-3

    ii  i1  i2   ff        f1    f2   ss   s1     s2     bb     b1  xx          yy  c4  c5
0  0.0   6   6  0.0  0.000000  1.11   s0   s0  s0__6   True   True   0   61.960696  35  35
1  1.0   5   5  1.0  1.010000  2.22   s1   s1  s1__5  False  False   1  110.954124  30  30
2  2.0   4   4  2.0  2.002000  3.33    狗   s2   狗__4   True   True   2  158.785236  25  25
3  3.0   3   4  NaN  3.000300  4.44   汽车   s2  汽车__3  False  False   3  211.240446  23  23
4  4.0   2   1  4.0  4.000040  5.55  NaN  nan    NaN    NaN   True   4  261.161846  12  12
5  5.0   1   1  5.0  5.000005  7.77   s5   s5  s5__1  False  False   5  311.051283  10  10
6  NaN   0   0  6.0  6.000001  9.99   s6   s6  s6__0   True   True   6  361.248450   5   5

-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4-4

    ii  i1  i2   ff        f1    f2   ss     s2     bb     b1  xx          yy  c4  c5
0  0.0   6   6  0.0  0.000000  1.11   s0  s0__6   True   True   0   61.960696  35  35
1  1.0   5   5  1.0  1.010000  2.22   s1  s1__5  False  False   1  110.954124  30  30
2  2.0   4   4  2.0  2.002000  3.33    狗   狗__4   True   True   2  158.785236  25  25
3  3.0   3   4  NaN  3.000300  4.44   汽车  汽车__3  False  False   3  211.240446  23  23
4  4.0   2   1  4.0  4.000040  5.55  NaN    NaN    NaN   True   4  261.161846  12  12
5  5.0   1   1  5.0  5.000005  7.77   s5  s5__1  False  False   5  311.051283  10  10
6  NaN   0   0  6.0  6.000001  9.99   s6  s6__0   True   True   6  361.248450   5   5

-5-5-5-5-5-5-5-5-5-5-5-5-5-5-5-5-5-5-5-5-5-5-5-5-5-5-5-5-5-5

    ii   ff        f1    f2   ss     s2     bb     b1  xx          yy  c5
0  0.0  0.0  0.000000  1.11   s0  s0__6   True   True   0   61.960696  35
1  1.0  1.0  1.010000  2.22   s1  s1__5  False  False   1  110.954124  30
2  2.0  2.0  2.002000  3.33    狗   狗__4   True   True   2  158.785236  25
3  3.0  NaN  3.000300  4.44   汽车  汽车__3  False  False   3  211.240446  23
4  4.0  4.0  4.000040  5.55  NaN    NaN    NaN   True   4  261.161846  12
5  5.0  5.0  5.000005  7.77   s5  s5__1  False  False   5  311.051283  10
6  NaN  6.0  6.000001  9.99   s6  s6__0   True   True   6  361.248450   5

### Question 18

Show how to calculate a pandas DataFrame column 
as a linear combination of some other columns

#### Answer

In [40]:
aa = ddd()
aa['c4']= 2*aa['i1'] + 3*aa['i2'] + 5 
display(aa)

    ii  i1  i2   ff        f1    f2   ss   s1    s2     bb     b1  xx          yy  c4
0  0.0   6   6  0.0  0.000000  1.11   s0   s0  1.11   True   True   0   61.033251  35
1  1.0   5   5  1.0  1.010000  2.22   s1   s1  2.22  False  False   1  110.098704  30
2  2.0   4   4  2.0  2.002000  3.33    狗   s2  3.33   True   True   2  160.107137  25
3  3.0   3   4  NaN  3.000300  4.44   汽车   s2  4.44  False  False   3  209.596649  23
4  4.0   2   1  4.0  4.000040  5.55  NaN  nan  5.55    NaN   True   4  259.172216  12
5  5.0   1   1  5.0  5.000005  7.77   s5   s5  7.77  False  False   5  309.770830  10
6  NaN   0   0  6.0  6.000001  9.99   s6   s6  9.99   True   True   6  361.469742   5

### Question 19

Show how to calculate a DataFrame column 
from several other columns while using str() and int().<br>
Hint - use map(lambda ..)

#### Answer

In [41]:
aa = ddd()
aa['s3'] = aa['yy'].map(lambda x: int(x)) 
aa['s4']= '>>>' + aa.s3.map(lambda x: str(x)) + '<<<'
display(aa)

    ii  i1  i2   ff        f1    f2   ss   s1    s2     bb     b1  xx          yy   s3         s4
0  0.0   6   6  0.0  0.000000  1.11   s0   s0  1.11   True   True   0   59.827760   59   >>>59<<<
1  1.0   5   5  1.0  1.010000  2.22   s1   s1  2.22  False  False   1  108.506052  108  >>>108<<<
2  2.0   4   4  2.0  2.002000  3.33    狗   s2  3.33   True   True   2  159.510324  159  >>>159<<<
3  3.0   3   4  NaN  3.000300  4.44   汽车   s2  4.44  False  False   3  209.039987  209  >>>209<<<
4  4.0   2   1  4.0  4.000040  5.55  NaN  nan  5.55    NaN   True   4  260.481408  260  >>>260<<<
5  5.0   1   1  5.0  5.000005  7.77   s5   s5  7.77  False  False   5  310.595830  310  >>>310<<<
6  NaN   0   0  6.0  6.000001  9.99   s6   s6  9.99   True   True   6  359.869259  359  >>>359<<<

### Question 20

Show how to define a mask using regex on one column, and numeric comparison on the other column

#### Answer

In [42]:
import re
aa = ddd()
mask = (aa.i2.map(lambda x: True if re.search(r'4',str(x)) else False)) & (aa.xx > 2)
display(mask)
display(aa[mask])

# more examples
# mask = ( df.a == 1) & (df.b == 2)
# mask = ( df.a == 1) | (df.b == 2)
# mask = ( df.a == 1) | df.b.isin([1,2,3])
# mask = ( df.a == 1) | df.b.map(lambda x: ......)
# mask = ( df.a == 1) | df.b.map(lambda x: ......)  |  df.c.map(lambda x: ......)

0    False
1    False
2    False
3     True
4    False
5    False
6    False
dtype: bool

    ii  i1  i2  ff      f1    f2  ss  s1    s2     bb     b1  xx          yy
3  3.0   3   4 NaN  3.0003  4.44  汽车  s2  4.44  False  False   3  209.653501

### Question 21

String operations on columns
<br>How to define a mask using a regular expression

In [43]:
aa = ddd()
mask = aa.ss.map(lambda x: True if re.search(r's[1,3]',str(x)) else False)
display(aa[mask])

    ii  i1  i2   ff    f1    f2  ss  s1    s2     bb     b1  xx          yy
1  1.0   5   5  1.0  1.01  2.22  s1  s1  2.22  False  False   1  107.758274