# Python Test 100
## Group 4

### Question 1

timeseries - a series indexed by datetime objects (or similar objects)<br>
Give examples of creating a timeseries

#### Answer

In [1]:
import sys, os
import pandas as pd
import numpy as np
import datetime as dt
mydates = [dt.datetime(2011,1,2), 
           dt.datetime(2011,1,5), 
           dt.datetime(2011,1,7), 
           dt.datetime(2011,1,8), 
           dt.datetime(2011,1,10), 
           dt.datetime(2011,1,12)]

ts = pd.Series(np.random.randn(6), index=mydates) 

ts = pd.Series(np.random.randn(1000), 
               index = pd.date_range('1/1/2000',periods=1000, normalize=True))

#   note: in above we use normalize=True to zero-out times. 
#   so ts.index = [2000-01-01 00:00:00, ..., 2002-09-26 00:00:00]

### Question 2

Show how to sort dictionary keys by keys or by values

#### Answer

In [2]:
dd = {11:5, 22:4, 33:3, 44:2, 55:1}
print(sorted(dd))                          # [11, 22, 33, 44, 55]
print(sorted(dd,key=dd.get))               # [55, 44, 33, 22, 11]
print(sorted(dd,key=dd.get, reverse=True)) # [11, 22, 33, 44, 55]

[11, 22, 33, 44, 55]
[55, 44, 33, 22, 11]
[11, 22, 33, 44, 55]

### Question 3

Show the uses sorted() function by using each of the parameters<br>
<b>sorted(iterable, cmp=None, key=None, reverse=False)</b>

#### Answer

In [3]:
# sorted(iterable, cmp=None, key=None, reverse=False) - returns new sorted list

aa=[1,2,3,11,12,13]
print(sorted(aa))                       # [1, 2, 3, 11, 12, 13]
print(sorted(aa,key=str))               # [1, 11, 12, 13, 2, 3]
print(sorted(aa,key=int))               # [1, 2, 3, 11, 12, 13]
print(sorted(aa,key=int,reverse=True))  # [13, 12, 11, 3, 2, 1]
print(sorted(aa,key=str,reverse=True))  # [3, 2, 13, 12, 11, 1]

[1, 2, 3, 11, 12, 13]
[1, 11, 12, 13, 2, 3]
[1, 2, 3, 11, 12, 13]
[13, 12, 11, 3, 2, 1]
[3, 2, 13, 12, 11, 1]

### Question 4

Show how to see variables I have defined in current ipython session
<br>    (dir(), locals(), globals() return too much)

#### Answer

In [4]:
# use magic command %who to print the list
# use magic command %who_ls to return the list

mylist = %who_ls
print(mylist)

['aa', 'dd', 'dt', 'mydates', 'ts']

### Question 5

Calculate number of business days between two dates

#### Answer

In [5]:
import numpy as np
import datetime as dt

dt1 = dt.date(2019,4,23)
dt2 = dt.date(2019,4,25)

# use numpy
cnt_np = np.busday_count(dt1, dt2)
print("np:",cnt_np)

# efficient way to calculate 
def working_days_in_range(from_date, to_date):
    from_weekday = from_date.weekday()
    to_weekday = to_date.weekday()
    # If start date is after Friday, modify it to Monday
    if from_weekday > 4:
        from_weekday = 0
    day_diff = to_weekday - from_weekday
    whole_weeks = ((to_date - from_date).days - day_diff) / 7
    workdays_in_whole_weeks = whole_weeks * 5
    beginning_end_correction = min(day_diff, 5) - (max(to_weekday - 4, 0) % 5)
    working_days = workdays_in_whole_weeks + beginning_end_correction
    # Final sanity check (i.e. if the entire range is weekends)
    return int(max(0, working_days))

cnt_eff = working_days_in_range(dt1, dt2)
print("eff:",cnt_eff)

# special libraries for bus. days calculations
# https://pypi.org/project/workdays/
# https://bitbucket.org/shelldweller/python-bizdatetime
pass

np: 2
eff: 2

In [6]:
import pandas as pd
import numpy as np

df = pd.DataFrame({ 'A' : ['1/1/2013', '2/2/2013', '3/3/2013'],
                    'B': ['1/12/2013', '4/4/2013', '3/3/2013']})
display(df)
print("-"*40)

df['Ad'] = pd.to_datetime(df['A'])
df['Bd'] = pd.to_datetime(df['B'])

display(df)
print("-"*40)

A = np.array(df['Ad'].values.astype('datetime64[D]'))
B = np.array(df['Bd'].values.astype('datetime64[D]'))
print(A)
print("-"*40)

df['DIFF'] = np.busday_count(A,B)
display(df)

          A          B
0  1/1/2013  1/12/2013
1  2/2/2013   4/4/2013
2  3/3/2013   3/3/2013

----------------------------------------

          A          B         Ad         Bd
0  1/1/2013  1/12/2013 2013-01-01 2013-01-12
1  2/2/2013   4/4/2013 2013-02-02 2013-04-04
2  3/3/2013   3/3/2013 2013-03-03 2013-03-03

----------------------------------------
['2013-01-01' '2013-02-02' '2013-03-03']
----------------------------------------

          A          B         Ad         Bd  DIFF
0  1/1/2013  1/12/2013 2013-01-01 2013-01-12     9
1  2/2/2013   4/4/2013 2013-02-02 2013-04-04    43
2  3/3/2013   3/3/2013 2013-03-03 2013-03-03     0